### ISSUE TITLE
Error: NuGet target in project.assets.json is still unavailable after restore. Please verify that the project has been restored. 

### ISSUE THREAD

**Issue by jarvis-89** [dotnet/upgrade-assistant#1021]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

I'm trying to upgrade the application developed with .net core 2.0 to .NET 6 with upgrade assistance. 

Getting error while executing `upgrade-assistant upgrade <Path to csproj or sln to upgrade>` command.

Getting following error.

![Screenshot 2022-01-20 165802](https://user-images.githubusercontent.com/55572047/150332236-ab35c975-ab03-461e-a17f-dfb0592ee9d3.jpg)

Tried following things:
1. Tried to restore with dotnet restore and retried to upgrade
2. Cleared nuget cache(s) from visual studio
3. Copied project.assets.json file from obj folder and pasted it at .csproj file's location

**Comment by sunandabalu** [comment]
@jarvis-89 Could you try running the tool in verbose mode `-v` and provide the `upgrade-assistant.clef` on that run?
