### ISSUE TITLE
Repeating Loop/Lockup with the Upgrade Assistant

### ISSUE THREAD

**Issue by MillerMark** [dotnet/upgrade-assistant#1023]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

![image](https://user-images.githubusercontent.com/4841528/150667198-062e3aea-934c-4da6-b9ff-8fbbf19f9abc.png)

I was upgrading a .NET Framework 4.7.2 project using the Upgrade Assistant. On the last step, it appears I accidentally hit "2" instead of "1", and then the command window proceeded to fill up with a repeating message - "Initializing upgrade step Select project to upgrade" (see the first screenshot).

After a while, the messages changed (see the second screenshot).

![image](https://user-images.githubusercontent.com/4841528/150667300-3da00965-b364-485b-9a60-f65f6d0eb674.png)

I copied as much text as was available in the cmd wintow and saved it into the file that is attached.

[CommandPromptText.txt](https://github.com/dotnet/upgrade-assistant/files/7919913/CommandPromptText.txt)

**Comment by sunandabalu** [comment]
@MillerMark Appears to be some weird async issue that went into a loop, were you able to complete your upgrade later with the right option? Could you also attach the `upgrade-assistant.clef` file?

**Comment by MillerMark** [comment]
I was able to complete the upgrade later (after exiting and restarting the tool). Where can I find upgrade-assistant.clef?

**Comment by sunandabalu** [comment]
> I was able to complete the upgrade later (after exiting and restarting the tool). Where can I find upgrade-assistant.clef?

It will be in the same folder where you are running the upgrade-assistant from

**Comment by brandonh-msft** [comment]
Closing stale issues; if you're able to provide the clef file, though, let us know.
