### ISSUE TITLE
The analyze command doesn't identify NuGet packages that need updated to newer versions

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#1034]
One of the useful features of the `analyze` commands is the ability to see which NuGet dependencies will need to change as part of upgrade.

This doesn't work for packages that need updated to work with the new TFM, though. As an example, I have a project with a dependency on EntityFramework version 6.1. This version of the EF package won't work with .NET 6 so I would expect the `analyze` command to identify the package and suggest updating to version 6.4, instead (since that version works with .NET 6).

The `upgrade` command correctly makes that replacement but the analyze command doesn't list EntityFramework as a package that needs to change.

I haven't debugged through the tool to root cause this yet but perhaps the analyze command is evaluating whether NuGet packages will work based on the current TFM instead of the future one? Or perhaps the target compatibility reference analyzer isn't used by the analyze command?

**Comment by sunandabalu** [comment]
> I haven't debugged through the tool to root cause this yet but perhaps the analyze command is evaluating whether NuGet packages will work based on the current TFM instead of the future one? Or perhaps the target compatibility reference analyzer isn't used by the analyze command?

`analyze` command analyzes on target TFM and not on the current TFM. The code path for `analyze` command uses the `TargetCompatibilityReferenceAnalyzer` similar to upgrade, I'm surprised that `upgrade` was able to recognize the package as potential upgrade and not `analyze`. Did you look at the SARIF report as well, does is it also not call out the package?

**Comment by mjrousos** [comment]
Thanks, @sunandabalu, for the details. Yea, I looked at the report and it doesn't mention EF. It's good we're using the target TFM. There must be something else going on here causing the package not to be flagged.

**Comment by sunandabalu** [comment]
@mjrousos When you get a chance, since you have a repro, it will be great to understand what is happening in debug mode.

**Comment by brandonh-msft** [comment]
@mjrousos can you provide the repro sample somewhere for me? thanks!

**Comment by mjrousos** [comment]
Any netfx-targeted project with a dependency on [EntityFramework](https://www.nuget.org/packages/EntityFramework) 6.0.0 would work as a repro. That package is a common one we see customers using that UA will upgrade to EntityFramework 6.4.4.

Analysis doesn't list that as a change that's needed, though.

I took a look and see what's causing the problem, though. It looks like there are some bugs in how we resolve package dependencies for non-SDK style projects. So, in analysis scenarios (when the target project is not SDK-style) we're not getting the list of NuGet dependencies properly. I'll create a PR.
