### ISSUE TITLE
Error attempting to install the .NET Upgrade Assistant

### ISSUE THREAD

**Issue by mmuresan** [dotnet/upgrade-assistant#1036]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows 10 Pro, version = 21H1

Steps to reproduce:
1. Installed the .NET 6 SDK 64bit
2. Executed dotnet from cmd and all seems fine.
3. Executed dotnet tool install -g upgrade-assistant

Got the following errors:
C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5): error : Failed to retrieve information about 'upgrade-assistant' from remote source 'https://nuget.org/FindPackagesById()?id='upgrade-assistant'&semVerLevel=2.0.0'. [C:\Users\mmuresan\AppData\Local\Temp\ovampbs0.5fx\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5): error :   Response status code does not indicate success: 404 (Not Found). [C:\Users\mmuresan\AppData\Local\Temp\ovampbs0.5fx\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by nhiorns** [comment]
I had the same issue, the following worked for me:

If you follow the link at the bottom of your issue, or this one: https://docs.microsoft.com/en-gb/dotnet/core/tools/troubleshoot-usage-issues#nuget-feed-cant-be-accessed and go to the **401 (Unauthorized)** section, it will advise to try running the command with the following additional arguments:

dotnet tool install -g **--ignore-failed-sources** \<toolName\>

This will ignore any other NuGet feeds that are erroring and will continue until the Microsoft feed processes the request to install.

**Comment by sunandabalu** [comment]
@mmuresan Like @nhiorns suggested please try with `--ignore-failed-sources` to see if it helps.

**Comment by jcrawfor74** [comment]
The issue for me was that I had add extra "non-standard" nuget repositories. 

For example I had a reference to our own Azure DevOps Nuget Feed. 
It was the reference to our Azure DevOps feed that was throwing the unauthorized error, as obviously you need to be authenticated to be able to access the private Azure DevOps Nuget feed.

To fix I did the following:
* opened a project in Visual Studio
* choose manage nuget packages
* click on the settings icon
* untick any non standard nuget feeds
* click ok

After doing this run the command and it all worked
