### ISSUE TITLE
Extension: Adding a template file to a directory that does not exist in destination fails

### ISSUE THREAD

**Issue by ujjwalchadha** [dotnet/upgrade-assistant#1049]
I'm working on the [fork of the project here](https://github.com/sotteson1/upgrade-assistant/tree/uwp-support) and adding the support to convert UWP apps to WinUI3 (WindowsAppSDK) in the Microsoft.DotNet.UpgradeAssistant.Extensions.Windows extension.

It seems like when I try to add a template file that is not in the root, the code fails with a directory not found exception at [this line](https://github.com/dotnet/upgrade-assistant/blob/057ffba0656270dc5d83c015748ac56daed55886/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Templates/TemplateInserterStep.cs#L147) for which I am using a temporary workaround by adding [this line of code](https://github.com/sotteson1/upgrade-assistant/blob/e81cbc619d0afab4755313984229a3254cdd3a19/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Templates/TemplateInserterStep.cs#L147) in the fork.

Steps to repro: 
Add a template file that is not in the same directory as the template config file, but in a subdirectory, and that subdirectory does not exist in the destination

**Comment by sunandabalu** [comment]
@twsouthwick Is this something you can provide some insights on?
