### ISSUE TITLE
Add more functions to IProject like RemoveItem

### ISSUE THREAD

**Issue by ujjwalchadha** [dotnet/upgrade-assistant#1050]
When implementing Updater<IProject>, the collection of project objects does not have enough functionality to perform operations like updating or removing an item from the project file.

I suggest exposing a more flexible object like ProjectRoot for performing operations that the current IProject helper functions do not provide and allow extensions to make use of it.

**Comment by ujjwalchadha** [comment]
@sunandabalu @twsouthwick do we have any update for this?
I am looking for IProjectFile.RemoveItem method which does not seem to be present.

**Comment by sunandabalu** [comment]
@ujjwalchadha Per our offline conversation, feel free to put up a PR with the change we will be happy to review it :)
