### ISSUE TITLE
Error in step upgrade-assistant upgrade

### ISSUE THREAD

**Issue by pjgironal** [dotnet/upgrade-assistant#1053]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Step: dotnet tool install -g upgrade-assistant -> results OK

Step: upgrade-assistant analyze <Path to csproj or sln to upgrade> -> Results OK

Step: upgrade-assistant upgrade <Path to csproj or sln to upgrade> -> Results show the following error:

'upgrade' is not recognized as an internal or external command,
operable program or batch file.

Thank you for your support.

**Comment by sunandabalu** [comment]
@pjgironal its weird that `analyze` command works and `upgrade` doesnt. Could you provide the version number that you are using for upgrade-assistant?

**Comment by pjgironal** [comment]
Thank you for your support. I'm using Windows 11 latest version and my upgrade-assistant version is Microsoft .NET Upgrade Assistant v0.3.310801+057ffba0656270dc5d83c015748ac56daed55886

**Comment by pjgironal** [comment]
Solved
