### ISSUE TITLE
Tutorial requires VS 2022 but recommends Microsoft SARIF Viewer which only supports 2019

### ISSUE THREAD

**Issue by wsheemsft** [dotnet/upgrade-assistant#1057]
### Describe the bug
The tutorial requires Visual Studio 2022 but recommends a SARIF viewer that is only compatible with Visual Studio 2017 and 2019. The viewer should be updated, or the recommendation removed.

### To Reproduce
1. Visit the [tutorial intro](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/intro). Note how it says the Prerequisites are "Visual Studio 2022 17.0 or later".
2. Visit the [Install and run upgrade-assistant](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant) page. It recommends "[VS extension for SARIF Viewer](https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer&WT.mc_id=dotnet-35129-website) for a richer experience."
3. Try to install [VS extension for SARIF Viewer](https://marketplace.visualstudio.com/items?itemName=WDGIS.MicrosoftSarifViewer&WT.mc_id=dotnet-35129-website). It is not compatible with VS 2022.

**Comment by sunandabalu** [comment]
@wsheemsft Good catch! we will edit the ReadMe to add the link for the right version of SARF Viewer
