### ISSUE TITLE
Mismatch in parameter ordering between Github documentation, what the tool expects and what the tool help says.

### ISSUE THREAD

**Issue by cyclr-adrian** [dotnet/upgrade-assistant#1070]
I have just installed version `0.3.310801+057ffba0656270dc5d83c015748ac56daed55886` of the `upgrade-assistance` tool by running the following command:
```
dotnet tool install -g upgrade-assistant
```

I ran the tool's help command:
```
upgrade-assistant --help
```
and got an output:
```
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.3.310801+057ffba0656270dc5d83c015748ac56daed55886

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

Makes a best-effort attempt to upgrade .NET Framework projects to current, preview, or LTS versions of .NET.

This tool does not completely automate the upgrade process and it is expected that projects will have build errors after the tool runs. Manual changes will be required to complete the upgrade.

This tool's purpose is to automate some of the 'routine' upgrade tasks such as changing project file formats and updating APIs with near-equivalents in the selected target framework. Analyzers added to the project will highlight the remaining changes needed after the tool runs.
Usage:
  upgrade-assistant [options] [command]

Options:
  --version       Show version information
  -?, -h, --help  Show help and usage information

Commands:
  analyze <project>
  upgrade <project>
  extensions
  features
```

Therefore using the specified usage pattern `upgrade-assistant [options] [command]` (from the help output), I tried running the following command:
```
upgrade-assistant --verbose --target-tfm-support LTS analyze Cyclr.sln
```
This failed with an output:
```
'--verbose' was not matched. Did you mean '--verbose'?
'--target-tfm-support' was not matched. Did you mean '--target-tfm-support'?
'LTS' was not matched. Did you mean '-v', or '-e', or '-h'?
Unrecognized command or argument '--verbose'
Unrecognized command or argument '--target-tfm-support'
Unrecognized command or argument 'LTS'
```

Then looking at the Github documentation [https://github.com/dotnet/upgrade-assistant#analyze-path](https://github.com/dotnet/upgrade-assistant#analyze-path) it contradicts the usage pattern of the tool's help output by saying that it is required to be this usage pattern:
```
upgrade-assistant [command] [options] <project>
```

So using the specified usage pattern from Github `upgrade-assistant [command] [options] <project>`, I tried running the following command by swapping the `[Command]` and the `[Options]` around:
```
upgrade-assistant analyze --verbose --target-tfm-support LTS Cyclr.sln
```
This time the tool ran successfully.

Looks like the help information output from the tool doesn't match the Github documentation [https://github.com/dotnet/upgrade-assistant#analyze-path](https://github.com/dotnet/upgrade-assistant#analyze-path) or what the tool is expecting.

**Comment by sunandabalu** [comment]
@cyclr-adrian Good catch! We would love a quick PR to correct this in the `--help` documentation, feel free to put up a PR if you are upto it :)
