### ISSUE TITLE
dotnet \sdk\6.0.201 upgrade assistant error

### ISSUE THREAD

**Issue by KDGunther** [dotnet/upgrade-assistant#1073]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-sdk
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
![DotNetUpgradeError](https://user-images.githubusercontent.com/101827048/159186883-95ff7c25-1e24-4a3f-971e-9ed2bbfd1ada.JPG)
![WindowsVersion](https://user-images.githubusercontent.com/101827048/159186886-e089ea98-22cf-4d4d-845c-9aba82640301.JPG)
.
Kurt Gunther, kdgunther@mapgistics.com, 951-323-2820

**Comment by sunandabalu** [comment]
@KDGunther looks like you might be seeing issues due to some private nuget feeds in your NuGet.Config, could you run the command with `--ignore-failed-sources` and see if it helps?

**Comment by brandonh-msft** [comment]
This should also be solved by our new instructions which explicitly add the nuget source where the tool is distributed to the cmd line for installation.
