### ISSUE TITLE
upgrade-assistant upgrade . This tool is not supported on non-Windows platforms due to dependencies on Visual Studio.

### ISSUE THREAD

**Issue by Amondale** [dotnet/upgrade-assistant#1076]
## Summary

How about putting that higher in the README.MD, rather than having us assume it will work on Linux/Mac ootb?

## Motivation and goals

10-15 minutes time wasted to discover the tool isn't as XPLAT as it might be?

## In scope

While we're at it can we get a "mission statement" written for this valuable tool? I foresee that because there were both .Net *CORE* 4.6.1 and .Net *Framework* 4.6.1, there could potentially be confusion generated by what the tool can accomplish.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Wonder how the VS dependencies could be "de-coupled" ... or maybe we're stuck waiting for the first cut of VS built completely on .NET 6++.

**Comment by shreenivas-asurion** [comment]
It doesnt work on Mac? OMG, wasted visual studio subscription and time.

**Comment by mattiaskjellsson** [comment]
Windows isn't listed as a prerequisite on this page, but it looks like it is on the [microsoft domain page](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview) Not sure about the connection in between the pages though.

**Comment by leslie-alldridge** [comment]
really, no Mac support in 2023? that's a shame.

**Comment by akhilgite** [comment]
Seriously, no extension for MAC? Why Microsoft is releasing half baked tools.
