### ISSUE TITLE
WCF Analyzers and Codefixers

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/upgrade-assistant#1083]
- [x] #624 
- [x] #363

**Comment by mjrousos** [comment]
To add more detail here, with CoreWCF releasing as a 1.0 soon, UA should help users migrate from WCF server APIs to CoreWCF.

**Comment by spur19** [comment]
> To add more detail here, with CoreWCF releasing as a 1.0 soon, UA should help users migrate from WCF server APIs to CoreWCF.

Hey, with CoreWCF 1.0 released, is there a timeline by when this feature will be available?

**Comment by brandonh-msft** [comment]
@SimonaLiao this should be the issue your PR tracks against :)
