### ISSUE TITLE
Error downloading the nuget package

### ISSUE THREAD

**Issue by RobDehn1** [dotnet/upgrade-assistant#1099]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi 
Error
Microsoft Windows [Version 10.0.22000.556]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Robert>dotnet tool install -g upgrade-assistant
C:\Program Files\dotnet\sdk\6.0.201\NuGet.targets(130,5): error : Failed to retrieve information about 'upgrade-assistant' from remote source 'https://nuget.telerik.com/nuget/FindPackagesById()?id='upgrade-assistant'&semVerLevel=2.0.0'. [C:\Users\Robert\AppData\Local\Temp\4sunw0ud.3zi\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.201\NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Logon failed.). [C:\Users\Robert\AppData\Local\Temp\4sunw0ud.3zi\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

C:\Users\Robert>

**Comment by sunandabalu** [comment]
@RobDehn1 Looks like you are having permissions issues based on what is on your NuGet.config, could you try installing with `--ignore-failed-sources`?
