### ISSUE TITLE
Can't get analyze to work, please help!

### ISSUE THREAD

**Issue by thepunkduck** [dotnet/upgrade-assistant#1103]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I have installed upgrade-assistant and am working through the "Get started" guide (https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant)

I am attempting to analyze my solution. I navigate to it's directory and then attempt to run it as specified. Here is my output:
```

C:\Users\James>dotnet tool install -g upgrade-assistant
Tool 'upgrade-assistant' is already installed.

C:\Users\James>cd C:\Users\James\Visual Studio 2017\Qintegral\LamRockPhysicsLib

C:\Users\James\Visual Studio 2017\Qintegral\LamRockPhysicsLib>dir
 Volume in drive C has no label.
 Volume Serial Number is E08B-9011

 Directory of C:\Users\James\Visual Studio 2017\Qintegral\LamRockPhysicsLib

20/04/2022  03:30 PM    <DIR>          .
20/04/2022  03:30 PM    <DIR>          ..
20/04/2022  06:08 PM    <DIR>          LamRockPhysicsLib
20/04/2022  03:30 PM             1,157 LamRockPhysicsLib.sln
               1 File(s)          1,157 bytes
               3 Dir(s)  12,897,001,472 bytes free

C:\Users\James\Visual Studio 2017\Qintegral\LamRockPhysicsLib>upgrade-assistant analyze LamRockPhysicsLib.sln
File does not exist: analyze
Unrecognized command or argument 'LamRockPhysicsLib.sln'

-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.226201+4598a23e60b7571063570ee21e868f0f446b5b0f -
-----------------------------------------------------------------------------------------

Makes a best-effort attempt to upgrade .NET Framework projects .... etc


Any ideas what I'm doing wrong here? I have tried the full path and everything, but it's always a similar error.

Many thanks
James

**Comment by sunandabalu** [comment]
@thepunkduck Have you tried running from a different folder with a full path to the sln? Also does it show the help content when you just type `upgrade-assistant` or `upgrade-assistant analyze`?

**Comment by brandonh-msft** [comment]
@thepunkduck could we also get you to upgrade to the latest version and give it a shot just so we're on the same page w/ whatever we may need to debug? `dotnet tool update -g upgrade-assistant`
thanks!
