### ISSUE TITLE
The tool should generate a report at the end of the conversion explaining the conversions done as well as the next steps

### ISSUE THREAD

**Issue by ujjwalchadha** [dotnet/upgrade-assistant#1128]

**Comment by brandonh-msft** [comment]
@ujjwalchadha this feels like a dupe of #368  do you agree? If so you can close

**Comment by ujjwalchadha** [comment]
@brandonh-msft this is slightly different where we tell users what next manual steps to follow. Those steps are specific to UWP to WinAppSDK upgrade and might not depend on the changes made by the tool but general steps like walking through TODO comments, moving some code etc. 

Although I think both can be combined and this step can be included as a sub step of #368

**Comment by brandonh-msft** [comment]
If you want to leave this so you have something to capture this type of work specifically for UWP I'm fine w/ that. I'll leave it up to you if you want to close / leave open :)

**Comment by ujjwalchadha** [comment]
Closing as it is dup of #460
