### ISSUE TITLE
Try-Convert not found.

### ISSUE THREAD

**Issue by jamesbell43** [dotnet/upgrade-assistant#1140]
"Try-Convert not found." - but this NuGet package is on my machine (try-convert.0.7.222801.nupkg)

**Comment by sunandabalu** [comment]
@jamesbell43 Are you seeing while running `upgrade-assistant`? Could you please provide the `upgrade-assistant.clef`?

**Comment by jamesbell43** [comment]
The Microsoft page for upgrade-assistant https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant did not specify the need to first install try-convert like this: dotnet tool install -g try-convert
After installing try-convert, I was able to proceed. Thank you!

**Comment by sunandabalu** [comment]
@jamesbell43 Curious what version of upgrade-assistant you are using? We had removed the need to have try-convert installed prior to using UA a few versions back hence the question.

**Comment by jamesbell43** [comment]
version 0.2.212405

**Comment by sunandabalu** [comment]
> version 0.2.212405

Ah that is a really old version, if you upgraded to latest you will see that try-convert is built-in and is not expected to be on the machine for UA to run.
