### ISSUE TITLE
Is not compatible with net5.0

### ISSUE THREAD

**Issue by jbaylon3** [dotnet/upgrade-assistant#1143]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I keep trying to run the "upgrade-assistant analyze" part of the upgrade assistant and it keeps telling me that it is not compatible with net5.0. I already downloaded .NET6 but it keeps giving me the same error. Do you know what could be causing this issue?

**Comment by sunandabalu** [comment]
@jbaylon3 Could you please share the `upgrade-assistant.clef` so we can look at exact errors observed?

**Comment by jbaylon3** [comment]
It is not letting me share it. It is telling me that the file is not supported

**Comment by brandonh-msft** [comment]
@jbaylon3 I suggest c/p into a [gist](https://gist.github.com/), or uploading as gist and then linking here. Thanks!
