### ISSUE TITLE
Upgrade: wrong version, always defaults to .Net 2 which is out of support, make Default TFM --> .NET 6 LTS

### ISSUE THREAD

**Issue by fasteddys** [dotnet/upgrade-assistant#1144]
Hello, 

## Please consider that this tool should _support and default to the latest LTS .NET Core version_, step one should be a `prompt on which TFM, and default to .NET 6` to catch the latest bug fixes etc.

can you please ensure we have a config file/setting to make the `default TFM .NET 6 LTs`

Upgrade: `Default upgrades should be current versions, for e.g. ,NET 6 Core LTS` wrong version, always defaults to .Net 2 which is out of support, make default .NET 6 LTS

Currently the tool `upgrades are struggling/failing` since they first upgrade to .NET 2.0 then upgrade again to 5.0 and then fail at .NET Core 6.

**Comment by twsouthwick** [comment]
Can you explain what you are seeing? The tool does default to the latest LTS. You'd see this in the choice for TFMs when it comes to applications themselves (not libraries).

If you are referring to the TFM choices it makes for libraries, that is actually an orthogonal decision. .NET Standard 2.0 is the default we start with, and then various other factors may cause it to chose .NET 6, or .NET 6-windows, or .NET 6-windows10.0.xxx. This keeps libraries available to be consumed by the most broad set of applications. .NET Standard 2.0 libraries are fully supported on both .NET Framework, .NET Core, and .NET 5+ without having to duplicate code or multi-target.

**Comment by nate141** [comment]
Can we at least have an option to upgrade libraries to net6 currently even if I'm setting `--target-tfm-support LTS` it still only updates to netstandard2.0 (these libraries are only used internally & I'm trying to upgrade them all to net6)

**Comment by twsouthwick** [comment]
We should check packages for their support and use that to determine a starting TFM. EF 6.4.4 supports .NET Standard 2.1+, so that would have fixed the issue as well.

**Comment by brandonh-msft** [comment]
> Correct. `--force-TFM` would be amazing. @brandonh-msft besides _'having everything on .NET 6'_, netstandard2.0 doesn't actually support everything & I was actually having weird issues with `EntityFramework` (not core - I needed to downgrade to 6.2) until I changed the TFM of my library to net6. That's beside the fact that I would like to use C# 10 / .net6 features, so why do the upgrade in 2 steps

gotchya - thanks!



> We should check packages for their support and use that to determine a starting TFM. EF 6.4.4 supports .NET Standard 2.1+, so that would have fixed the issue as well.
@twsouthwick, It would solve for the "_full_ support" problem, but not the user's desire to take advantage of c# 10/net6 goodness, though, right?

**Comment by fasteddys** [comment]
Hello, thanks for the response, please see below for your answers..

> Can you explain what you are seeing? The tool does default to the latest LTS. You'd see this in the choice for TFMs when it comes to applications themselves (not libraries).
> 

`Default: TFM = should be latest LTS (.NET6)` or configurable
We are not seeing the latest LTS upgrade, we have run it several times on 3 different machines, and it keeps defaulting and pumps out migration to .NET 2.0,  trying the TFM flags to .NET6 doesn't do anything.


`Option`: uninterrupted option needed please/fully automated upgrade
Also having an `uninterrupted/fully automated upgrade option` at the solution level would be great, or accept all configuration/defaults (from a config file for the 5 or 6 options is needed). _Typically the first pass is blitz to see what runs and what failed_, using this we can revisit surgically fix items.

**Comment by twsouthwick** [comment]
> `Option`: uninterrupted option needed please/fully automated upgrade Also having an `uninterrupted/fully automated upgrade option` at the solution level would be great, or accept all configuration/defaults (from a config file for the 5 or 6 options is needed). _Typically the first pass is blitz to see what runs and what failed_, using this we can revisit surgically fix items.

You may be interested in the `--non-interactive` flag for this

**Comment by brandonh-msft** [comment]
Are folks in general agreement that we can close this in favor of #770?

**Comment by twsouthwick** [comment]
That's reasonable to me - it's a design proposal that's been around for a year :)
