### ISSUE TITLE
Upgrade assistant hangs after "Loaded 6 extensions"

### ISSUE THREAD

**Issue by MarvinNorway** [dotnet/upgrade-assistant#1147]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: Windows 10 Enterprise 21H2

Microsoft .NET Upgrade Assistant v0.3.310801+057ffba0656270dc5d83c015748ac56daed55886
Visual Studio Professional with latest updates 

We've successfully used the tool on other projects.
When I just tried to run it on another project, it is stuck after  "Loaded 6 extensions".

`[16:01:27 INF] Loaded 6 extensions`

When I kill the dotnet.exe process, there is an error message that msbuild was not found:

`[16:05:14 ERR] No supported MSBuild found. Ensure `dotnet --list-sdks` show an install that is 64-bit`
`[16:05:14 ERR] MSBuild not found`
`Execute managed assembly exit code: 0x2`
`Waiting for breadcrumb thread to exit...`
`Done waiting for breadcrumb thread to exit...`

But that doesn't make any sense as I am running the code from a Developer PowerShell and of course msbuild is installed, as well as several SDKs.

**Comment by sunandabalu** [comment]
@MarvinNorway Is this behavior only observed in certain type of projects? Could you please share the `.csproj` and `upgrade-assistant.clef` file?

**Comment by brandonh-msft** [comment]
@MarvinNorway  Just to double-check can you post the output of your `dotnet --list-sdks`?

**Comment by MarvinNorway** [comment]
@brandonh-msft 

`1.1.8 [C:\Program Files\dotnet\sdk]
1.1.11 [C:\Program Files\dotnet\sdk]
1.1.12 [C:\Program Files\dotnet\sdk]
1.1.13 [C:\Program Files\dotnet\sdk]
1.1.14 [C:\Program Files\dotnet\sdk]
2.1.101 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
2.1.818 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.419 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]
`

**Comment by MarvinNorway** [comment]
@brandonh-msft
That was from the regular PowerShell window. I couldn't figure out how to redirect the output from the Visual Studio PowerShell to a file. But the tool hangs in both, so I guess it doesn't really matter...

**Comment by VentuzKarolStrozynski** [comment]
Same problem here.
This worked a few month ago with an old version but is broken since some update of the upgrade-assistent.

**Comment by brandonh-msft** [comment]
@MarvinNorway & @VentuzKarolStrozynski 
Can I get you to update to the latest version and run with `-v` option, then attach the output here along with CLEF file? Want to make sure we're all on the same page as I get to the root of this and see what's going on.

**Comment by VentuzKarolStrozynski** [comment]
I did the update and I'm running from a Command Prompt with Admin rights: _upgrade-assistant upgrade --skip-backup -v XYZ.sln 1> UA_out.txt 2>&1_
The upgrade-assistent runs until it hangs with this last output in line 4406:
_[10:00:10 DBG] Using Visual Studio v17.2.32526.322 [C:\Program Files\Microsoft Visual Studio\2022\Professional]_
After waiting a few minutes I close the command window and the last output lines are written. Only then the .clef file is written.

Thank you for looking into that
[UA.zip](https://github.com/dotnet/upgrade-assistant/files/8947046/UA.zip)
!

**Comment by brandonh-msft** [comment]
@sunandabalu / @mjrousos / @twsouthwick 

Ack. Unfortunately the CLEF nor the output from @VentuzKarolStrozynski are providing any insight into what could be hanging from my vantage point.
As for @MarvinNorway the issue you're seeing there is one we have [a fix forthcoming for](https://github.com/dotnet/upgrade-assistant/pull/1162) as there is a regression in MSbuild on 6.0.400 preview right now. I'm currently waiting for one more PR before I build the next ver of UA which will have this fix in it.

**Comment by brandonh-msft** [comment]
Hi @MarvinNorway & @VentuzKarolStrozynski !
Can I get you to try today's release of UA to see if the problem has gone away for you? 🤞🏻🤞🏻

**Comment by VentuzKarolStrozynski** [comment]
Hi @brandonh-msft !
The problem still persists on my main dev machine.
This is where is hangs:
_[10:46:20 INF] Loaded 8 extensions

Telemetry
----------
The .NET tools collect usage data in order to help us improve your experience. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_UPGRADEASSISTANT_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about Upgrade Assistant telemetry: https://aka.ms/upgrade-assistant-telemetry
Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry_

I tested another machine and it does not have this problem.
So the question is: How to find out the substantial difference between those two systems.

**Comment by brandonh-msft** [comment]
@VentuzKarolStrozynski thanks for this troubleshooting! Could you run `dotnet --list-sdks` on both the working and broken box and post those here (labeled accordingly)?

Thanks in advance!

**Comment by VentuzKarolStrozynski** [comment]
Hi Brandon,
here you are:

**NOT WORKING SYSTEM**:
Tracing enabled @ Thu Jul 21 08:14:52 2022 GMT
--- Invoked dotnet [version: 6.0.7, commit hash: 0ec02c8c96e2eda06dc5b5edfdbdba0f36415082] main = {
dotnet
--list-sdks
}
Reading fx resolver directory=[C:\Program Files\dotnet\host\fxr]
Considering fxr version=[1.0.5]...
Considering fxr version=[1.1.9]...
Considering fxr version=[2.0.9]...
Considering fxr version=[2.1.30]...
Considering fxr version=[2.2.2]...
Considering fxr version=[3.0.0-preview-27324-5]...
Considering fxr version=[3.1.27]...
Considering fxr version=[5.0.17]...
Considering fxr version=[5.0.9]...
Considering fxr version=[6.0.4]...
Considering fxr version=[6.0.5]...
Considering fxr version=[6.0.7]...
Detected latest fxr version=[C:\Program Files\dotnet\host\fxr\6.0.7]...
Resolved fxr [C:\Program Files\dotnet\host\fxr\6.0.7\hostfxr.dll]...
Loaded library from C:\Program Files\dotnet\host\fxr\6.0.7\hostfxr.dll
Invoking fx resolver [C:\Program Files\dotnet\host\fxr\6.0.7\hostfxr.dll] hostfxr_main_startupinfo
Host path: [C:\Program Files\dotnet\dotnet.exe]
Dotnet path: [C:\Program Files\dotnet\]
App path: [C:\Program Files\dotnet\dotnet.dll]
Tracing enabled @ Thu Jul 21 08:14:52 2022 GMT
--- Invoked hostfxr_main_startupinfo [commit hash: 0ec02c8c96e2eda06dc5b5edfdbdba0f36415082]
Checking if CoreCLR path exists=[C:\Program Files\dotnet\coreclr.dll]
--- Executing in muxer mode...
Using the provided arguments to determine the application to execute.
Application '--list-sdks' is not a managed executable.
Multilevel lookup is true
Gathering SDK locations in [C:\Program Files\dotnet]
Found SDK version [1.1.11]
Found SDK version [2.1.202]
Found SDK version [2.1.526]
Found SDK version [2.2.104]
Found SDK version [3.0.100-preview-010184]
Found SDK version [3.1.421]
Found SDK version [5.0.203]
Found SDK version [5.0.214]
Found SDK version [5.0.303]
Found SDK version [5.0.408]
Found SDK version [6.0.202]
Found SDK version [6.0.203]
Found SDK version [6.0.300]
Found SDK version [6.0.302]
1.1.11 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]
3.1.421 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]
6.0.302 [C:\Program Files\dotnet\sdk]

**WORKING SYSTEM**:
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
3.1.418 [C:\Program Files\dotnet\sdk]
5.0.406 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]

**Comment by brandonh-msft** [comment]
Hmm so we have a lot more .NET SDKs on the "problem" system than the working one. That's pretty interesting. Wondering what would happen if you were to uninstall some/all of the ones you don't need on the problem system and/or get it to the same state as the working one? Is that something you could try out or do you require _all_ of those SDKs?

**Comment by mast76** [comment]
Duplicate of #1395 and #1379
