### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by sbrockway** [dotnet/upgrade-assistant#1148]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am trying to install the upgrade assistant but get the following error.
I am able to browse to the index.json url shown below via the Chrome browser.
Windows 10.0.19044 (21H2)
Running from PowerShell v7.2.4 as Admin

C:\repos> dotnet tool install -g upgrade-assistant
C:\Users\sbrockway\AppData\Local\Temp\145uk1zv.ooo\restore.csproj : error NU1301: Unable to load the service index for
source https://pkgs.dev.azure.com/edmentum/_packaging/Internal/nuget/v3/index.json.
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
C:\repos>

**Comment by twsouthwick** [comment]
It does, but that doc doesn't have that flag. The README here does. For future reference:

```
dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources upgrade-assistant
```
