### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Aravind2606** [dotnet/upgrade-assistant#1155]
I tried installing the tool but when I run any commands of upgrade-assistant, I just get Access is denied issue. Tried updating & reinstalling the tools but the issue remains.

Even tried to run the .exe directly, but getting the same Access is denied error. Not sure what's going wrong.

![image](https://user-images.githubusercontent.com/104636918/172837109-76cc9a5e-a505-4e74-9009-30d0723a64ad.png)

![image](https://user-images.githubusercontent.com/104636918/172837195-4fbf3722-e865-4521-a6a8-26ed2572f1e6.png)

**Comment by sunandabalu** [comment]
@Aravind2606 could you try installing upgrade-assistant in a different folder and try?
