### ISSUE TITLE
HttpRequest.Url.Scheme and HttpRequest.Url.Host -> HttpRequest.Scheme/HttpRequest.Host

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#1159]
The `HttpRequest` type in ASP.NET Core no longer has a URL type, but many of the common properties accessed from the request's URL (host and scheme, for example) are now available directly on HttpRequest, instead. Upgrade Assistant should make this code change, if needed, in ASP.NET Core apps.

**Comment by twsouthwick** [comment]
This is available from the Microsoft.AspNetCore.SystemWebAdapters package
