### ISSUE TITLE
zsh: command not found: upgrade-assistant

### ISSUE THREAD

**Issue by pablobfs** [dotnet/upgrade-assistant#1185]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After install the tool, I tried to run the command and the command was not found.
I'm running with a Mac M1.

**Comment by github4es** [comment]
From the pre-reqs, it looks like this is not supported on the Mac :-(

**Comment by brandonh-msft** [comment]
@pablobfs your initial statement says your OS is windows but then you said you're running on a Mac M1. Is this to say you're running something like Parallels and Windows emulation on your mac?
