### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mlmolefe2** [dotnet/upgrade-assistant#1190]
- [x] Include the log file `upgrade-assistant.clef` that is produced in the working directory

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
- Include the output of `dotnet --list-sdks`
- Include the output of `upgrade-assistant --version`

**Comment by brandonh-msft** [comment]
@Mlmolefe2 I think we're missing your CLEF and some context on your report? Can you try filling it out the above template and re-attaching? Thanks!

**Comment by Mlmolefe2** [comment]
Will do... thnx.
