### ISSUE TITLE
Corrupted/Disabled Project

### ISSUE THREAD

**Issue by RyanNewmanTruGreen** [dotnet/upgrade-assistant#1197]
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory
'upgrade-assistant.clef' file was not found on my local machine.

### Describe the bug
A clear and concise description of what the bug is:
I was trying the Upgrade-Assistant out as an option to upgrade from dotnet2.2 to dotnet3.1 or later (preferably net6) for our existing Bot Skills, since dotnet 2.2 is out of support. We have a Bot Framework SDK that we use as a skills bot for our Power Virtual Agents. Upgrade-Assistant caused an issue that I can’t get rid of for this solution.
 
The issue is: When removing all existing local files and the project itself from my machine to start a clean slate and then cloning the project from DevOps, the solution no longer debugs on my machine, the error given when trying to debug:   “The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[16672] dotnet.exe' has exited with code 2147516566 (0x80008096).” Also there now exists a couple of files in the "Git Changes" tab of Visual Studio that have never existed before on my machine with two folders nested inside of a .vs folder: ProjectEvaluation which contains a metadata.v2 file and projects.v2 file. The other folder is FileContentIndex folder containing a read.lock file and a file with a name that changes everytime I open Visual Studio currently it is  6c1eddf8-dc54-4886-a5fe-fc2c7380acfe.vsidx .
 
Before trying the Upgrade-Assistant, the solution would debug with no issues other than some warnings for updating the version. After the Upgrade-Assistant I noticed that read.lock file along with some other file and a  ContentIndexFile folder along with ProjectEvaluation folder that contains metadata.v2 and projects.v2, these are found inside of the “Git Changes” tab of Visual Studio. I have tried other projects where we have a Git repository in DevOps and these projects work fine, fortunately for the other projects the read.lock and other files do not exist.

### To Reproduce
To reproduce on my local machine, just trying to debug give an issue. I started fresh by removing the project including all the files, empty the recycle bin, and remove Visual Studio from the Visual Studio Installer, then reinstall Visual Studio 2022, clone the repo from DevOps, and open the project in Visual Studio 2022. Try to debug and get the error: “The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[16672] dotnet.exe' has exited with code 2147516566 (0x80008096).”

### Exceptions (if any)
None

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
Windows 10 Version: 10.0.19043 Build 19043 
System Type: x64-based PC
- Include the output of `dotnet --list-sdks` :
2.2.207 [C:\Program Files\dotnet\sdk]
6.0.301 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version` 
version: 0.3.330701

**Comment by RyanNewmanTruGreen** [comment]
Hi Brandon,

When doing this I receive this error:

***@***.***


The good news is I haven't pushed this to remote since before the error occurred, so this is certainly a local issue.
Thank You,
Ryan Newman
Application Developer II
***@***.***

**Comment by RyanNewmanTruGreen** [comment]
From the Git Bash menu:

$ git clean -xdf
Unlink of file 'TrueGreenSkill/.vs/TrueGreenSkill/FileContentIndex/8f931a06-1564-46de-8846-4ab19433d6c4.vsidx' failed. Should I try again? (y/n)

Thanks,
Ryan Newman
Application Developer II
***@***.***

**Comment by RyanNewmanTruGreen** [comment]
My apologies, I had the solution open. The git command worked in Git Bash, however, I still have the read.lock file.

Thank You,
Ryan Newman
Application Developer II
***@***.***



From: Newman, Ryan
Sent: Thursday, July 7, 2022 2:27 PM
To: dotnet/upgrade-assistant ***@***.***>; dotnet/upgrade-assistant ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [dotnet/upgrade-assistant] Corrupted/Disabled Project (Issue #1197)

From the Git Bash menu:

$ git clean -xdf
Unlink of file 'TrueGreenSkill/.vs/TrueGreenSkill/FileContentIndex/8f931a06-1564-46de-8846-4ab19433d6c4.vsidx' failed. Should I try again? (y/n)

Thanks,
Ryan Newman
Application Developer II
***@***.***

**Comment by brandonh-msft** [comment]
@RyanNewmanTruGreen I feel pretty confident this isn't an issue caused by UA. If you disagree and can provide more info for us to work with, please re-open!
