### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'C:\AnalysisReport.sarif' is denied.

### ISSUE THREAD

**Issue by pjm313** [dotnet/upgrade-assistant#1203]
How do I change the output path?

Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by brandonh-msft** [comment]
Seems like you're either running the analysis on a codebase that lives in `C:\`, or you're running UA _from_ `C:\` but giving it input of an sln elsewhere on your drive.
So you can probably solve by either
1. Running from an Administrator-mode command prompt
2. Running UA from the directory of the sln (e.g. `cd` to the directory first)

Can you try either of those and report back? Thanks!
