### ISSUE TITLE
Error while installing dotnet tool upgrade-assistant

### ISSUE THREAD

**Issue by pramodyadav1081** [dotnet/upgrade-assistant#1205]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows
I get the below error when trying to install upgrade-assistant : 
_**error NU1202: Package upgrade-assistant 0.3.330701 is not compatible with net5.0 (.NETCoreApp,Version=v5.0) / any. Package upgrade-assistant 0.3.330701 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install.**_

**Comment by YanerTavuz** [comment]
You should install .NET 6 SDK then.

**Comment by pramodyadav1081** [comment]
Thanks! that worked.
