### ISSUE TITLE
Ability to apply all steps automatically

### ISSUE THREAD

**Issue by jamers99** [dotnet/upgrade-assistant#1213]
## Summary

I want to apply all the steps automatically to prevent having to step through the entire process, requiring my constant attention.

## Motivation and goals

I find it incredibly tedious to have to go through each step and manually tell the assistant to go to the next step. Plus, it slowly lists out all the steps in between each action! I'm migrating many UWP projects to WinUI. Each step doesn't actually take that long to apply, but between each step, it has to recompute the entire list of steps, then ask you if you want to apply the next step. 

I should be able to, at any point, choose to apply all next steps.

## Risks / unknowns

I'm not sure if some of the upgrade paths require interaction, but if so, it's fine to stop for those. But for the love of my time, _please_ don't ask me to just go to the next step.

## Examples

Current process:
1. Start upgrade
2. _Assistant lists the steps_
3. Choose the next step
4. _Assistant applies step_
5. Confirm it was successful by pressing enter
6. _Assistant lists the steps_
7. Choose the next step
8. _Assistant applies step_
5. Confirm it was successful by pressing enter
6. _Assistant lists the steps_
7. Choose the next step
8. _**Rinse and repeat**_

What it should be:
1. Start upgrade
2. _Assistant lists the steps_
3. Choose to go through all steps automatically
4. _Assistant applies all steps (unless there is interaction required)_

**Comment by brandonh-msft** [comment]
@jamers99 is this different than the already-present `--non-interactive` flag in that you still want to see the steps it's going to do, and have to approve them, but just as one operation instead of individual ones? Or does `--non-interactive` effectively satisfy your ask?
