### ISSUE TITLE
Incorrect usage description when using from commandline

### ISSUE THREAD

**Issue by KevinvanHemert** [dotnet/upgrade-assistant#1255]
### **Describe the bug**

The usage information that is shown when using the tool from the commandline is different than whats written in the description of the repository README.md. 

In this specific case the order of "upgrade" and "[options]" are swapped in both of these places.

- In the commandline it says:

> _Usage:
>   upgrade-assistant **[options] upgrade** <project> [command]_

- While the README.md states:

> _Usage:
>   upgrade-assistant **upgrade [options]** <project>_

The only correct way to use the tool is the latter AKA how its described in the README.

### **To Reproduce**

- Open the commandline and type the following command:

> upgrade-assistant --non-interactive upgrade <project>

- It will return:

> _'--non-interactive' was not matched. Did you mean '--non-interactive'?
> Unrecognized command or argument '--non-interactive'_

- Followed by the usage description that contains:

> _Usage:
>   upgrade-assistant **[options] upgrade** <project> [command]_

### **Further technical details**
- Occurred while using Microsoft .NET Upgrade Assistant v0.4.336902+3a2177acaa53d719e5da4ccde275f84ff18f0611

**Comment by brandonh-msft** [comment]
This is an artifact of the console parser we've chosen for this project and, frankly, something I struggled with and tried to fix while implementing binary analysis. It's definitely been a source of confusion for many users, though, so 👍🏻

**Comment by brandonh-msft** [comment]
This ordering was fixed by a recent PR which also updated our parsing lib. Output now looks correct:

```
This tool's purpose is to automate some of the 'routine' upgrade tasks such as changing project file formats and updating APIs with near-equivalents in the selected target framework. Analyzers added to the project will highlight the remaining changes needed after the tool runs.

Usage:
  Microsoft.DotNet.UpgradeAssistant.Cli upgrade <project> [command] [options]

Arguments:
  <project>  The path to a project or solution file to be used.
```
