### ISSUE TITLE
upgrade-assistant : Unrecognized command or argument '--non-interactive-wait'

### ISSUE THREAD

**Issue by papyr** [dotnet/upgrade-assistant#1257]
Not interactive wait is not working

upgrade-assistant : Unrecognized command or argument '--non-interactive-wait'
At line:1 char:1
+ upgrade-assistant analyze

________________

Please improve the help as well

**Comment by vvkim20** [comment]
analyze doesn't support --non-interactive-wait only for upgrade support the option. 
Also the commend line has a bug show [options] upgrade. 
it should be
"upgrade --non-interative-wait"  instead of "--non-interative-wait upgrade"

**Comment by papyr** [comment]
I used the help from the video on the msdn channel
