### ISSUE TITLE
GUI + Please improve the help: non interactive, and options on upgradind between TFMs is confusing.

### ISSUE THREAD

**Issue by papyr** [dotnet/upgrade-assistant#1259]
Can you please improve the help docs to show the options on the upgrade/fully automatic with selected TFM NET 6.

Can you also provide a GUI to get this as an easier application.

**Comment by brandonh-msft** [comment]
@papyr Thanks for your suggestions

GUI is being tracked in #1225 

Would you be able to submit a PR for what you're needing/wanting/expecting in our docs related to non-interactive mode? Thanks!
