### ISSUE TITLE
Upgrading from Xamarin.Forms to MAUI does not work

### ISSUE THREAD

**Issue by holecekp** [dotnet/upgrade-assistant#1265]
- [X] Include the log file `upgrade-assistant.clef` that is produced in the working directory
 
[upgrade-assistant.zip](https://github.com/dotnet/upgrade-assistant/files/9409440/upgrade-assistant.zip)
[AnalysisReport.zip](https://github.com/dotnet/upgrade-assistant/files/9409441/AnalysisReport.zip)

### Describe the bug
The upgrade-assistant is not able to migrate Xamarin.Forms solution to MAUI. It fails even on a blank Xamarin.Forms solution created by the default Visual Studio template (without any user changes)! It modifies only a single file (.csproj for the Android project) and skips the others completely! For example, there are plenty of .cs files with `using Xamarin.Forms` are left unchanged by the upgrade-assistant. It is interesting that running the assistant with the "analyze" command lists the changes to be made, but running it with the "upgrade" command does not perform of these changes.

### To Reproduce
1. Select "Create a new project" in Visual Studio 2022.
2. Choose "Mobile App (Xamarin.Forms)" in the templates list.
3. I have named the solution as "MyApp", selected that it should use the "Flyout" template, and I have checked only Android in the platforms list. Confirm the dialog.
4. It is recommended to create a git repository so that you can track which files where modified by the upgrade-assistant later.
5. Run the upgrade assistant for the solution: `upgrade-assistant upgrade D:\dotNET\MyApp\MyApp.sln`
6. Go through the all steps. I have selected MyApp.Android as the entry point. Next, it asks for the project that should be converted. There is only one choice (MyApp.Android) because the upgrade assistant shows "[Completed]" next to the MyApp project (.NET Standard). So I have selected MyApp.Android again. I have skipped the backup and confirmed all the other steps. The upgrade assistant states that the upgrade has been completed.
7. Now look at Git which files has been changed. Only MyApp.Android.csproj has been modified!!! No other modification has been made. Namely, there are plenty of `using Xamarin.Forms` in the shared .NET Standard (MyApp) project. It seems that this project has been skipped by the assistant completely.
8. I have tried to run the assistant again just for this shared project: 
`upgrade-assistant upgrade D:\dotNET\MyApp\MyApp\MyApp\MyApp.csproj` but it refuses to do any changes - the assistant goes directly to the "Finalize upgrade step", exits and no changes are made. The weird thing is that if I run `upgrade-assistant analyze D:\dotNET\MyApp\MyApp\MyApp\MyApp.csproj`, it proposes a bunch of changes such as removing Xamarin.Forms, changing usings and others! So "analyze" command knows about the changes that should be made, but the "upgrade" command does not.
9. I have tried to run the upgrade-assistant for the whole solution again (step 5) in hope that it recognizes the shared project and converts it, but it goes again directly to the "Finalize upgrade" step.

### Further technical details
- Windows 10 (21H2), 64bit

- Include the output of `dotnet --list-sdks`:
```
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.422 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
6.0.303 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]
```

- Include the output of `upgrade-assistant --version`
```0.4.336902+3a2177acaa53d719e5da4ccde275f84ff18f0611```

**Comment by brandonh-msft** [comment]
@dotnet/dotnet-upgrade-assistant-maui

**Comment by deviprasad987** [comment]
@holecekp any update the issue

**Comment by holecekp** [comment]
I am also wondering if there are any updates on what causes this issue. The problem still persists.

**Comment by Tak1wa** [comment]
Hi, @holecekp 

I also confirmed the same phenomenon with the latest stable version.
Common projects are skipped, Android projects are converted to just net6.0 instead of net6.0-andoid and UseMaui is not enabled.

I was able to try converting to .NET MAUI by installing the latest development version as follows. It was stated that UWP and Xamarin.Forms upgrades are in the preview stage, so it may not be available in the stable version yet.

```
C:\>dotnet tool install -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
次のコマンドを使用してツールを呼び出せます。upgrade-assistant
ツール 'upgrade-assistant' (バージョン '0.4.345202') が正常にインストールされました。
```

**Comment by Sweekriti91** [comment]
Hi! Thank you all for letting us know about this issue. We will take a look at this and get back you once we have a fix or we need more information. 

Thanks for your patience!

**Comment by holecekp** [comment]
@Tak1wa Thank you, using the latest development helped a lot! The development version recognizes the project types better and converts much more files. However, it does not do the conversion correctly. A blank Xamarin.Forms project created by VS is corrupted after the conversion to MAUI and cannot be compiled any more. The following error messages appear when I try to compile it:

_Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'MauiProgram.cs'_

If I have time, I will create a new issue for it later.

I have been seeing multiple videos with upgrade-assistant for conversion Xamarin.Forms to MAUI for months. For example "_.NET MAUI Community Standup - Get to MAUI with the .NET Upgrade Assistant feat. Sweeky!_" has been uploaded more than a year ago (but there were also other more recent ones). This confused me. I thought that the assistant is surely 
stable by now, used and tested by many people on real-world Xamarin.Forms projects. I did not know that it is not in the stable version yet and it works (partially) in the preview version only. Please consider stating it clearly on the github main page next to the text: "_Currently, the tool supports the following project types: ... Xamarin.Forms to .NET MAUI_". I think it would be helpful for other developers so that they could better distinguish which projects types can be converted by the stable version of the assistant and which types require downloading the preview/development version.

**Comment by Sweekriti91** [comment]
Hi @holecekp , the upgrade-assistant at the moment does not provide 100% migrated solutions. There are more steps that need to be taken after the upgrade-assistant has run. It gets you to 60-70% of the way towards migration and you would still have some manual follow up steps to be taken to complete the migration process and those steps can be found [here](https://github.com/dotnet/upgrade-assistant/blob/main/docs/maui_support.md#migration-steps). And as I said in my previous message, we are still working on the tool and making the experience better. 

We appreciate your patience.
