### ISSUE TITLE
Further Improvements/Features for WCF Updater Extension

### ISSUE THREAD

**Issue by SimonaLiao** [dotnet/upgrade-assistant#1270]
Here are some feedbacks from code review that I won't be able to get to yet in the first PR but will implement in the next PR.

`Constants.cs`: Use `await app.StartAsync();` and update the method signature to Async instead of `app.StartAsync().GetAwaiter().GetResult();`

`UpdateRunner.cs`: Create a type `WcfUpgradeContext` to store the contexts from configuration files.

`WCFUpdateStep.cs`: Create a type for `_path` variable with fields of expected paths.

`UpdaterFactory.cs`:  Make this class available in dependency injeciton and other classes could request it in their constructors.

**Comment by brandonh-msft** [comment]
Do you want to include Docs in this work? Or make a new issue for those?

**Comment by SimonaLiao** [comment]
> Do you want to include Docs in this work? Or make a new issue for those?

Yes I will write a documentation after finishing those improvements! The document will be submitted via a different PR.
