### ISSUE TITLE
Unexpexcted error using upgrade assistant

### ISSUE THREAD

**Issue by GregWalcottAdvantest** [dotnet/upgrade-assistant#1313]
Trying to upgrade a .Net Framework .csproj file to SDK-Style using the upgrade assistant 
https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Running from the VS 2022 Developer Prompt, I get the following error when running "upgrade-assistant analyze myproject.csproj"

[10:26:39 INF] Loaded 5 extensions
[10:26:41 INF] Using MSBuild from C:\Program Files\dotnet\sdk\6.0.400\
[10:26:41 INF] Using Visual Studio install from C:\Program Files\Microsoft Visual Studio\2022\Enterprise [v17]
[10:26:45 ERR] Unexpected error
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.DotNet.UpgradeAssistant.M
SBuild.MSBuildWorkspaceUpgradeContext.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Mic
rosoft.Extensions.Options.IOptions`1[Microsoft.DotNet.UpgradeAssistant.MSBuild.WorkspaceOptions], Microsoft.DotNet.Upgra
deAssistant.IPackageRestorer, Microsoft.DotNet.UpgradeAssistant.MSBuild.Factories, Microsoft.DotNet.UpgradeAssistant.ITa
rgetFrameworkMonikerComparer, System.Collections.Generic.IEnumerable`1[Microsoft.DotNet.UpgradeAssistant.IComponentIdent
ifier], Microsoft.Extensions.Logging.ILogger`1[Microsoft.DotNet.UpgradeAssistant.MSBuild.MSBuildWorkspaceUpgradeContext]
)' on type 'MSBuildWorkspaceUpgradeContext'.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6
.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6
.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Comment by brandonh-msft** [comment]
This looks like #1151 which was fixed by #1162 - what version of UA are you using?

**Comment by GregWalcottAdvantest** [comment]
v0.3.261602

**Comment by GregWalcottAdvantest** [comment]
Just upgraded to v0.4.346202 and now it's not blowing up, thanks.
