### ISSUE TITLE
"ResolvePackageFileConflicts" task could not be loaded from the assembly

### ISSUE THREAD

**Issue by RamanSggs** [dotnet/upgrade-assistant#1317]
Getting below error while analyzing upgrade.

 Msbuild failed when processing the file 'C:\Projects\xyz.csproj' with message: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets: (30, 5): The "ResolvePackageFileConflicts" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net6.0\Microsoft.NET.Build.Extensions.Tasks.dll. Could not load file or assembly 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\tools\net6.0\Microsoft.NET.Build.Extensions.Tasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by brandonh-msft** [comment]
can you paste the output of `dotnet --list-sdks`? Thanks

**Comment by RamanSggs** [comment]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.511 [C:\Program Files\dotnet\sdk]
2.2.100 [C:\Program Files\dotnet\sdk]
3.1.405 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
6.0.401 [C:\Program Files\dotnet\sdk]

**Comment by abpiskunov** [comment]
Fixed in new versions of UA CLI.
