### ISSUE TITLE
No packages exist with this id in source(s)

### ISSUE THREAD

**Issue by MarvusMedia** [dotnet/upgrade-assistant#1319]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Hi. I entered this command as instructed:

dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources upgrade-assistant

but I got this error: (I replaced my username)

C:\Users\<username>\AppData\Local\Temp\sni0d0cn.vxh\restore.csproj : warning NU1801: The local source 'C:\Program Files\
Microsoft Visual Studio\2022\Community\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\<username>\AppData\Local\Temp\sni0d0cn.vxh\restore.csproj : warning NU1801: The local source 'C:\Program Files\
Microsoft Visual Studio\2022\Community\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\<username>\AppData\Local\Temp\sni0d0cn.vxh\restore.csproj : warning NU1801: The local source 'C:\Program Files\
Microsoft Visual Studio\2022\Community\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\<username>\AppData\Local\Temp\sni0d0cn.vxh\restore.csproj : error NU1101: Unable to find package upgrade-assist
ant. No packages exist with this id in source(s): C:\Program Files\Microsoft Visual Studio\2022\Community\'https:\api.n
uget.org\v3\index.json', Microsoft Visual Studio Offline Packages
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install.

**Comment by brandonh-msft** [comment]
See my comments on #1293 where we are seeing a similar issue

**Comment by brandonh-msft** [comment]
thanks for that update, can you comment on #1293 so we can use that as a link to the fix? thanks

**Comment by MarvusMedia** [comment]
Done.
