### ISSUE TITLE
Path to sln

### ISSUE THREAD

**Issue by ScottinTexasUS** [dotnet/upgrade-assistant#1329]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The path to the solution has spaces in it. ...OneDrive - The Dow Chemical Company\... and the command does not recognize '-' or 'The' or 'Dow'

**Comment by brandonh-msft** [comment]
You need to put your path in `" "` for spaces to be recognized as part of it
