### ISSUE TITLE
Propagate (or handle) if the users has the MinimumOSVersion set inside the info.plist file

### ISSUE THREAD

**Issue by PureWeen** [dotnet/upgrade-assistant#1331]
## Summary

Currently the `MinimumOSVersion` inside the `info.plist` isn't really a supported path (even apple indicates that you shouldn't use it). With net6.0-ios the equivalent to this value is `SupportedOSPlatformVersion` which you can set in the CSPROJ file and/or via the property editor. 

If there is a project where the `info.plist` and the `SupportedOSPlatformVersion` don't match the user will get compile errors. 

Possible actions
- read the `info.plist` value and propagate that to the `SupportedOSPlatformVersion` if that value is not found then just set `SupportedOSPlatformVersion` to whatever we have in the MAUI templates (right now we have 11.0 for iOS and 13.1 for catalyst)
- just remove this entry from the `info.plist` file if they have it and just set `SupportedOSPlatformVersion` to what we have in the templates.

**Comment by mgoertz-msft** [comment]
I believe this was done.
