### ISSUE TITLE
MSBuild not found - Upgrading MAUI project to .NET 7.0

### ISSUE THREAD

**Issue by fabrb** [dotnet/upgrade-assistant#1353]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant#
Operating System: windows

Right after installing the new update released by the MS team, I decided to bump my personal MAUI project up, from .NET 6.0 to .NET 7.0 using the .NET Upgrade Assistant.

I ran into problems when I ran the upgrade-assistant analyze command:
```
PS C:\WINDOWS\system32> upgrade-assistant analyze C:\Users\Fabio\source\repos\InfoDisplayer\InfoDisplayer.sln
-----------------------------------------------------------------------------------------------------------------
Microsoft .NET Upgrade Assistant v0.4.346202+66a923ad8212e008d71c1c232bed728c4c7982c1

We are interested in your feedback! Please use the following link to open a survey: https://aka.ms/DotNetUASurvey
-----------------------------------------------------------------------------------------------------------------

[18:30:55 INF] Loaded 9 extensions
[18:30:57 ERR] No supported MSBuild found. Ensure `dotnet --list-sdks` show an install that is 64-bit
[18:30:57 ERR] MSBuild not found
```

Running dotnet --list-sdks shows me this:
```
PS C:\WINDOWS\system32> dotnet --list-sdks
7.0.100 [C:\Program Files\dotnet\sdk]
```

Just to be sure, I downloaded the .NET 7.0 64-bits SDK from [this step](https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-sdk), ran these commands again, but no good.

Is there something I am missing out, or that I could provide more info about?

**Comment by LeDahu22** [comment]
Run the following command to update the upgrade assistant : dotnet tool update -g upgrade-assistant

**Comment by orbtz** [comment]
After running the command, I was able to continue the process.

I will continue the process, checking if the dependencies are in one piece. Thank you.
