### ISSUE TITLE
Upgrading MAUI netstandard2.1 library doesn't work

### ISSUE THREAD

**Issue by filipnavara** [dotnet/upgrade-assistant#1359]
### Describe the bug

The check in the code is too restrictive:
https://github.com/dotnet/upgrade-assistant/blob/1eaed1d7ed79d5c3af34ba72dbc7897aa8f3942a/src/extensions/maui/Microsoft.DotNet.UpgradeAssistant.Extensions.Maui/MauiComponentIdentifier.cs#L41

It only allows `netstandard2.0`, we use `netstandard2.1`.

### Further technical details

> upgrade-assistant --version
0.4.355802+b2aeae2c0e41fbfed35df6ab2e88b82a0c11be2b

**Comment by filipnavara** [comment]
Workaround: Change the target framework to `netstandard2.0` before running the upgrade assistant. The TFM gets upgraded anyway.

**Comment by mgoertz-msft** [comment]
Should work in current versions.
