### ISSUE TITLE
Upgrade assistant stuck in Xamarin Forms upgrade (UA0014)

### ISSUE THREAD

**Issue by Bloodyairtimer** [dotnet/upgrade-assistant#1374]
### Describe the bug
The upgrade assistant keeps trying to fix the UA0014 code fix for the same file. If the Fix failed it won't continue to the next issue, but keeps retrying it.

It looks like it isn't able to handle a fully qualified base class in for example a custom renderer or a PlatformEffect.

### To Reproduce
Add a custom renderer or platformeffect to a platform project. Fully qualify the base class like this:

```
public class ListViewRenderer : Xamarin.Forms.Platform.Android.ListViewRenderer
{
}
```

### Further technical details
Upgrade-assistant version: 0.4.0-dev

In the class/method UsingXamarinFormsAnalyzerCodeFixProvider.RegisterCodeFixesAsync the node.RawKind is of type SyntaxKind.ClassDeclaration, which isn't handled.

Looks like it should be doing similar to what the assistant is doing to the MainActivity class. And add the using "Microsoft.Maui.Controls.Compatibility.Platform".

**Comment by mgoertz-msft** [comment]
Please try the newest version.
