### ISSUE TITLE
Reference to .NET Upgrade Assistant analyzer package (Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers, version 0.4.355802) needs to be added

### ISSUE THREAD

**Issue by galb1191** [dotnet/upgrade-assistant#1397]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mgoertz-msft** [comment]
No longer applicable.
