### ISSUE TITLE
Failure looking for non existant Microsoft.NET.Build.Extensions.Tasks.dll

### ISSUE THREAD

**Issue by clovett** [dotnet/upgrade-assistant#1401]
- [x] Include the log file `upgrade-assistant.clef` that is produced in the working directory

[upgrade-assistant.zip](https://github.com/dotnet/upgrade-assistant/files/10367542/upgrade-assistant.zip)

### Describe the bug

workspace.OpenSolutionAsync is failing saying it could not load an assembly (because it doesn't exist):

> Could not load file or assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net7.0\Microsoft.NET.Build.Extensions.Tasks.dll. 

In my VS installation the `Microsoft.NET.Build.Extensions\tools` folder has no "net7.0" folder...?

But on my machine this assembly does live in:

> C:\Program Files\dotnet\sdk\7.0.101\Microsoft\Microsoft.NET.Build.Extensions\tools\net7.0\Microsoft.NET.Build.Extensions.Tasks.dll

So perhaps there's a problem with assembly resolution paths somewhere? The `var workspace = MSBuildWorkspace.Create(GlobalProperties)` line has this in the GlobalProperties:

![image](https://user-images.githubusercontent.com/3336415/211177217-3f56d999-4414-48ad-977b-86fd51158c83.png)

It seems to get further if I add `C:\Program Files\dotnet\sdk\7.0.101\Microsoft\Microsoft.NET.Build.Extensions\tools\net7.0\` to the MsBuildExtensionsPath.

### To Reproduce

git clone https://github.com/MoneyTools/MyMoney.Net.git
git checkout net7
git checkout 38dbc04123ac97ef7768ab94ee82868e084a72eb
cd MyMoney.Net\Source\WPF
upgrade-assistant analyze .\MyMoney.sln --verbose

and this project also fails to upgrade:
https://github.com/lovettchris/GraphViewer

### Exceptions (if any)

17:47:52 DBG] [Failure] Problem loading file in MSBuild workspace Msbuild failed when processing the file 'D:\git\MoneyTools\MyMoney.Net\Source\WPF\MyMoney\MyMoney.csproj' with message: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets: (30, 5): The "ResolvePackageFileConflicts" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net7.0\Microsoft.NET.Build.Extensions.Tasks.dll. Could not load file or assembly 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\tools\net7.0\Microsoft.NET.Build.Extensions.Tasks.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

### Further technical details

- Windows version and bitness info (32-bit or 64-bit) Windows 11, 21H2, 64-bit
- Include the output of `dotnet --list-sdks`
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.404 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]

- Include the output of `upgrade-assistant --version`
0.4.355802+b2aeae2c0e41fbfed35df6ab2e88b82a0c11be2b

**Comment by abpiskunov** [comment]
Fixed in new versions of UA CLI.
