### ISSUE TITLE
Can't select a command

### ISSUE THREAD

**Issue by saitoreeper** [dotnet/upgrade-assistant#1416]
### Describe the bug
It doesn't allow me to select a command, ie if I type anything nothing happens
Upgrade Steps

1. [Next step] Select an entrypoint
2. Select project to upgrade

Choose a command:
   1. Apply next step (Select an entrypoint)
   2. Skip next step (Select an entrypoint)
   3. See more step details
   4. Configure logging
   5. Exit

**Comment by Sean-URS** [comment]
**Same Bug**
"FREEZES" at command selection. (pipeline/command continues to run, red square visible in Package Manager Console)

using upgrade-assistant version (0.4.410601+6304b1d0784e32e20ef0299db22bc9e3f6a9b3f)

Tried removing tool then re-installing then updating it.
Tried each project within the solution. (Test solution is - https://github.com/SteveSandersonMS/CarChecker.git)

![Select](https://user-images.githubusercontent.com/113436819/219702799-54228456-6cfb-49fc-b518-8715711c6053.png)

**Comment by rr222cy** [comment]
@saitoreeper @Sean-URS I just ran into the same problem running this tool on a .NET 5 project, upgrading it to .NET 7. The workaround that worked for me was to run this in Windows PowerShell (or equivalent in other OS).

**Comment by Sean-URS** [comment]
Thank you @rr222cy, this solved the issue.

**Comment by mgoertz-msft** [comment]
No longer applicable.
