### ISSUE TITLE
Mac - Android and iOS files were not updated

### ISSUE THREAD

**Issue by davidortinau** [dotnet/upgrade-assistant#1461]
Running from mac with a preview build, I got new files added, but existing files were not updated (usings, class types).

* MainActivity
* AppDelegate

They still referenced Xamarin.Forms too.

Project: https://learn.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/deeplinking/

**Comment by mgoertz-msft** [comment]
@jstedfast It should do the same as the CLI on Windows

**Comment by jstedfast** [comment]
Using the latest (including @DianaSoltani 's latest patch), running the upgrade-assistant with the following arguments produces identical results on Windows and macOS: `upgrade DeepLinking.sln --non-interactive --entry-point \*`

I've attached the results of `git diff` for both platforms:

[deeplinking.windows.patch](https://github.com/dotnet/upgrade-assistant/files/11151565/deeplinking.windows.patch)
[deeplinking.macos.patch](https://github.com/dotnet/upgrade-assistant/files/11151567/deeplinking.macos.patch)

**Comment by jstedfast** [comment]
It should be noted that without Diana's latest patch, the Android project gets assigned a TFM of net7.0-ios which would likely cause Roslyn resolution failures which I expect would cause problems in the "upgrade code" step.

This was likely the issue David ran into.

**Comment by mgoertz-msft** [comment]
No longer applicable.
