### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by tkmetdev** [dotnet/upgrade-assistant#1475]
### Describe the bug
VirtualBox VM Windows 2016 Core Server with .NET Framework 4.7.1 runtime and .NET 6 SDK installed, Visual Studio 2019 and now Visual Studio 2022 version 17.0.2 - VM has about 22GB of memory and 4 CPU's works fine with both version of VS.  Downloaded the VSIX Installer and ran it goes through the motions of looking like its installing the .NET Upgrade Assistant extension and then it fails with message:

`This extension is not installable on any currently installed products.`

### To Reproduce
VirtualBox VM (latest version) Windows 2016 Core Server OS AD, IIS, SQL 2017 Core Server, 22GB ram, 4 cpu's assigned through VirtualBox manager, 2 x drives 150GB C: partition and 500GB D: partition.
Visual Studio Professional 2019 installed
.NET Framework 4.7.1 and 4.8 developer kits installed (and runtimes)
.NET 6 SDK
Visual Studio Professional 2022 version 17.0.2 installed.

Run the downloaded VSIX Installer (latest obtained from VSMarketplace) and the error will pop-up.

### Exceptions (if any)
`
13/04/2023 14:10:05 - Microsoft VSIX Installer
13/04/2023 14:10:05 - -------------------------------------------
13/04/2023 14:10:05 - vsixinstaller.exe version:
13/04/2023 14:10:05 - 17.0.5226-preview5
13/04/2023 14:10:05 - -------------------------------------------
13/04/2023 14:10:05 - Command line parameters:
13/04/2023 14:10:05 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,d:\downloads\Microsoft.NET.UpgradeAssistant.vsix
13/04/2023 14:10:05 - -------------------------------------------
13/04/2023 14:10:05 - Microsoft VSIX Installer
13/04/2023 14:10:05 - -------------------------------------------
13/04/2023 14:10:05 - Initializing Install...
13/04/2023 14:10:06 - Extension Details...
13/04/2023 14:10:06 - 	Identifier         : Microsoft.NET.UpgradeAssistant
13/04/2023 14:10:06 - 	Name               : .NET Upgrade Assistant
13/04/2023 14:10:06 - 	Author             : Microsoft
13/04/2023 14:10:06 - 	Version            : 0.1.201.39690
13/04/2023 14:10:06 - 	Description        : .NET Upgrade Assistant is a tool that is designed to assist users with modernizing .NET applications.
13/04/2023 14:10:06 - 	Locale             : en-US
13/04/2023 14:10:06 - 	MoreInfoURL        : 
13/04/2023 14:10:06 - 	InstalledByMSI     : False
13/04/2023 14:10:06 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
13/04/2023 14:10:06 - 
13/04/2023 14:10:38 - 	SignatureState     : InvalidTimestamp
13/04/2023 14:10:38 - 	SignedBy           : Microsoft Corporation
13/04/2023 14:10:38 - 	Certificate Info   : 
13/04/2023 14:10:38 - 		-------------------------------------------------------
13/04/2023 14:10:38 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
13/04/2023 14:10:38 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
13/04/2023 14:10:38 - 		[Serial Number] : 33000004BB954232676BC54B430000000004BB
13/04/2023 14:10:38 - 		[Not Before]    : 07/06/2022 18:44:22
13/04/2023 14:10:38 - 		[Not After]     : 01/06/2023 18:44:22
13/04/2023 14:10:38 - 		[Thumbprint]    : 9A1765B13411676B4107A5F9F365F6178B1BF384
13/04/2023 14:10:38 - 
13/04/2023 14:10:38 - 	Supported Products : 
13/04/2023 14:10:38 - 		Microsoft.VisualStudio.Community
13/04/2023 14:10:38 - 			Version : [17.1,18.0)
13/04/2023 14:10:38 - 			ProductArchitecture : amd64
13/04/2023 14:10:38 - 		Microsoft.VisualStudio.Community
13/04/2023 14:10:38 - 			Version : [17.1,18.0)
13/04/2023 14:10:38 - 			ProductArchitecture : x86
13/04/2023 14:10:38 - 
13/04/2023 14:10:38 - 	References         : 
13/04/2023 14:10:38 - 	Prerequisites      : 
13/04/2023 14:10:38 - 		-------------------------------------------------------
13/04/2023 14:10:38 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
13/04/2023 14:10:38 - 		Name         : Visual Studio core editor
13/04/2023 14:10:38 - 		Version      : [17.0,18.0)
13/04/2023 14:10:38 - 
13/04/2023 14:10:38 - Signature Details...
13/04/2023 14:10:38 - 	Extension is signed with an invalid timestamp.
13/04/2023 14:10:38 - 
13/04/2023 14:10:38 - Searching for applicable products...
13/04/2023 14:10:38 - Found installed product - Global Location
13/04/2023 14:10:38 - Found installed product - Visual Studio Professional 2022
13/04/2023 14:10:38 - Found installed product - Visual Studio Professional 2019
13/04/2023 14:10:39 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`
### Further technical details
- VirtualBox VM Windows 2016 Core Server
- 3.1.101 [C:\Program Files\dotnet\sdk]
- 5.0.412 [C:\Program Files\dotnet\sdk]
- 6.0.100 [C:\Program Files\dotnet\sdk]
- 6.0.111 [C:\Program Files\dotnet\sdk]`
- Include the output of `upgrade-assistant --version`  *Doesn't exist*

**Comment by abpiskunov** [comment]
Yes, this extension supports only VS 2022 17.1 and above as it is described on the marketplace page.
