### ISSUE TITLE
Markup package upgrade can also be included while processing Xamarin.Forms to .NET MAUI projects

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/upgrade-assistant#1487]
## Summary

For those working without XAML, rely on the Markup package which is officially supported too and there is a transition path from `Xamarin.CommunityToolkit.Markup` to `CommunityToolkit.Maui.Markup` NuGet package.

But the Markup package upgrade is not included while processing Xamarin.Forms to .NET MAUI projects.

## Motivation and goals

Ease of upgrade, reducing manual steps to a greater extent.

## In scope

Since the migration from the `Xamarin.CommunityToolkit` to the `CommunityToolkit.Maui` package is already there in scope, it is another package processing step that is to be included.

## Out of scope

NA

## Risks / unknowns

None

## Examples

Users would attempt to upgrade their existing Xamarin.Forms projects to .NET MAUI.

**Comment by mgoertz-msft** [comment]
This was done.
