### ISSUE TITLE
Missing change log

### ISSUE THREAD

**Issue by debuglevel** [dotnet/upgrade-assistant#1499]
A month ago, [0.5.30](https://www.nuget.org/packages/upgrade-assistant/0.5.30) was released. It introduces some important changes (e.g. removes `analyze`) but there are no entries in the change log since 0.4.355802

**Comment by jstedfast** [comment]
The project moved to another repo, this repo is dead.

**Comment by debuglevel** [comment]
Then please archive this repository and point to the new one.

**Comment by jstedfast** [comment]
The new repo is not public and I do not have the ability to archive this repo.
