### ISSUE TITLE
[MAUI] [MacOS] System.ArgumentException: MauiApp/Template/MauiProgram.cs ('Failed to load resource named MauiApp/Template/MauiProgram.cs')

### ISSUE THREAD

**Issue by janusw** [dotnet/upgrade-assistant#1505]
### Describe the bug

I'm trying to convert a netstandard2.0 library (that is part of a Xamarin.Forms solution) to net7.0 / MAUI on MacOS 13.4 using upgrade-assistant v0.5.30.21767:

```
upgrade-assistant upgrade XYZ.csproj --operation Inplace --targetFramework net7.0
```

The migration finishes with:
```
Complete: 78 succeeded, 1 failed, 120 skipped.
```

The one failure that occurs seems to be due to an ArgumentException:

```
project XYZ.csproj...
	Microsoft.UpgradeAssistant.Msbuild.Transformers.InplaceDuplicatePackageReferenceTransformer
	info: Done
	Microsoft.UpgradeAssistant.Maui.Transformers.MauiTargetFrameworkProjectTransformer
	info: Done
	Microsoft.UpgradeAssistant.Maui.Transformers.MauiProjectTransformer
	info: Removing property 'TargetFramework' from project 'XYZ (XYZ.csproj)'.
	info: Setting property 'TargetFrameworks' to 'net7.0-android;net7.0-ios' for project 'XYZ (XYZ.csproj)'.
	info: Setting property 'UseMaui' to 'True' for project 'XYZ (XYZ.csproj)'.
	info: Done
	Microsoft.UpgradeAssistant.Transformers.DefaultProjectFilesRemoveTransformer
	info: Done
	Microsoft.UpgradeAssistant.Maui.Transformers.MauiLibraryPropertiesTransformer
	info: Removing property 'DebugType,DebugSymbols,ProduceReferenceAssembly' from project 'XYZ (XYZ.csproj)'.
	info: Setting property 'OutputType' to 'Library' for project 'XYZ (XYZ.csproj)'.
	info: Setting property 'ImplicitUsings' to 'enable' for project 'XYZ (XYZ.csproj)'.
	info: Setting property 'SingleProject' to 'true' for project 'XYZ (XYZ.csproj)'.
	info: Done
	Microsoft.UpgradeAssistant.Maui.Transformers.MauiProjectTemplateItemTransformer
	error: System.ArgumentException: MauiApp/Template/MauiProgram.cs (Parameter 'Failed to load resource named MauiApp/Template/MauiProgram.cs from assembly Microsoft.UpgradeAssistant.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
  ---> System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at Microsoft.UpgradeAssistant.Helpers.ResourceUtilities.GetEmbeddedResourceFileInternal(String resourceName, Assembly assembly)
   --- End of inner exception stack trace ---
   at Microsoft.UpgradeAssistant.Helpers.ResourceUtilities.GetEmbeddedResourceFileInternal(String resourceName, Assembly assembly)
   at Microsoft.UpgradeAssistant.Helpers.ResourceUtilities.GetEmbeddedResourceFile(String resourceName, Assembly containingAssembly)
   at Microsoft.UpgradeAssistant.Templates.ProjectTemplate.ApplyFiles(String projectFolder, IReadOnlyDictionary`2 parameters, Boolean includeProject, ISet`1 includeFiles, ILogger logger)
   at Microsoft.UpgradeAssistant.Templates.ProjectTemplate.ApplyFiles(OperationContext context, Boolean includeProject, IEnumerable`1 includeFiles, ILogger logger)
   at Microsoft.UpgradeAssistant.Maui.Transformers.MauiProjectTemplateItemTransformer.RunAsync(OperationContext context, SliceNode node, CancellationToken cancellationToken)
   at Microsoft.UpgradeAssistant.Operations.Operation.RunTransformerAsync(OperationContext context, SliceNode node, Lazy`2 transformer, TelemetryEvent telemetryEvent, OperationLogger transformerLogger, CancellationToken cancellationToken)
   at Microsoft.UpgradeAssistant.Operations.Operation.RunNodeAsync(SliceNode node, CancellationToken cancellationToken)
	info: Done
	Microsoft.UpgradeAssistant.Transformers.TargetFrameworkTransformer
	info: Done
Failed
```

Notes:
* The project is a library, not an executable, so it should not have any `MauiProgram.cs`. Indeed no such file is generated, but apparently the upgrade assistant expects it somewhere?
* The same migration works without failure on Windows (same upgrade-assistant version).

### To Reproduce

I cannot provide a full reproducer right now (my project is not open source), but I can try to cut out a minimal example if necessary.

The crucial part of the csproj is this (before and after conversion):

```
 ﻿<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
-    <TargetFramework>netstandard2.0</TargetFramework>
     <ReleaseVersion>1.0.0</ReleaseVersion>
     <Configurations>Debug;Release</Configurations>
     <BuildWithMSBuildOnMono>true</BuildWithMSBuildOnMono>
+    <TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
+    <UseMaui>True</UseMaui>
+    <OutputType>Library</OutputType>
+    <ImplicitUsings>enable</ImplicitUsings>
+    <SingleProject>true</SingleProject>
   </PropertyGroup>
```

### Exceptions (if any)

```
System.ArgumentException: MauiApp/Template/MauiProgram.cs (Parameter 'Failed to load resource named MauiApp/Template/MauiProgram.cs from assembly Microsoft.UpgradeAssistant.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
  ---> System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
```

(for details see above)

### Further technical details
- Windows version and bitness info (32-bit or 64-bit): none (MacOS 13.4.1)
- Include the output of `dotnet --list-sdks`:
```
6.0.403 [/usr/local/share/dotnet/sdk]
6.0.404 [/usr/local/share/dotnet/sdk]
6.0.405 [/usr/local/share/dotnet/sdk]
6.0.406 [/usr/local/share/dotnet/sdk]
6.0.407 [/usr/local/share/dotnet/sdk]
6.0.408 [/usr/local/share/dotnet/sdk]
6.0.410 [/usr/local/share/dotnet/sdk]
6.0.412 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
7.0.101 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
7.0.103 [/usr/local/share/dotnet/sdk]
7.0.200 [/usr/local/share/dotnet/sdk]
7.0.201 [/usr/local/share/dotnet/sdk]
7.0.202 [/usr/local/share/dotnet/sdk]
7.0.203 [/usr/local/share/dotnet/sdk]
7.0.302 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
```
- Include the output of `upgrade-assistant --version`: `0.5.30.21767`

**Comment by janusw** [comment]
@jstedfast

**Comment by janusw** [comment]
> I'm guessing, based on the original TargetFramework, that this doesn't have any iOS or Android API usage

Right. The library is completely platform-independent. No iOS- or Android-specific code anywherer.

> and so shouldn't have been converted to a "MAUI" project - it should probably have stayed as a netstandard2.0 project, I imagine.

I guess ideally it should simply be converted from netstandard2.0 to net7.0 (instead of net7.0-android and net7.0-ios).

Note that the library does contain some Xamarin.Forms-based UI elements, so the converted projects needs `<UseMaui>True</UseMaui>`, I guess (that part is correct).


> Odd that this happened on Mac but not on Windows.

On Windows the conversion to the net7.0-android and net7.0-ios frameworks (with `UseMaui`) happens exactly the same way as on MacOS, just the exception does not occur.

**Comment by jstedfast** [comment]
> Note that the library does contain some Xamarin.Forms-based UI elements, so the converted projects needs <UseMaui>True</UseMaui>, I guess (that part is correct).

Ah, okay, that explains the conversion, then. It might also explain why it targeted net7.0-ios and net7.0-android.

Like you said, though, I don't think it should be adding a MauiProgram.cs file since it's a library and not the main program itself.

**Comment by janusw** [comment]
> Like you said, though, I don't think it should be adding a MauiProgram.cs file since it's a library and not the main program itself.

Exactly. On Windows I do see a MauiProgram.cs being generated (which seems to be the actual bug here). On MacOS I don't see it. I assume there is an attempt to generate it, which fails with the exception shown above.

If you can prevent the upgrade assistant from generating a MauiProgram.cs for the case of `<OutputType>Library</OutputType>`, then I'd hope that this will also fix this issue.

**Comment by jstedfast** [comment]
Looks like the MauiApp/Template/MauiProgram.cs error has been fixed (June 8th) but it probably hasn't made it into a release yet.

Essentially embedded resource names when built on Windows were using "MauiApp\\Template\\MauiProgram.cs" and so on mac, it was expecting "MauiApp/Template/MauiProgram.cs" and wasn't finding it.

**Comment by jstedfast** [comment]
As far as the Library projects getting the MauiProgram.cs... looks like the the main MAUI app program is a Library project, so it's not as simple as only adding it if it is a Exe project.

I'll create a bug for this internally and bring it up in tomorrow's meeting to see if anyone knows why MAUI projects are Library projects and if there's a way we could fix this issue.

**Comment by janusw** [comment]
Alright, I updated to version 0.5.261.51392 and can confirm that the exception is gone. Thanks a lot for fixing, @jstedfast!

[Note that the conversion result for the same project is now: `Complete: 106 succeeded, 0 failed, 94 skipped.` So, no more failures, but still 94 skipped. I assume that means that the conversion may still be incomplete? Need to check ...]

**Comment by jstedfast** [comment]
I think that just means 94 steps were skipped because they weren't relevant to your project.
