### ISSUE TITLE
[MAUI] [Android] remove `<uses-sdk/>` element in favor of MSBuild properties

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/upgrade-assistant#1508]
## Summary

See the doc change here: https://github.com/dotnet/docs-maui/pull/1624

Xamarin.Android uses the `<uses-sdk/>` element in `AndroidManifest.xml` files, while we should use MSBuild properties instead in .NET 6+.

It would be ideal if UA could:

* Remove the `<uses-sdk/>` element
* Set `SupportedOSPlatformVersion` in the `.csproj` to match `android:minSdkVersion` with a minimum of 21.

We could leave `TargetFramework` alone and rely on `net7.0-android` to supply the appropriate Android target platform version.

## Motivation and goals

Customers can get build warnings if `<uses-sdk/>` doesn't match the `TargetFramework`, and it isn't clear they should just remove it. We are working on improving these warning messages, but that is a separate issue.

**Comment by mgoertz-msft** [comment]
I believe this has been completed. @DianaSoltani?

**Comment by DianaSoltani** [comment]
Yup! Marking as completed
