### ISSUE TITLE
Error while firing this command

### ISSUE THREAD

**Issue by omgaur7** [dotnet/upgrade-assistant#1509]
getting this error while firing upgrade-assistant analyze command
![Capture](https://github.com/dotnet/upgrade-assistant/assets/141411302/093a35b3-f936-4b41-b2d6-2fb9b590c8f2)

**Comment by jstedfast** [comment]
Starting with v0.5, the analyze command was removed.

Note: technically, it wasn't removed so much as the entire program was rewritten from scratch and the analyze command hasn't been implemented (yet?).

**Comment by jstedfast** [comment]
This is a duplicate of issue https://github.com/dotnet/upgrade-assistant/issues/1491 and issue https://github.com/dotnet/upgrade-assistant/issues/1497
