### ISSUE TITLE
UpgradeAssistant.Extensions.Default.Analyzers package missing dependencies - Could not load file or assembly Microsoft.CodeAnalysis.VisualBasic

### ISSUE THREAD

**Issue by TallBaldGeek** [dotnet/upgrade-assistant#1514]
### Describe the bug
We have installed the upgrade assistant Analyzers package to our .NET Framework 4.8 projects to warn us of practices that will cause issues when we update to .NET 6+. We recently updated the package from v0.2.220602 to v0.4.421302 and after that, when doing a fresh build we're getting errors like the following:

```
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.ApiAlertAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.AttributeUpgradeAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.BinaryFormatterUnsafeDeserializeAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.HttpContextCurrentAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.TypeUpgradeAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.WinUIApiAlertAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'.
84>Done building project "*******.csproj" -- FAILED.

```

According to the NuGet page for [Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers](https://www.nuget.org/packages/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers) there are no dependencies for this package. But in the analyzer that is giving a build error [
src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/HttpContextCurrentAnalyzer.cs](https://github.com/dotnet/upgrade-assistant/blob/be0ea11e8234f2a0bde2d170b0fdd455fa4f9a45/src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/HttpContextCurrentAnalyzer.cs#L47) it is using some `Microsoft.CodeAnalysis*`  references:

``` csharp
using CSSyntax = Microsoft.CodeAnalysis.CSharp.Syntax;
using VBSyntax = Microsoft.CodeAnalysis.VisualBasic.Syntax;
```

It seems like the Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers package should explicitly depend upon the packages that distribute the `Microsoft.CodeAnalysis*` dependencies listed above, as well as any others needed.

**Note** -  I tried to replicate this in an example that didn't include our source code, but so far I've not been able to reproduce in a minimal example. 

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
    - Windows 10 Enterprise 21H2, 64-bit
- Include the output of `dotnet --list-sdks`
    - 7.0.400 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`

**Comment by mgoertz-msft** [comment]
No longer applicable.

**Comment by andrueastman** [comment]
@mgoertz-msft Any chance you can clarify where this is longer applicable?

**Comment by mgoertz-msft** [comment]
@andrueastman Of course, sorry. The Upgrade Assistant that used to be in this repo has been replaced by a newer closed source version. This new version does not have a public extensibility API besides the ability to provide JSON-based API and Package map files and this repo has been repurposed to host those 3rd party mappings.

For more information see the main [README.md](https://github.com/dotnet/upgrade-assistant/blob/main/README.md).

**Comment by StevenBonePgh** [comment]
I saw the same errors as reported above, and this is the only web search result for it. It is most likely a conflict with other analyzers. In my case, updating the package reference for xunit from version 2.8.1 to version 2.9.3 resolved this issue.
