### ISSUE TITLE
error NU1101: Cannot find package Microsoft.DotNet.UpgradeAssistant.Telemetry.

### ISSUE THREAD

**Issue by felipebaltazar** [dotnet/upgrade-assistant#1525]
### Describe the bug
Im trying to build an extension for the Maui upgrade assistant, but when I add a reference to `Microsoft.DotNet.UpgradeAssistant.Abstractions` I get this error:

`error NU1101: Cannot find package Microsoft.DotNet.UpgradeAssistant.Telemetry.`

### To Reproduce

https://github.com/felipebaltazar/UpgradeAssistant.Extension.Maui.Community

### Exceptions (if any)
`error NU1101: Cannot find package Microsoft.DotNet.UpgradeAssistant.Telemetry.`

### Further technical details

**- Include the output of `dotnet --list-sdks`**
6.0.202 [C:\Program Files\dotnet\sdk]
7.0.401 [C:\Program Files\dotnet\sdk]
8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]

**- Include the output of `upgrade-assistant --version`**
0.2.241603+99dc6c7bf12364ae199f7acd8d0d42c631508de0

**Comment by mgoertz-msft** [comment]
The old Upgrade Assistant has been replaced with a new closed source one, which doesn't have any public extensibility API at the moment besides the new ability to create package and API mappings. See https://devblogs.microsoft.com/dotnet/announcing-api-map-support-for-ua/
