### ISSUE TITLE
Can't install upgrade-assistant on macOS apple silicon

### ISSUE THREAD

**Issue by Grivus** [dotnet/upgrade-assistant#1529]
**No log file `upgrade-assistant.clef` was created, can't install**

### Describe the bug
I'm trying to install upgrade-assistant on macOS 13.6 (m1 processor), and getting an error:

> Unhandled exception: System.IO.FileNotFoundException: Unable to find the specified file.
>    at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
>    at Interop.Sys.GetCwd()
>    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand..ctor(ParseResult parseResult, IToolPackageInstaller toolPackageInstaller, IToolManifestFinder toolManifestFinder, IToolManifestEditor toolManifestEditor, ILocalToolsResolverCache localToolsResolverCache, IReporter reporter)
>    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand..ctor(ParseResult parseResult, ToolInstallGlobalOrToolPathCommand toolInstallGlobalOrToolPathCommand, ToolInstallLocalCommand toolInstallLocalCommand)
>    at Microsoft.DotNet.Cli.ToolInstallCommandParser.<>c.<ConstructCommand>b__14_0(ParseResult parseResult)
>    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()

### To Reproduce
Just try to install it with any command from readme, like 
`dotnet tool install -g --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources upgrade-assistant`
or 
`dotnet tool install -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`

### Exceptions (if any)
No

### Further technical details
- system version and bitness info (32-bit or 64-bit) : macOS 13.6 m1
- Include the output of `dotnet --list-sdks` 
6.0.403 [/usr/local/share/dotnet/sdk]
6.0.404 [/usr/local/share/dotnet/sdk]
6.0.405 [/usr/local/share/dotnet/sdk]
6.0.406 [/usr/local/share/dotnet/sdk]
6.0.407 [/usr/local/share/dotnet/sdk]
6.0.408 [/usr/local/share/dotnet/sdk]
6.0.410 [/usr/local/share/dotnet/sdk]
6.0.412 [/usr/local/share/dotnet/sdk]
6.0.414 [/usr/local/share/dotnet/sdk]
6.0.415 [/usr/local/share/dotnet/sdk]
6.0.416 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
7.0.101 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
7.0.103 [/usr/local/share/dotnet/sdk]
7.0.200 [/usr/local/share/dotnet/sdk]
7.0.201 [/usr/local/share/dotnet/sdk]
7.0.202 [/usr/local/share/dotnet/sdk]
7.0.203 [/usr/local/share/dotnet/sdk]
7.0.302 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
7.0.308 [/usr/local/share/dotnet/sdk]
7.0.309 [/usr/local/share/dotnet/sdk]
7.0.310 [/usr/local/share/dotnet/sdk]
- Include the output of `upgrade-assistant --version`
no output, can't install it

**Comment by timdinh** [comment]
i have macos with apple silicon and it is working for me. ensure that your default dotnet arch is arm64 since you may have both arm64 and x64 installed

**Comment by Grivus** [comment]
The issue is gone after reboot, never saw it again.
