### ISSUE TITLE
cannot target 6.0 , option "-f net6.0" is ignored

### ISSUE THREAD

**Issue by akasolace** [dotnet/upgrade-assistant#1532]
### Describe the bug
I have the .net 6.0 SDK installed but the upgrade tool does not allow me to upgrade from .net framework 4.8 to .net 6.0.  Only 7.0 and 8.0 are listed as possible choices and the option -f net6.0 is ignored.
In my case targeting 7.0 or above is not an option. Any suggestion on how to force the assistant to target 6.0? 
Thank you 

I am using version 0.5.564.2486
the help option list the following as usage example making it sound like 6.0 is supported
`upgrade-assistant upgrade <PROJECT_PATH> --operation Inplace --targetFramework net6.0 `

**Comment by bsubasic** [comment]
Just install previous version [0.5.261](https://www.nuget.org/packages/upgrade-assistant/0.5.261) and add the flag --target-tfm-support LTS, you will have support for .NET 6.0 (because .NET 8.0 wasn't released yet on this version, so the .NET 6.0 is the only LTS at that moment)

**Comment by mgoertz-msft** [comment]
Correct, LTS has moved from .NET 6.0 to .NET 8.0, so .NET 6.0 is no longer available.
