### ISSUE TITLE
Lots of Xamarin leftovers

### ISSUE THREAD

**Issue by davidortinau** [dotnet/upgrade-assistant#1533]
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory

no such file is present

### Describe the bug

I ran the latest VS UA ext (0.5.563.61476) on each project in this solution, and when I went to start building and fixing the library project found that a LOT of namespaces were left unchanged from Xamarin.Forms to Microsoft.Maui or related.

### To Reproduce

Clone it, run through the in place upgrade, and then try to build the library project. Observe the errors.

https://github.com/xamarin/app-xamarintv

You may also discover the additional `net8.0` tfm is problematic. I had to remove that.

### Further technical details

```
PS C:\Users\daortin> dotnet --list-sdks
7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]
8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
8.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by mgoertz-msft** [comment]
Please reopen if this is still a problem
