### ISSUE TITLE
.net6 not showing up in upgrade assistant

### ISSUE THREAD

**Issue by mayajose** [dotnet/upgrade-assistant#1535]
I have installed .net upgrade assistant plugin for vs2022. When I click on upgrade, "Upgrade to a newer .net version" I do not see option to select .net6, though .net6 is installed in my machine. (.net7, .net8, .netstandard2. .netstandard2.1 are still present)
.net6 option was there before and it disappeared today. Any help would be appreciated.

**Comment by mgoertz-msft** [comment]
.NET 6.0 as the current LTS release would have been replaced with .NET 8.0 now, which is the new LTS release.
