### ISSUE TITLE
Getting unhandled while install upgrade assistant with dotnet tool 

### ISSUE THREAD

**Issue by prakashdiwakar** [dotnet/upgrade-assistant#1543]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Getting unhandled error as below
![image](https://github.com/dotnet/upgrade-assistant/assets/145442787/7d23f3c7-7f57-43df-bac5-f92bf77e36e9)

**Comment by mgoertz-msft** [comment]
Looks like you mis-spelled `upgrade-assistent`. It should be `upgrade-assistant`.
