### ISSUE TITLE
Multiple upgrade operations are applicable to source project, user input is required.

### ISSUE THREAD

**Issue by ChandraMohanMuthyala** [dotnet/upgrade-assistant#1547]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mgoertz-msft** [comment]
Please follow the instructions here: https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-install
