### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by akingboy123** [dotnet/upgrade-assistant#1551]
- [x] Include the log file `upgrade-assistant.clef` that is produced in the working directory

### Further technical details
- Windows version and bitness info (32-bit or 64-bit)
- Include the output of `dotnet --list-sdks`
- Include the output of `upgrade-assistant --version`

**Comment by akingboy123** [comment]
Yet

**Comment by akingboy123** [comment]
[Uploading bug fixer.zip…]()

**Comment by akingboy123** [comment]
[Uploading [TIE]_Motor_PDS_ENG_Rebate_@13.01.2020.pdf…]()

**Comment by mgoertz-msft** [comment]
Closing for lack of details
