### ISSUE TITLE
Xamarin Forms project to .NET MAUI

### ISSUE THREAD

**Issue by Auto72** [dotnet/upgrade-assistant#1552]
The upgrade assistant updated the  Xamarin Forms project successfully, but then, when the Android project was converting, I got the following error:

	Microsoft.IntelliCode.Transformations.Upgrade.IC107CProseUgradeTransformer
	info: Done
	Microsoft.UpgradeAssistant.Maui.Transformers.Code.CSharp.MauiMemberMapTransformer
Failed to execute Azure Artifacts credential provider.
[Minimal] [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json
[Minimal] [CredentialProvider]ATTENTION: User interaction required. 

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code L34UT96XA to authenticate.

    **********************************************************************

[Warning] [CredentialProvider]A task was canceled.

I tried to login to that page with my account, after I provide the code above, but it did not let me in.

**Comment by mgoertz-msft** [comment]
That looks like it's trying to use an internal feed. Do you use a preview version of .NET by chance? I have a feeling that you would get a similar issue when trying to install/update the workloads for .NET MAUI.

**Comment by DianaSoltani** [comment]
There may have been a temporary issue. Please open an issue with the .NET MAUI team if the issue persists.
