### ISSUE TITLE
Typo in description for NuGet.0004

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/upgrade-assistant#1558]
### Describe the bug
Text for NuGet.0004 reads "secutiry" instead of "security"
![image](https://github.com/dotnet/upgrade-assistant/assets/8855055/c0058bf1-1cac-49c5-a286-d97fad04f3ad)

**Comment by mgoertz-msft** [comment]
Thank you for reporting. Already fixed in `main`. Not sure if it's been released yet.

**Comment by mgoertz-msft** [comment]
Should be included in today's release if it wasn't already.
