### ISSUE TITLE
How to use a packagemap.json in my project?

### ISSUE THREAD

**Issue by claudeHasler** [dotnet/upgrade-assistant#1570]
I'm trying to automate the upgrade of a very large application with many .csproj using the upgrade-assistant CLI.
I'd like to force certain packages in those .csproj to be updated to certain versions.

The packagemap.json feature seems to support this functionality, But I can't figure out where this file must be placed to be picked up by the cli.

I am running a command like this:
```
upgrade-assistant upgrade `
			SomeProj/.csproj `
			--non-interactive `
			--operation Inplace `
			--targetFramework net8.0
```

But my custom defined packagemap.json file is never respected

Where do the packagemap files go? Is this documented anywhere? Is this even how these files are intended to be used?

**Comment by mgoertz-msft** [comment]
Take a look at this blog post for how to test package map changes locally: https://devblogs.microsoft.com/dotnet/announcing-api-map-support-for-ua/

**Comment by DianaSoltani** [comment]
Guidance has been provided.
