### ISSUE TITLE
upgrade-assistant cli and cmd-line target to only update the project to SDK style

### ISSUE THREAD

**Issue by phroos** [dotnet/upgrade-assistant#1579]
Hi!
Feature might be present, and just undocumented, but I'd like the upgrade-assistant cli to be able
to  _only_ upgrade the project to SDK-style, but KEEP the current framework.

Something like:
```
upgrade-assistant upgrade FuseBatch.csproj -o feature.sdkstyle -o Inplace --non-interactive (omitting the framework flag), or
upgrade-assistant upgrade FuseBatch.csproj -o feature.sdkstyle -o Inplace --non-interactive -f KEEP (keeping the framework version)
```
## Motivation and goals

The motivation of this is to remove older unreadable project types, and enable further analysis by tools that work only on SDK style projects.

## In scope

if functionality exists; documentation how to do this should be improved, and made easier to find (have looked at articles, the doc for the cli-tool, the github repo, MS Learn, e.t.c)

if not, the requirement of the -f flag could be removed (thus enabling the cli tool to be called without upgrading framework), or
a special value added to the -f flag, (like the values LTS, Current, Preview), for example "Keep" .

**Comment by abpiskunov** [comment]
This feature exist for a while already. If you run "upgrade-assistant upgrade" and select classic project it would how you all available upgrade types including "only sdkstyle". Command line will be "upgrade-assistant upgrade FuseBatch.csproj -o feature.sdkstyle --non-interactive"

**Comment by abpiskunov** [comment]
Here is a blog post about it: https://devblogs.microsoft.com/dotnet/upgrade-assistant-august-2023-update/

**Comment by abpiskunov** [comment]
@mckennabarlow when we add more docs to this repo, lets add more sample command lines for people to copy and paste.

**Comment by phroos** [comment]
You sir (@abpiskunov), are awsome. Thanks!
