### ISSUE TITLE
How to add extension mappings

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/upgrade-assistant#1580]
The extensions portion of the readme indicates how to add custom vendor mappings to the tool. But how does this work for tools that are already deployed via either CLI or VS exstension? Let's assume we don't want to modify the actual code in Github, how do we add these mappings to an existing instance? My first thought was to find the extension directory in VS (not easy by the way) and then add the `mappings` structure to that. But not sure if this even works correctly.

Please provide clear documentation on how to create our own (company specific) mappings that integrates with either the CLI or VS extension versions of the tool. Even better would be to make it easy to do this via the VS UI (for the extension at least) so we don't have to find the randomly-generated extension directory ourselves.

**Comment by CoolDadTx** [comment]
Followed the information on the corresponding [blog article](https://devblogs.microsoft.com/dotnet/announcing-api-map-support-for-ua/) and I still cannot get this to work. The built package is in a local feed, there is a nuget.config file that points to the package location and then nothing.

Are there some sort of logging options that can help determine if the extensions are being loaded and/or help diagnose why the mappings aren't working? Right now there doesn't seem to be anything logged about the extensions. 

It would be even better if we could package the mappings into their own packages independent of anything else and then specify the list of mappings to load as part of the tool. Sometimes I might want to use one set of mappings and a complete different set other times (different companies, different rules).

**Comment by jstedfast** [comment]
I'll work on adding more logging to make this easier to diagnose.

In the meantime, you probably just need to delete your nuget package cache.

**Comment by jstedfast** [comment]
Logging has been added/released
