### ISSUE TITLE
Unable to generate a report for a large solution

### ISSUE THREAD

**Issue by AzatTazayan** [dotnet/upgrade-assistant#1581]
We have an enterprise application, and the main solution has 240 projects. I have run the upgrade on that solution, and after 5 minutes, it is just spinning without consuming CPU time; therefore, I assume that the upgrade is stuck somewhere and the timer doesn't refresh, just the progress is spinning. After I opened another solution within that repo with 163 projects, the same thing happened. Finally, I ran it on the solution with 75 projects and it took 8 min 3 sec to finish. It seems there is a problem with big solutions. I will leave it overnight to see if I get any reports eventually.

OS: Windows 11 Enterprise - 22631.3737
CPU: 13th Gen Intel(R) Core(TM) i9-13950HX
VisualStudio: Version 17.10.2

**Comment by mgoertz-msft** [comment]
@AzatTazayan  Make sure to turn off `Binary dependencies` when creating an upgrade assessment report:

![image](https://github.com/user-attachments/assets/3b1fdd17-67f8-46cf-8b5d-504a8e54cbfe)

With this option off it will only analyze your own code dependencies. Turning it on will analyze **all** binary dependencies whether you use them or not, and that takes **a lot** longer.

**Comment by DianaSoltani** [comment]
Were you able to try running this without the binary dependencies, @AzatTazayan? Where you able to run it over night?

**Comment by AzatTazayan** [comment]
Ho @DianaSoltani, it was without the binary dependencies. Today, I ran it again with the updated version of the tool on 240 projects, and I was successfully able to get the report; it just took 16 minutes.
