### ISSUE TITLE
What is the full list of all command-line options for upgrade-assistant CLI?

### ISSUE THREAD

**Issue by AndreasNVI** [dotnet/upgrade-assistant#1582]
This is more of a documentation issue. But what is the full list of all possible command-line options when running the CLI version of the upgrade assistant?

I want to automate the analysis and upgrade process of literally 100s of projects at my client's organization, and it seems I keep running into instances where it is either looking for user interaction, or it needs additional details.

**Comment by mckennabarlow** [comment]
Running the command `upgrade-assistant --help` will display the full list of command-line options when running the CLI version of the upgrade assistant. More information can be found [here](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview) .

**Comment by antibarbie** [comment]
Same question here, since the product is now closed source (WTF!),  options are now completely opaque to us users, and spectre.cli automated --help does not automatically document everything.

Just to be clear, there does not seems to have a --yes or --force option, we just can't bear to click or select/enter 400's or 500's times.

**Comment by antibarbie** [comment]
It should support something like that, though it seems completely buggy and does not gets the framework correctly.

`upgrade-assistant.exe upgrade my.old.csproj --operation Inplace --targetFramework "net8.0" --non-interactive`

**Comment by antibarbie** [comment]
Closing a "documentation is missing" bug without explanation make me feel sad about being a m$ paid user...Le 25 juil. 2024 17:44, Diana Soltani ***@***.***> a écrit :
Closed #1582 as not planned.
