### ISSUE TITLE
Installing package refused 

### ISSUE THREAD

**Issue by Ssenabuly** [dotnet/upgrade-assistant#1583]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-sdk
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Ssenabuly** [comment]
I was trying to install Microsoft.net SDK 8.0.302 but it refused saying that the installation package is not supported  by the processor

**Comment by mgoertz-msft** [comment]
For issues with the SDK itself please raise an issue at https://github.com/dotnet/sdk/issues
