### ISSUE TITLE
Source code for eng and src missing

### ISSUE THREAD

**Issue by nnganesha** [dotnet/upgrade-assistant#1585]
Hello all,

I do not see the source code for the Upgrade assistant project here. Specifically the eng, src as well as the legacy try-convert folders. Was there any change done after 0.5.2? If so, where can I get the earlier versions of the source code - is there any branch where I can take the same? Any changes to this open source project?

Regards,
Ganesh.

**Comment by mgoertz-msft** [comment]
The Upgrade Assistant that used to be in this repo has been replaced by closed-source versions. We have repurposed this repo to host 3rd party mappings that can be used by the newer Upgrade Assistants (VS extension or CLI).

**Comment by nnganesha** [comment]
Thank you!
