### ISSUE TITLE
Test Upgrade Assistant with only the .NET SDK installed (not VS)

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#181]
The readme currently says that users should have VS2019 installed, but the tool's MSBuild dependencies should be satisfied by the .NET SDK. We should double-check that the SDK is all that's needed to run the Upgrade Assistant and update the readme.

**Comment by adegeo** [comment]
@mjrousos @twsouthwick  Is there an update to this? I'm currently updating the https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview#prerequisites docs to remove try-convert as a prerequisite.

**Comment by twsouthwick** [comment]
The best thing to say is that you need to be able to compile. For web apps, wpf, etc that generally means VS is installed.
