### ISSUE TITLE
Bug: When all of the projects have been upgraded end the session

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#239]
### Repro
1. Finished migrating my project
> project details available in #237  
2. Continued to "next step" until i hit this error

![image](https://user-images.githubusercontent.com/23503973/109066267-74288180-76b2-11eb-90af-093d3a585f48.png)

**Comment by KSchlobohm** [comment]
This may already be fixed, I was testing an older version.

Sorry, I've updated my tooling since this issue was reported and I'm not sure which version this was reported from

**Comment by mjrousos** [comment]
No, I saw something similar recently. I think this is still an issue (though I haven't investigated it at all)

**Comment by KSchlobohm** [comment]
I tested this today and the upgrade closed smoothly when I was running an upgrade for a solution with only one project.

In the screenshot above there were multiple entry points available in the solution. Perhaps that is part of the way this surfaced.

**Comment by brandonh-msft** [comment]
The way it works today is you get to migrate only one project at a time. I just tested with FabrikamFiber and pointed it at the SLN file. It prompted which project to migrate (I chose the DAL one), went thru the whole upgrade, then ended after migrating _only that one project_.
