### ISSUE TITLE
Automatically move the Content folder under wwwroot when migrating a web app

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#241]
When migrating a legacy MVC app the Content & Scripts folders were used to store static files that should be served from the wwwroot directory

![image](https://user-images.githubusercontent.com/23503973/109075321-958f6a80-76be-11eb-8b44-2751215b2a5a.png)

**Comment by KSchlobohm** [comment]
Depending on what you upgraded you may experience this as a compile error.

![image](https://user-images.githubusercontent.com/23503973/113457649-f274f380-93d5-11eb-9cc5-d76b5705fbc8.png)

Error `Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'appsettings.json'`

**Comment by twsouthwick** [comment]
There are two options we can enable, and I'm not sure which is the *best*:

1. Move the files into the pattern ASP.NET Core expects by default
2. Keep the files where they are and add custom file providers to expose them as expected

The benefitof (2) is that long-term I believe we'll look at duplicating the head project and seeing how the two projects can live side-by-side. By updating the code to look in the `Content`/etc, the two csproj files can live in the same directory (not sure if that's how we'll do it, but it simplifies code-sharing).

For example, here's a directory listing:

```
dir
  |- old.csproj
  |- new.csproj
  |- Content
  |- Scripts
  |- ...
```

The `old.csproj` would stay the way it is so things keep working and devs can keep it deployable. We update the `Startup.cs` to have something similar to the following:

```cs
// This is to enable accessing Content from the directory. If possible, this content should be moved into `wwwroot/` which by default is served to the client.
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider("Content"),
    RequestPath = new PathString("Content")
});
```
```

**Comment by oteinone** [comment]
I've rarely seen Content/Scripts folder used in MVC5-projects as the only folders with static content. Quite often there have been other folders like 'Styles' or 'bootstrap'. Even the [MvcMovie example](https://github.com/dotnet/AspNetDocs/tree/main/aspnet/mvc/overview/getting-started/introduction/sample/MvcMovie/MvcMovie) has a 'fonts'-folder.

I think that even though moving the files to wwwroot would be better for the long-term, it might quite often cause scenarios where some static files are moved but not all of them.

As a prospective user for this tool I would maybe prefer adding a static file provider for content-folder as an example and a `//TODO` for any other folders with static content.
