### ISSUE TITLE
Create an Analyzer to flag legacy web app artifacts (Global.asax)

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#242]
* NinjectWebCommon.cs
* Global.asax.cs
* BundleConfig.cs
* RouteConfig.cs
* FilterConfig.cs

**Comment by mjrousos** [comment]
Good idea. I don't think global.asax.cs is something we'll be able to automatically migrated, but we should add an analyzer to produce a warning for the file and point users at ASP.NET migration docs. 

NinjectWebCommon I'm not as sure about. It's ninject-specific (I assume) and handling all the different DI frameworks users use is probably a lower priority, at least initially.

**Comment by KSchlobohm** [comment]
@mjrousos , you're right that `NinjectWebCommon.cs` is a ninject-specific file and while it would be difficult to make recommendations for every DI framework I think it would be valuable to add some detection for the top 3 or so that mentions *where* service registration should be done in the new version.
