### ISSUE TITLE
401 error during installation

### ISSUE THREAD

**Issue by bigtfromaz** [dotnet/upgrade-assistant#251]
This command, as well as other forms of the command are failing with a 401 error:
dotnet tool install -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

Is failing with a 401:
C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/objex/_packaging/ObjEx/nuget/v3/index.json. [C:\Users\myaccountname\AppData\Local\Temp\fiysvqdm.pbj\restore.csproj]
**C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized)**. [C:\Users\myaccountname\AppData\Local\Temp\fiysvqdm.pbj\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

Should we be signed on somewhere or is this an installation issue?

**Comment by sunandabalu** [comment]
Try installing from the nuget feed instead as mentioned here - https://github.com/dotnet/upgrade-assistant#installation-steps

```
dotnet tool install -g upgrade-assistant
```

**Comment by bigtfromaz** [comment]
`dotnet tool install -g upgrade-assistant`

Same error:

`C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized).`

No idea what's issuing the 401.

**Comment by twsouthwick** [comment]
Can you install any package? ie `dotnet tool install -g apiport`

**Comment by bigtfromaz** [comment]
@twsouthwick That was the tip I needed.  We have a rarely used private repo and I wasn't signed in.  So rather than signing in, I added **--ignore-failed-sources** which worked.  The answer is in the message but I didn't see it.

`dotnet tool install --ignore-failed-sources -g try-convert`

So this issue is a bit off topic. The monitor should hide it, if it doesn't add value.
