### ISSUE TITLE
When i make use of Central Package Management, it cannot detect the package versions in the csproj.

### ISSUE THREAD

**Issue by ErwinBakels** [dotnet/upgrade-assistant#252]
When i make use of Central Package Management, it cannot detect the package versions in the csproj.

![image](https://user-images.githubusercontent.com/25903888/109198862-0312c800-779f-11eb-85e7-461cb144d3ab.png)

**Comment by twsouthwick** [comment]
Good catch! Are you using Directory.Packages.props to define the version?

**Comment by ErwinBakels** [comment]
I use in Directory.Build.props the following

  
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <EnableCentralPackageVersions>true</EnableCentralPackageVersions>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>

<CentralPackagesFile>$(RootDir)PackageVersions.props</CentralPackagesFile>
  </PropertyGroup>


and in my PackageVersions.props

<Project>

  
  <ItemGroup>
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.7.0" />
    <PackageReference Update="Moq" Version="4.14.5" />
    <PackageReference Update="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Update="MSTest.TestFramework" Version="2.1.2" />
    <PackageReference Update="SpecFlow" Version="3.0.220" />
    <PackageReference Update="SpecFlow.MsTest" Version="3.0.220" />
    <PackageReference Update="SpecFlow.Tools.MsBuild.Generation"
Version="3.0.220" />
  </ItemGroup>





Kind regards,

*Erwin Bakels*
Software Developer/Consultant


*Note: This email and its content is confidential and intended only for the
addressee. If you are not the addressee of this e-mail, please inform the
sender immediately by means of a reply e-mail and remove the received
e-mail from your systems. If you are not an addressee, you may not peruse,
copy, distribute, disclose or otherwise use the content.*


Op do 25 feb. 2021 om 19:54 schreef Taylor Southwick <
notifications@github.com>:

**Comment by twsouthwick** [comment]
This will be a bit of work to enable, so we'll keep this open while also adding a preliminary check to notify people that this isn't supported at the moment.

**Comment by sunandabalu** [comment]
- [ ] Read the props file for versions probably a medium workitem
 - [ ] Updating versions in the props file would be a large workitem

**Comment by nkolev92** [comment]
The issue here applies to simply PackageReference update as well. It doesn't have to Central package management (SDK or built-in feature). 

Example:

csproj sample:
```xml
<Project>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="bla" />
  </ItemGroup>
<Project>
``` 

DBP sample
```xml
<Project>
  <ItemGroup>
    <PackageReference Update="bla" Version="1.0.0" />
  </ItemGroup>
<Project>
```

**Comment by Tohnmeister** [comment]
Any update on this? We're looking to migrate a code-base of several 100 kloc of C# code from old-style .csproj files and .NET Framework 4.8 to new-style .csproj files and .NET 5. But we're heavily using central package management.

**Comment by brandonh-msft** [comment]
@ErwinBakels any chance you could provide a small sample app that repros this? Thanks!

**Comment by ErwinBakels** [comment]
Hi Brandon,

That issue was from a long time ago. I do not have access to that code anymore because it was for a previous client.

It was also the only client who used Central Package Management, because they had about 1400 projects in 1 solution and it was easier to update the package this way.

For now, if nobody else complains, we can close this ticket, seems not enough people use Central Package Management and want to update their projects/solutions.

**Comment by verydarkmagic** [comment]
Very sad to see this closed as not planned.
With a 1 year release cycle on .NET its very hard to keep with if upgrade assistant does not support Central Package Management feature.
Please reconsider!
