### ISSUE TITLE
Substeps show as [Completed] when they need to be applied

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#258]
While converting an ASP.NET Web MVC3 project I found that the substeps show as [Completed] before they're applied.

Shows UA0003 as completed
![NextStep-ApplyFixForUA0001](https://user-images.githubusercontent.com/23503973/109208904-8668f500-7770-11eb-952b-60c580ca9e2f.png)

> noted that resizing the console window may have caused one of the line items to be printed off to the right

The next step was to apply the fix for UA0003
![NextStep-ApplyFixForUA0003](https://user-images.githubusercontent.com/23503973/109209148-cfb94480-7770-11eb-85fe-c7a97c9b4fc5.png)

**Comment by sunandabalu** [comment]
Steps that are not applicable for the project will be displayed as Complete, meaning there is no action needed. We have an issue open to #255 to filter the steps based on components. This should be addressed with that change.

**Comment by KSchlobohm** [comment]
Thanks, I see that I misread the status of UA0003 in the first screenshot :D
