### ISSUE TITLE
Automatic mode

### ISSUE THREAD

**Issue by WojciechNagorski** [dotnet/upgrade-assistant#259]
I would like to apply all steps for all projects in the `SLN` file in an automated way. Currenlty I have to wait and press "1" many times for every project. I have 153 projects in the solution.

I know that my solution won't be work, after applying all steps. But I would like to check what is the biggest problem. In my case I know that I need to remove WPF and rewrite some part of ASP.NET MVC. But I know some small projects will work without any changes.

**Comment by sunandabalu** [comment]
You can run upgrade-assistant with --non-interactive, which will auto-select option 1 for each step.

**Comment by WojciechNagorski** [comment]
I didn't know because the readme doesn't contains this option. I'll check and if it works, I'll update a readme.

**Comment by cathysull** [comment]
Suggestion to add the option for an entry point as well.

**Comment by WojciechNagorski** [comment]
@sunandabalu the `--non-interactive` option is undocumented, the help doesn't contain information about this option:

```bash
❯ upgrade-assistant -h
-----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.212405+8e7b4314944e5328780f06f20721a4d6ef9783bb -
-----------------------------------------------------------------------------------------

Makes a best-effort attempt to upgrade .NET Framework projects to .NET 5.

This tool does not completely automate the upgrade process and it is expected that
projects will have build errors after the tool runs. Manual changes will be required to
complete the upgrade to .NET 5.

This tool's purpose is to automate some of the 'routine' upgrade tasks such as changing
project file formats and updating APIs with near-equivalents in .NET Core. Analyzers added
to the project will highlight the remaining changes needed after the tool runs.

Usage:
  upgrade-assistant [options] <project>

Arguments:
  <project>

Options:
  --skip-backup                  Disables backing up the project. This is not
                                 recommended unless the project is in source control
                                 since this tool will make large changes to both the
                                 project and source files.
  -e, --extension <extension>    Specifies a .NET Upgrade Assistant extension package to
                                 include. This could be an ExtensionManifest.json file,
                                 a directory containing an ExtensionManifest.json file,
                                 or a zip archive containing an extension. This option
                                 can be specified multiple times.
  -v, --verbose                  Enable verbose diagnostics
  --version                      Show version information
  -?, -h, --help                 Show help and usage information
```

**Comment by WojciechNagorski** [comment]
I checked and the hidden `--non-Interactive` option works, but I don't understand why this option is hidden 

This hidden option was added here: #171

**Comment by WojciechNagorski** [comment]
@twsouthwick Maybe you know?

**Comment by mjrousos** [comment]
This was added undocumented originally because we felt in most cases it was better for customers to not use non-interactive mode so that they would better understand the changes being made by the tool.

Running in non-interactive mode can result in a lot of changes to a user's project, leaving it in a state that doesn't build correctly without them understanding everything that changed (which makes it hard to fix).

For scenarios with many projects, though, I see the value of the mode. Perhaps we can add documentation for the argument, but include cautions that it will make many changes automatically and may not be appropriate for small solutions.

**Comment by sunandabalu** [comment]
I'll add documentation about the non-interactive mode with the disclaimer about the possibility that this could leave the user's projects in a messed up state wrt building/changes made. I'm working on adding a dependency on providing an entry-point if running on non-interactive mode to minimize some of the churn.

**Comment by mjrousos** [comment]
Great; thanks, @sunandabalu!

**Comment by twsouthwick** [comment]
@WojciechNagorski The main reason is that the non-interactive mode on a large solution will select the entrypoint as your alphabetically-first project at the moment. This happened to work for our demos, so it was sufficient, but wasn't ready for prime-time. Once that's addressed (@sunandabalu is working on that), it's definitely worth giving a try and seeing what falls out.

**Comment by sunandabalu** [comment]
This is done via #282 , closing this.
