### ISSUE TITLE
Add Support for Conditional Steps (handle legacy apps with Newtonsoft.Json serialization)

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#267]
Many legacy apps use the default Newtonsoft serializer settings. In ASP.NET Core this was replaced with System.Text.Json which changes the format of content returned from Web API endpoints.

Adding support for a Conditional Step would enable the Upgrade Assistant to display a prompt that can ask the user if they would like to apply the Netwonsof Serializer settings to their new Startup.cs

Support for a Conditional Step would also increase the flexibility of extensions offered by the tool

**Comment by mjrousos** [comment]
I think we might want to just make this a normal upgrade step. I think users would often want to apply it and there's already a 'skip' option if they don't.

**Comment by cathysull** [comment]
Thoughts: Not having a step to convert the usage of Newtonsoft.Json... to System.Text.Json (which is the default) - update the startup template to contain Newtonsoft and add the reference. Then provide information to **consider** moving to System.Text.Json and the reason why.

**Comment by KSchlobohm** [comment]
Addressed by #306
