### ISSUE TITLE
What if you have a preview version of the .Net 5 sdk?

### ISSUE THREAD

**Issue by jphellemons** [dotnet/upgrade-assistant#269]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-try-convert
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My `dotnet --list-sdks` gives:

>5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.200-preview.21079.7 [C:\Program Files\dotnet\sdk]

So I have no global.json to specify the 5.0.103 and dotnet keeps using the 5.0.200... even when I run:
`C:\Program Files\dotnet\sdk\5.0.103> dotnet.exe tool install -g upgrade-assistant`

How can I force it to use a lower version?

**Comment by mjrousos** [comment]
By default, the tool will use (and should work with) the latest version of the .NET SDK installed. Is it not working with 5.0.200?

That said, a global.json file should work to redirect it back to 5.0.103 if you need to do that for some reason.

**Comment by jphellemons** [comment]
It's the installation which is rejecting it due to the preview version of
the sdk. So can't run the install global tool thingy

Op vr 26 feb. 2021 15:36 schreef Mike Rousos <notifications@github.com>:

**Comment by mjrousos** [comment]
How strange. I don't run into any issues installing with a preview SDK. Can you share more details on the error you're seeing when trying to install?

![image](https://user-images.githubusercontent.com/10077254/109336387-4cabf300-7831-11eb-8f9e-e91c12d2d87a.png)

**Comment by cathysull** [comment]
Include link to the dotnet tooling install docs (check in try-convert) - add to the FAQ/troubleshooting.

**Comment by jphellemons** [comment]
I think it is proxy related. Sorry for the "fakenews"! 
I see a 401 unauthorized returning from the nuget.targets(131,5)
