### ISSUE TITLE
Upgrade VB projects

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#270]
Related to #265 (which concerns error messaging when users run the tool on VB projects), it would be great to have the tool work on VB projects in the future.

Updating all the source fixers to work on both C# and VB would be a fair bit of work (though not necessarily one we don't want to do), but at least getting all the upgrade steps *until* the source update step working with vbproj should be a more manageable work item that we should investigate doing sooner.

**Comment by KSchlobohm** [comment]
1. end of April #400
1. end of April #376
1. end of April #378
1. end of April #255
1. mid May #310

**Comment by andreymir** [comment]
I'm trying to convert our VB.NET projects and as a test, I created a simple VB.NET library with a single class that looks like this
```vb.net
Public Class Class1
    Public Sub SayHello()
        Console.WriteLine(UCase("Hello, today is {0}"), Format(Now, "yyyyMMddhhmmssff"))
        Console.WriteLine(Len("hello"))
        Console.WriteLine(FormatCurrency(100.00))
    End Sub
End Class
```
The tool does not do anything with `UCase`, `Format`, `Now`, `FormatCurrency` functions, and the project does not compile. Is there a way to upgrade this code to net5 or netstandard2.0?

**Comment by KSchlobohm** [comment]
@andreymir please open your question as a new issue

**Comment by brandonh-msft** [comment]
@KSchlobohm / @mjrousos is this item considered closed?

**Comment by brandonh-msft** [comment]
Closing. we are now tracking vb issues & work w/ the [area:VB.NET label](https://github.com/dotnet/upgrade-assistant/labels/area%3AVB.NET)
