### ISSUE TITLE
Update NuGet Package fails with invalid project

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/upgrade-assistant#292]
I'm running the tool on a solution that contains an MVC 5 project and several class libraries. The libraries are in the SDK format with NuGet package references. The MVC5 project is the old project format. I have gotten to the step where it wants to upgrade my first class library project and then it wants to upgrade the NuGet packages. When that step runs it fails with the error "Invalid project: *.csproj". There is no indication as to what is wrong or why it is failing. That project is already in the SDK format, it targets .NET 4.7.2 and it already uses package references. Here's the project file it is trying to upgrade.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
   
  <ItemGroup>
    <PackageReference Include="Fsmb.Apollo" Version="8.1.0" />
    <PackageReference Include="Fsmb.Augusta" Version="4.1.2" />
    <PackageReference Include="Fsmb.EnterpriseServices.Logging" Version="4.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
</Project>
```

The FSMB packages are company packages hosted in our Nuget repo that is authenticated. Given the earlier issue with authenticated feeds I don't know if that is what is causing the problem here. Just to check I commented out the non-Nuget.org packages and it failed with the same error. Not sure if this information is cached or something such that I would need to rerun the tool after the project file change.

Attaching the log file.

[log.txt](https://github.com/dotnet/upgrade-assistant/files/6071038/log.txt)

**Comment by sunandabalu** [comment]
@mtaylorfsmb Could you provide a verbose log for this issue? 
```upgrade-assistant <solution/project> -v```

Also we made a lot of bug fixes in this area, could you confirm you see this issue in the latest release of upgrade-assistant too? https://www.nuget.org/packages/upgrade-assistant/0.2.220602

**Comment by sberkovitz** [comment]
@sunandabalu I can confirm that the latest 0.2.220602 resolves this particular error for my projects.

**Comment by sunandabalu** [comment]
@mtaylorfsmb Closing this issue based on above comment, feel free to re-open if you are still seeing this issue.

**Comment by mtaylorfsmb** [comment]
@sunandabalu at this time I am unable to verify whether it works because I'm impacted by the authenticated Nuget feed issue that was already reported. Until the tool can pull from authenticated Nuget packages like Azure DevOps there is no way for me to validate.

**Comment by sunandabalu** [comment]
> @sunandabalu at this time I am unable to verify whether it works because I'm impacted by the authenticated Nuget feed issue that was already reported. Until the tool can pull from authenticated Nuget packages like Azure DevOps there is no way for me to validate.

#359 is tracking the work for auth Nuget feeds, its in progress currently.
