### ISSUE TITLE
Put backups and logs in a folder or location not tracked by Git

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/upgrade-assistant#293]
I suspect many people are going to run this tool on projects in Git/Github. If someone runs the tool and gets things working and then commits to Git then the backup projects and log files will be included using the default settings of the tool. 

It would probably be nice if the tool defaulted to placing the log file and backups someplace that would not get committed to Git by default. Maybe a `backup` folder or something that could be included in a `.gitignore` file would be nice. Even better would be if the tool looked for a `.gitignore` and added the location to it automatically or something.

**Comment by sunandabalu** [comment]
#435 is a good design proposal for address backup folder locations, closing this in favor of that.
