### ISSUE TITLE
Would be nice to have tool provide post-upgrade recommendations until tool supports the automation

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/upgrade-assistant#295]
There are several things that the tool does not currently do automatically but which most people would probably want to do. Until the automation is there to support the post-upgrade work (if ever) then it would be nice if the tool could provide a checklist of sorts to identify things that need to be changed manually. On a sample run on my MVC 5 project I see the following steps I'll need to handle manually.

1. Remove the existing `AssemblyInfo.cs` file and move that into the project file and reset the project flag to auto-generate. I could see that the tool could automate the migration of the SDK-support stuff like product name and whatnot and perhaps leave the `assemblyinfo` file if there are stuff it cannot migrate.
2. The `web.config` file is left intact but things like connection strings are not migrated. It would be nice if the tool could specify what needs to be migrated from the config to the settings.
3. In new ASP.NET Core projects all the content is under `wwwroot`. I thought this was required but maybe not. Irrelevant the tool should either do this automatically or provide the recommended approach to move the content under `wwwroot` to be consistent with new ASP.NET Core projects.

There may be other things, based upon other project types, that should be added to the post-upgrade checklist.

**Comment by sunandabalu** [comment]
Post-upgrade report is being tracked here #368
