### ISSUE TITLE
Config file migration does not migrate connection strings

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/upgrade-assistant#297]
Connection strings in .NET Core have a pre-defined location in the appsettings.json file. The migration tool does not move the connection strings but it does move the appsettings section from the config. It would be nice if the migration also moves the connection strings from the config to the appsettings.json file.

**Comment by mjrousos** [comment]
Yep, agreed. This is already on the backlog (#64) and should be happening soon.

**Comment by CoolDadTx** [comment]
Sorry didn't see that in the search results when I looked.
