### ISSUE TITLE
Cannot install on macos

### ISSUE THREAD

**Issue by nroypf** [dotnet/upgrade-assistant#301]
The tool package could not be restored.
Tool 'try-convert' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by mjrousos** [comment]
This is expected. The tool has dependencies that make it work on Windows only, at the moment.
