### ISSUE TITLE
Suggestion: Try convert installation before upgrade-assistant installation

### ISSUE THREAD

**Issue by vvijayalakshmi21** [dotnet/upgrade-assistant#302]
Hi, 
Instead of manually installing try-convert prior to upgrade-assistant, is it possible to automatically install the required version of try-convert as well when a user installs upgrade-assistant?

Not sure how easy or hard it is to do.
Just a suggestion.

**Comment by vvijayalakshmi21** [comment]
Sorry for creating an issue. Couldn't find the discussion forum

**Comment by mjrousos** [comment]
Thanks for the suggestion, @vvijayalakshmi21. This is something we've talked about but haven't found a good way to do in the past. I think @sunandabalu was looking into possibilities for chaining the installers. Ideally we would have the Upgrade Assistant install automatically install try-convert as a separate tool but we need to spend more time investigating the feasibility of that.

**Comment by sunandabalu** [comment]
Yep I'm looking into adding try-convert as a dependency to be able to bundle together with upgrade-assistant, #178 is tracking that effort.

**Comment by sunandabalu** [comment]
Closing as this is covered by #178
