### ISSUE TITLE
Visual studio extension

### ISSUE THREAD

**Issue by vvijayalakshmi21** [dotnet/upgrade-assistant#311]
Hi,
Is it in your roadmap to have upgrade assistant as an vs extension (similar to .net portability analyzer with an option to choose the required target .net core version)?

**Comment by sunandabalu** [comment]
Thanks @vvijayalakshmi21. We do have in our backlog to explore the option of a VS integration.

**Comment by brandonh-msft** [comment]
dupe of #54
