### ISSUE TITLE
 Apply fix for UA0010: [AllowHtmlAttrubute] should be removed - running the same file from past 12 hrs

### ISSUE THREAD

**Issue by ShilpaH-SyMetric** [dotnet/upgrade-assistant#313]
j. Apply fix for UA0010: [AllowHtmlAttrubute] should be removed - this process is taking a long time like I initiated migration yesterday, It is running some helper class for the past 12 hrs and still running.

![image](https://user-images.githubusercontent.com/71071848/109939540-2c7ba880-7cf7-11eb-818a-31282c5086d8.png)

![image](https://user-images.githubusercontent.com/71071848/109939939-8e3c1280-7cf7-11eb-861c-41a0bdc4cd94.png)

**Comment by sunandabalu** [comment]
@ShilpaH-SyMetric Is this something you see with recent released upgrade-assistant version too, we have made some bug fixes in this area? https://www.nuget.org/packages/upgrade-assistant/0.2.220602

**Comment by sunandabalu** [comment]
Closing this, feel free to re-open if you see this re-surface.
