### ISSUE TITLE
can upgrade-assistant support to convert VB.net winforms to C# winforms or web application

### ISSUE THREAD

**Issue by ajaybabuthota** [dotnet/upgrade-assistant#315]
can upgrade-assistant support to convert VB.net winforms to C# winforms or web application?

we have an application in VB.net winforms. our goal is to convert to C# web application and migrate to .NET 5 version. Please suggest the best approach.

**Comment by mjrousos** [comment]
Hi @ajaybabuthota, we're working on adding VB support right now. With the next release of Upgrade Assistant, it should be possible to upgrade VB.NET WinForms apps to target .NET 5. They will still be VB WinForms apps after upgrade, though (just targeting .NET 5). If you want to migrate to C# or a web application, those changes will need to be done outside of the tool.
