### ISSUE TITLE
Tool 'upgrade-assistant' failed to install.

### ISSUE THREAD

**Issue by ZiadMadkour** [dotnet/upgrade-assistant#320]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant

![image](https://user-images.githubusercontent.com/2838859/110250934-c2793280-7f86-11eb-8ebd-d3aeff50892b.png)

dotnet --list-sdks
1.1.14 [C:\Program Files\dotnet\sdk]
2.1.521 [C:\Program Files\dotnet\sdk]
2.1.813 [C:\Program Files\dotnet\sdk]
2.2.402 [C:\Program Files\dotnet\sdk]
3.1.112 [C:\Program Files\dotnet\sdk]
3.1.200 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]
3.1.300 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.200 [C:\Program Files\dotnet\sdk]

Edition	Windows 10 
Version	20H2
OS build	19042.844
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by mjrousos** [comment]
This may be related to the NuGet package source mentioned in the warning. Can you try running this command to see if it helps?

`dotnet tool install -g upgrade-assistant --ignore-failed-sources`

**Comment by ZiadMadkour** [comment]
I've got it working by adding `--interactive` and on running the command it opened the browser for my credentials, I logged in with my credentials on the browser it got installed.
Thanks, @mjrousos.
