### ISSUE TITLE
o que é arquivo de solução.

### ISSUE THREAD

**Issue by jh12-ao** [dotnet/upgrade-assistant#330]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by twsouthwick** [comment]
Hi @jh12-ao We'd be happy to investigate any issue you have, but doesn't look like you filled out the error info. I'll close for now, but feel free to reopen with more details if you're still having issues.
