### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#349]
The `Overview` mentions the steps, and their order, that the tool will execute

#342
Changed the order of steps

The phrasing `Update the project file to be an SDK-style project and re-target it to .NET 5.0` does not reflect that these are executed as 2 different steps

https://devblogs.microsoft.com/dotnet/introducing-the-net-upgrade-assistant-preview/#how-does-it-work

**Comment by sunandabalu** [comment]
Good catch, @KSchlobohm . I'll edit the readme to reflect the change.

**Comment by sunandabalu** [comment]
> https://devblogs.microsoft.com/dotnet/introducing-the-net-upgrade-assistant-preview/#how-does-it-work

The blog I guess cannot be edited but we can call this out in the release notes when the change goes out to nuget.org

**Comment by KSchlobohm** [comment]
Thanks @sunandabalu

**Comment by Saibamen** [comment]
Commited in https://github.com/dotnet/upgrade-assistant/commit/51d0b201ff5197f8c2eae20f46b3fae63533fc11 (https://github.com/dotnet/upgrade-assistant/pull/350)
