### ISSUE TITLE
About MSBuild and Visual Studio dependency

### ISSUE THREAD

**Issue by Nadare2012** [dotnet/upgrade-assistant#353]
The prerequisites say that the tool uses MSBuild (which can be installed with Visual Studio) and there is no word that Visual Studio is required. However, the tool looks for the path to Visual Studio and throws an exception if not found. If a tool needs Visual Studio to find MSBuild, can the --msbuild-path option be added, like in try-convert, to remove Visual Studio from dependencies?

**Comment by twsouthwick** [comment]
We should probably update that we require VS. We could try adding an option to say where to look for it, but we need it to help load projects that are being converted. Many old projects require targets files that are installed with VS and fail if we don't have those targets.

**Comment by sunandabalu** [comment]
@twsouthwick will update the wiki with clear instructions for VS / MSBuild

**Comment by sunandabalu** [comment]
Nothing more at this moment to be updated here, closing this.
