### ISSUE TITLE
getting Unknown selection Error after upgrading .Net Framework to .Net 5 using .Net Upgrade Assistant

### ISSUE THREAD

**Issue by Guggs** [dotnet/upgrade-assistant#355]
i am getting Unknown selection Error after upgrading .Net Framework to .Net 5. I am using the Upgrade Assistant. It lists me all Projekt (118) but when it recommends an order to upgrade only 7 are shown. These 7 Projects are upgraded just fine, but then i get an "Unknown selection: ''"-Error when pressing enter to move on.

**Comment by twsouthwick** [comment]
Interesting. Most likely the 7 it recommends are the only ones that are referenced by the entrypoint you selected. Can you share the `log.txt` or at least the error portion there?

**Comment by Guggs** [comment]
Hi i solved it by deleting the upgrade-assistant file and restart it, so i can go on and upgrade the other packages. THX
