### ISSUE TITLE
because the language 'Visual Basic' is not supported.

### ISSUE THREAD

**Issue by gturbeville** [dotnet/upgrade-assistant#357]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 [Failure] Problem loading file in MSBuild workspace Cannot open project 'C:\Users\gturbeville\source\repos\WinccApp\WinccApp.vbproj' because the language 'Visual Basic' is not supported.

**Comment by twsouthwick** [comment]
This is being worked on and some support should be enabled soon. See #270 where we'll be tracking this.
