### ISSUE TITLE
Dependency on Visual Studio or MSBuild?

### ISSUE THREAD

**Issue by prabh-62** [dotnet/upgrade-assistant#361]
## System Info

**OS**: macOS 11.2.3
<img width="183" alt="macOS_bigsur" src="https://user-images.githubusercontent.com/13006107/111550393-610a4e00-8754-11eb-9fdb-dbac51fdc30f.png">

```shell
❯ dotnet --list-sdks
3.1.407 [/usr/local/share/dotnet/sdk]
5.0.201 [/usr/local/share/dotnet/sdk]
6.0.100-preview.2.21155.3 [/usr/local/share/dotnet/sdk]
```

```shell
❯ dotnet msbuild --version
Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.10.0.12601
```

## Questions

- Should a user run [upgrade-assistant](https://github.com/dotnet/upgrade-assistant) tool only on Windows OS or are other operating systems supported as well?
- Is [upgrade-assistant](https://github.com/dotnet/upgrade-assistant) tool dependant on [Visual Studio](https://visualstudio.microsoft.com) or just [MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild)? Which versions of [Visual Studio](https://visualstudio.microsoft.com)/[MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild) are supported?
- Can this tool be leveraged by extensions developed for different IDEs like [Rider](https://www.jetbrains.com/rider/), [Visual Studio Code](https://code.visualstudio.com/)? This would only be possible if there is no dependency on Visual Studio
- I don't have Visual Studio for Mac installed on my machine(I use Rider). Upon running this tool, I received an error message `Unhandled exception: System.PlatformNotSupportedException: COM Interop is not supported on this platform`. Maybe the error message could be improved? 
<img width="1440" alt="upgrade_assitant_mac" src="https://user-images.githubusercontent.com/13006107/111551328-58b31280-8756-11eb-9cc3-4637ec6d00c5.png">

**Comment by mjrousos** [comment]
Yes, Upgrade Assistant is only supported on Windows, currently. In general, the tool is expected to run in an environment that could have built the solution being upgraded (so MSBuild and VS targets needed by the solution are available, NuGet sources are available, etc.).
