### ISSUE TITLE
Upgrade Assistant should tell me to update WCF client generated code (or just do it)

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#363]
Guidance is to replace generated WCF code with new tool to make code that's compatible with .NET Standard
https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x

We should either help the user run this tool or give them information that guides them to running the tool as a follow up step

**Comment by KSchlobohm** [comment]
Same for asmx service references

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi, 
Does upgrade-assistant call svcutil internally and make the changes required for WCF Client side?
