### ISSUE TITLE
An after-upgrade report (csv file perhaps?) should clearly list all changes made and any warnings the user needs to be aware of

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#368]
We already log diagnostic messages to disk, but that log can be a little noisy. We should also generate a report that very clearly lists each update made (and warnings the user should review).

**Comment by mjrousos** [comment]
We will have to spend a little time thinking about what form this should take, but a table seems reasonable with a format like:

| Notification Type | Message | Project | Upgrade Step | Risk
--- | --- | --- | --- | ---
| Change | Project file updated to SDK-style with default SDK | MyLibrary.csproj | TryConvert step | Medium
| Change | Project file updated to SDK-style with web SDK | MyApp.csproj | TryConvert step | High
| Change | Newtonsoft.Json version changed from 6.0.1 to 12.0.3 | MyApp.csproj | Package update step | High
| Warning | Newtonsoft.Json upgraded between major versions! Check for breaking changes | MyApp.csproj | Package update step | High
| Change | appsettings.json file added to project from template | MyApp.csproj | Template inserter step | Low
| Change | `using System.Web;` declaration removed from myClass.cs at line 3 | MyApp.csproj | Source update step | Medium

**Comment by paulomorgado** [comment]
Consider providing SARIF reports.

**Comment by mjrousos** [comment]
Good idea, @paulomorgado

**Comment by ujjwalchadha** [comment]
Tracking this as a part of #460 
@brandonh-msft it's up to you to keep or close this issue
Will use some suggestions from here

**Comment by brandonh-msft** [comment]
Closing as duplicate
