### ISSUE TITLE
Add an option to run over all entry points in a solution or directory

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#369]
In the case of a solution with many test projects, each test project is an entry point and it can be frustrating to have to run the tool repeatedly to upgrade all of those separate projects.

Ideally, there would be a way to upgrade *all* entry-points/projects in a solution or folder structure.

**Comment by twsouthwick** [comment]
My first thoguht is we'd want to structure it so a collection of entrypoints can be selected/submitted, and then the tool would identify the dependency graph of all of them and do the ordering from that graph.

**Comment by sunandabalu** [comment]
If the tool is run against the solution in a non-interactive mode, will it not chew through all the projects in the solution?

**Comment by mjrousos** [comment]
Only those in the entry point's dependency graph. The use case here the customer was asking about was a solution with many test projects, each their own entry point.

**Comment by sunandabalu** [comment]
> My first thoguht is we'd want to structure it so a collection of entrypoints can be selected/submitted, and then the tool would identify the dependency graph of all of them and do the ordering from that graph.

This should work, we need to make the entry-point param to be a collection for non-interactive mode too.
