### ISSUE TITLE
Upgrade Assistant should move MsTest projects to MsTestV2

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#372]
* Remove the assembly reference for Microsoft.VisualStudio.QUalityTools.UnitTestFramework
* Add package reference to MsTest.TestFramework (MsTest V2)
* Add package reference to Microsoft.Net.Test.Sdk
* Add package reference to MSTest.TestAdapter
* Add package reference to coverlet.collector
* Set TFM to net5.0 (not netstandard2.0)

**Comment by paulomorgado** [comment]
For tests that are already using MsTest, right?

Not changing XUnit or NUnit tests to MsTest2, right?

**Comment by KSchlobohm** [comment]
@paulomorgado , correct. This is only for test projects that are already using MsTest. Thanks for helping to clarify.
