### ISSUE TITLE
UpgradeReadyCheck should ask if you want to proceed

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#377]
Each UpradeReadyCheck should ask if you want to proceed rather than saying no. This is an improvement to the flow for unsupported project types and features.

Exmples include:
* ASP.NET Web Forms
* VB
  * ASP.NET VBHTML
  * Support for the My namespace

**Comment by paulomorgado** [comment]
Isn't the `My` namespace back, @KathleenDollard?

**Comment by KSchlobohm** [comment]
@paulomorgado , In this situation I'm referring to things that would leave a project in a situation with build errors after running the upgrade-assistant. The goal is to give a choice to make changes before applying the upgrade assistant to their project or after upgrading.
