### ISSUE TITLE
Support multi targeted dependencies

### ISSUE THREAD

**Issue by davidda** [dotnet/upgrade-assistant#379]
My legacy ASP.NET project has a dependency on a library project that is multi-targeting:
`<TargetFrameworks>netstandard2.1;net47</TargetFrameworks>`

The tool fails with:
_Expected project to have exactly one TargetFramework property. Found 0 TargetFramework properties for project ..._

**Comment by mjrousos** [comment]
Good find, @dividda. We don't support upgrading multi-targeted projects yet, but we should be able to upgrade projects that *depend* on multi-targeted projects. This will be a good one to fix.
