### ISSUE TITLE
Ensure Directory.Build.* properties are read by tools

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#387]
From https://github.com/dotnet/upgrade-assistant/pull/383#discussion_r602120477

See here for details of feature: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019

This should be supported, but we don't have anything actually verifying that

**Comment by paulomorgado** [comment]
There's a more than just `Directory.Build.*`. There's also `Custom*`.
