### ISSUE TITLE
Ignore disabled NuGet sources

### ISSUE THREAD

**Issue by Maetis** [dotnet/upgrade-assistant#396]
Hi,

I had a issue with the step "Clean up NuGet package references" because the process was unable to reach https://api.nuget.org/v3/index.json for proxy authentification reason. 

But I was confuse because this source was disabled in my configuration. 

So I tried to remove this source with the following command: `dotnet nuget remove source nuget.org`

I relaunched upgrade-assistant and the step passed.

Maybe the class [PackageLoader](https://github.com/dotnet/upgrade-assistant/blob/main/src/components/Microsoft.DotNet.UpgradeAssistant.MSBuild/PackageLoader.cs) (line 30) should ignore disabled sources.

**Comment by sunandabalu** [comment]
@Maetis good catch, I have a PR to fix this.
