### ISSUE TITLE
Projects aren't always restored when retrieving dependencies

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#402]
In order to identify transitive dependencies, we require that projects are restored as we get that info from the lock file. If not, we throw. We have attempted to add in restore steps to ensure that occurs, but the better fix would be to do it for the caller if it is not done. The error end users see is:

```
[11:17:03 ERR] Project is not restored: [Path].csproj
```

Naively, this would be as simple as updating to the following signature:

```csharp
Task<INuGetReference> GetNuGetReferences(CancellationToken token);
```
And call `IPackageRestorer.RestoreAsync` if the lockfile is not present.  However, this has a cascading effect on methods as it then requires callers to be async. This expands out to needing to make the following async:

- `UpgradeStep.IsApplicableImpl`
- `IComponentIdentifier.GetComponents`
- `ITargetTFMSelector.SelectTfm`

This ends up being quite viral. This should probably still be done, but I wanted to create an issue and get feedback before making the changes.

**Comment by mjrousos** [comment]
Yea, this is a tricky one. I agree with you that it should probably be done, but some of those callers (at least `IsApplicableImpl` and `SelectTfm`) get called quite a bit and it's nice to have them execute quickly. If `RestoreAsync` could return synchronously when there's already a valid lock file and only run asynchronously when a restore is actually needed, that would be ideal. I know that NuGet won't actually pull packages down unless it's needed, but spinning up the `dotnet` process and reloading the project is still a bit slow even if the restore itself doesn't do anything.

Now that all project file access is going through our interfaces, the best option might be to track whether packages need restored or not in `MSBuildProject` or `MSBuildProject.File`. We could restore packages when projects are loaded and then store some flag indicating that's already done. Then, certain `IProject` operations (updating TFM, updating references, etc.) would either re-restore or clear that flag so we know a restore is needed in the future. Even better, making those sorts of changes could kick off a restore task but not await it and `GetNuGetReferences` could await the restore task when it's called.

There are a couple instances when project files get updated without using our interfaces (when try-convert runs, for example), but those code paths should already be calling `ReloadWorkspaceAsync` so we can just make sure that that method re-starts the restore task.

Yea, I kind of like that. If we have loading a project, reloading a project, or making certain changes to a project kick off a restore task, then `GetNuGetReferences` can await that task and we'll know that packages have been restored for `GetNuGetReferences` but *usually* `GetNuGetReferences` will execute synchronously. That will cause async patterns to spread virally, but that seems ok.

**Comment by KSchlobohm** [comment]
In the scenario where this happened they were in the "experiment" phase of trying out the tool. During the process, they were skipping steps, and stopping at different phases to see what was done and whether or not it would compile/run.

As you can imagine, this involved multiple passes through the tool using the same project file just to see what the different paths were. As part of that process the rollback was manual, I think the steps to rollback were.

1. Delete the project folder
2. Rename the backup folder
3. Delete the ".upgrade-assistant" file that was in the backup folder
4. Delete the bin/obj folders

Maybe we should consider a more formal rollback process?

**Comment by twsouthwick** [comment]
@KSchlobohm that may make sense as a separate issue.

@mjrousos that's exactly what I was thinking implementation wise. We already throw if things are not restored, so we'd just use that logic to determine if we need to restore. Definately don't want to kick off while processor we don't need to.
