### ISSUE TITLE
Translate Code Fixers to VB

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#405]
Existing code fixers and analyzers are syntax level which enables them to operate on code that does not compile but limits them from supporting VB.

- [ ] AllowHtmlAttributeAnalyzer
- [x] BinaryFormatterUnsafeDeserializeAnalyzer
- [ ] DiagnosticAnalyzerExtensions
- [ ] FilterAnalyzer
- [ ] HelperResultAnalyzer
- [ ] HtmlHelperAnalyzer
- [ ] HtmlStringAnalyzer
- [ ] HttpContextCurrentAnalyzer
- [ ] HttpContextIsDebuggingEnabledAnalyzer
- [ ] ResultTypeAnalyzer
- [ ] UrlHelperAnalyzer
- [ ] UsingSystemWebAnalyzer

**Comment by twsouthwick** [comment]
Some things to identify here:

- Which ones are fine running while still targeting .NET Framework? Most in this list can't, but we should keep it in mind as those can use the symbol layer ie BinaryFormatterUnsafeDeserializeAnalyzer should be fine running there
- Those that should operate at a syntax layer should be using `DocumentEditor`/`SolutionEditor`/`SyntaxGenerator`/etc as much as possible to make language-agnostic analyzers/code fixers.
