### ISSUE TITLE
As a user, I can choose to migrate to either LTS, Current, or Preview

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#41]
Added Preview to consider supporting the preview release for the TFM (in this case .NET 6).

**Comment by sunandabalu** [comment]
Does this estimate include adding support for Preview as well?

**Comment by twsouthwick** [comment]
The TFM selection process for .NET 6 for instance, is the same as .NET 5. I've added an item to include allowing selection of this property
