### ISSUE TITLE
Fix `IsApplicable` naming confusion

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#427]
In Upgrade-Assistant, there are two separate concepts both named `IsApplicable`:

1. Upgrade steps have an 'IsApplicable' API which should be a fast check that can be run without initializing the step to determine whether the step even applies to the given context. It's used for deciding which upgrade steps to show the user.
2. IConfigUpdater/IUpdater have an 'IsApplicabe' API which is used to decide whether the updater needs run in a given context. The upgrade step using the updater will typically call this API during its initialization.

This is confusing because in case (1) the checks should be fast and high-level whereas in the second case it's more like an upgrade step's initialization and it's ok to check project specifics. We should rename one of these (probably the second one) to make it clearer that these APIs are different despite the unfortunate naming overlap.

Also, I'd like to review whether UpgradeStep.IsApplicableAsync really needs to be async. It was always meant to be a fast check for whether or not to display a step that is run frequently. If possible, it would be good to change it back to synchronous to encourage implementers to have speedy implementations.

**Comment by mgoertz-msft** [comment]
No longer applicable.
