### ISSUE TITLE
Long project names prevent using default visual studio repository location

### ISSUE THREAD

**Issue by oteinone** [dotnet/upgrade-assistant#429]
### Describe the bug
Some paths are nested too deep when building the solution in visual studio

### To Reproduce
1. Clone the repo to e.g. c:\users\edwardcontoso\source\repos\upgrade-assistant
2. Open in visual studio
3. Try to build

### Exceptions (if any)
`The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

### Further technical details
Example file that was nested too deep: `C:\Users\otto\source\ext-repos\upgrade-assistant\artifacts\obj\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.Package\Debug\netstandard2.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.Package.GeneratedMSBuildEditorConfig.editorconfig`

**Comment by twsouthwick** [comment]
Can you enable long file support?

**Comment by oteinone** [comment]
I definitely can but I just moved the whole thing under c:\Code to get going. Just thought to report it if you feel like making the project more accessible. Feel free to close this if it doesn't feel relevant.

**Comment by sunandabalu** [comment]
We can update the readme to call out enabling long path support, no other action needed here.

**Comment by sunandabalu** [comment]
#465 added the note to the contributing guide, closing this issue.
