### ISSUE TITLE
Default namespace on VB should not be set if not already set

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#430]
If `<RootNamespace>Microsoft.DotNet</RootNamespace>`, and you have a `namespace Microsoft.DotNet` in the project, the type gets the namespace `Microsoft.DotNet.Microsoft.DotNet` namespace

**Comment by sunandabalu** [comment]
This should be addressed by this PR in try-convert - https://github.com/dotnet/try-convert/pull/397/files

**Comment by KSchlobohm** [comment]
I think this could have been a bug with `try-convert` but I'm not able to repro the issue.

When I run `upgrade-assistant` on a vbproj for a Web API project (with &lt;RootNamespace&gt; set as an empty string) I see that it remains an empty string during step 2 (Convert project file to SDK style).

*snippet of net48 vb web project using SDK style*
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace></RootNamespace>
    <AssemblyName>WebApplication1</AssemblyName>
  </PropertyGroup>
...
```

And, when I finish the upgrade I see the same behavior

*snippet of finished upgrade targetting net5.0*
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>
    </RootNamespace>
    <AssemblyName>WebApplication1</AssemblyName>
  </PropertyGroup>
```

Observed no errors with the upgrade process.
![image](https://user-images.githubusercontent.com/23503973/118576544-59fcbd80-b74e-11eb-8fd6-ce928b9e07fd.png)

Also tried with a vbproj where the rootnamespace element had been deleted but that did not repro the issue.

**Comment by sunandabalu** [comment]
Assigning to @twsouthwick to verify and close

**Comment by twsouthwick** [comment]
Customer hasn't seen it recently. Closing for now.
