### ISSUE TITLE
Add a step to multitarget if adding .NET 5.0 as a target

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#431]
If we end up adding .NET 5.0 as a target (or anything non-.NET Standard), then we should provide a step that would expand that out to `<TargetFrameworks>net5.0;net472</TargetFrameworks>` or whatever the original version was.

In order to do this, we'd probably want to insert a property in the project file similar to `<OriginalTargetFramework>net472</OriginalTargetFramework>` and use that to track in case the tool is restarted.

**Comment by mjrousos** [comment]
If the UpdateTFM step is changed to just add `<TargetFrameworks>net5.0;net472</TargetFrameworks>` directly, then we wouldn't need the extra property. Either way, though, this will be a valuable feature; thanks for opening the issue!

**Comment by mjrousos** [comment]
Also, we probably don't want to multi-target web apps.
