### ISSUE TITLE
Persisting knowledge about non-default backup location

### ISSUE THREAD

**Issue by oteinone** [dotnet/upgrade-assistant#435]
## Summary

As #293 states, it is probably a bad idea to back up the solution inside the git folder. The ability to select another location for the backup helps but unfortunately the backup location is not persisted. 

## Motivation and goals

- Being able to store backups outside project/solution folder is good
- Having to do backups multiple times is bad

## Detailed design

The location could be persisted in `.upgrade-assistant` file and `BackupStep.InitializeImplAsync` could query for this location instead of the default location if it has been set.

**Comment by sunandabalu** [comment]
@oteinone This makes sense, feel free to make a PR we will review it.

**Comment by oteinone** [comment]
@sunandabalu Added PR, please let me know if something needs improving :)

**Comment by twsouthwick** [comment]
This is merged in now. Thanks for the PR!
