### ISSUE TITLE
Automatic selection of entry point

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [dotnet/upgrade-assistant#450]
Hi,
When there is only entry point, is it possible to automatically identify it, skip the "Select an entry point" step and go straight to the step of displaying recommended order to upgrade projects?

**Comment by mjrousos** [comment]
If there's only one project in the solution (or if the tool is run on a project directly) the entry point step should be skipped as you describe. Is this not the behavior you're seeing?

**Comment by twsouthwick** [comment]
@vijaya-lakshmi-venkatraman You mention "only entry point" and "to upgrade projects" so I'm wondering what you understand about the entrypoints. From the tool's perspective, any project is a viable entrypoint. It may be an application, a library you want to ship, or just the one project you care about getting converted to .NET 5/.NET Standard at this point.

**Comment by vijaya-lakshmi-venkatraman** [comment]
@mjrousos Sorry, I am yet to check how the tool behaves when there is only one project in the solution. 

@twsouthwick  My understanding of entry point was more in terms of the application entry point. Thanks for the clarification. Now I get the tool's pov. I will close this thread.
