### ISSUE TITLE
Backup step doesn't work for multi-project solutions

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#462]
### To Reproduce

1. Run Upgrade Assistant on a solution with multiple entry points. Choose one of the entry points and upgrade using all defaults.
2. Run Upgrade Assistant a second time on the sample solution and choose a different entry point. **The tool will _not_ back up this project** because it stores the backup location for the solution from the previous run and believes backup is complete (since a project *is* backed up there).

**Comment by mjrousos** [comment]
I have a fix available for this, but am running into some strange (unrelated) test failures that I want to sort out before creating a PR.

**Comment by twsouthwick** [comment]
It'd be great to fix where someone skips a backup that that persists as well. Not sure if that would be in scope, though

**Comment by mjrousos** [comment]
Agreed. That's a bit of an orthogonal issue, but they're both related to making the backup step's persistence better. I'll see about addressing both.
