### ISSUE TITLE
Enable extensions to load zip files

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#490]
## Summary

Extensions currently work best when given a path. This however, is not great for redistribution of extensions. We should have support for an archive format (ie zip) that could be used as well.

## Motivation and goals

Right now, distribution of an extension requires it to be a directory, but it would simplify things if it could just be an archived format.

## In scope

- Support for zip format

## Out of scope

- Distribution of the zip files

## Risks / unknowns

There may be issues with loading assemblies from these directly, so they may need to be expanded to disk. If so, zip bombs may be an issue.

**Comment by mjrousos** [comment]
I've tried to design the extension system so that this will work without actually expanding the archives. Of course, there may be surprises as we implement. :)
