### ISSUE TITLE
Replace System.Web.HttpCookieCollection usage

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#495]
Investigate the feasibility of replacing System.Web.HttpCookieCollection usage with Microsoft.AspNetCore.Http.IRequestCookieCollection and Microsoft.AspNetCore.Http.IResponseCookies (for request and response scenarios, respectively).

**Comment by twsouthwick** [comment]
This is available from the Microsoft.AspNetCore.SystemWebAdapters package
