### ISSUE TITLE
After successful upgrade execution clean up undesired changes

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/upgrade-assistant#510]
## Summary

I propose that after a successful upgrade has been executed, that only required changes / files remain. Currently, this is not the case. For example, after running an upgrade:

- There is a _.upgrade-assitant_ JSON file at the root, this file is no longer needed and should be deleted
- There are `<PackageReference>` entries for upgrade specific analyzers, these should be removed

```xml
<PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.2.222702">
      <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

## Motivation and goals

I understand that as part of the execution of the upgrade, peripheral changes and files are required. But after, these should be removed or undone.

## In scope

Add a clean up routine which is able to spin through projects removing package references that were added, and delete any files that were intended to be temporary.

## Out of scope

Nothing comes to mind here.

## Risks / unknowns

None.

## Examples

I ran the upgrade assistant with a project that was targeting `netcoreapp3.0`. It upgrade to `net5.0`, but left a _.upgrade-assitant_ file at the root of the .sln directory, and left a `<PackageReference>` entry - which should be no longer needed.

Somewhat related to #386, but more detailed and larger scope as it proposes a clean up routine.

**Comment by mjrousos** [comment]
Removing .upgrade-assistant may make sense. @twsouthwick, is there anything in that file that needs to persist after upgrade is finalized?

The analyzers being left is intentional, though. In the (hopefully near) future, we're planning to include analyzers in that package that will alert users to APIs that they need to manually migrate away from that the tool wasn't able to handle automatically. Having the package included in the project will allow us to add diagnostics for these sorts of scenarios.

**Comment by sunandabalu** [comment]
Making the finalize solution step to provide an option for the user to confirm that its Ok to clean up all traces of upgrade-assistant from the solution, and remove if user chooses so would make sense. @IEvangelist Feel free to create a PR for the solution mentioned here, we will review it.

**Comment by IEvangelist** [comment]
Hi friends - @sunandabalu @mjrousos and @twsouthwick - please see #522

**Comment by sunandabalu** [comment]
#522 is merged, closing this

**Comment by HughWarrington** [comment]
> The analyzers being left is intentional, though. In the (hopefully near) future, we're planning to include analyzers in that package that will alert users to APIs that they need to manually migrate away from that the tool wasn't able to handle automatically. Having the package included in the project will allow us to add diagnostics for these sorts of scenarios.

@mjrousos are you saying the reference to the analyzers should be left in the upgraded project for all time? Couldn't they be removed after the upgrade process is completed, and assuming none of them are being triggered?
