### ISSUE TITLE
As a user, I can run Upgrade Assistant on a mac

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#550]

**Comment by sshquack** [comment]
Please support this for macOS. Here is the error message I get trying to upgrade from a Framework 4.8 to .net 5

```
❯ upgrade-assistant ./TaskService/TaskService.csproj
This tool is not supported on non-Windows platforms due to dependencies on Visual Studio.
```

Environment info
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by AndiRudi** [comment]
Sadly, I just discovered the same error message. I feel everything `.net` should not rely anymore on Visual Studio.

**Comment by ramedey** [comment]
+1

**Comment by twsouthwick** [comment]
I'm interested in what your use case is. Can you share what project type you're coming from and where you want to go with it? 

The tool was initially designed to move people from ASP.NET to ASP. NET Core which requires VS because that's where the sdk was available. There are other workloads we're exploring that don't require VS, but that is where that limitation comes from.

**Comment by AndiRudi** [comment]
> The tool was initially designed to move people from ASP.NET to ASP. NET Core which requires VS because that's where the sdk was available. There are other workloads we're exploring that don't require VS, but that is where that limitation comes from.

I am not sure what you mean by that. We have some projects written in .net (either .net framework 4.x or .net core 3.1) and I wanted an easy automated way to update them to .net 5 or 6 on my mac.

**Comment by twsouthwick** [comment]
The ASP. NET tool chain was and is only available on Windows. Since we need the toolchain available in order to do the conversion, we initially limited it to Windows. Right now, the main focus of the tool is. NET Framework to. NET Core/6. However, in order to support Xamarin to Maui, we will need to figure out the non-windows story.

Have you been building the. NET Framework apps on non - Windows machines? If so, what toolchain are you using for that?

**Comment by AndiRudi** [comment]
For .NET Framework 4.x I was using Visual Studio for Mac / Mono at the time. I am not so much interested in an upgrade tool for that anymore as we have already moved all projects to .net core 3.1. (But there might be other people that are interested in that. If that only works on windows, then it's fine I guess to use a windows machine)

But conversion from .net 3.1 upwards should be possible on all operating systems if you ask me.

**Comment by github4es** [comment]
+1.  Need Mac Support

**Comment by Lancelotbronner** [comment]
My main use case is migrating projects to SDK-style

**Comment by Lancelotbronner** [comment]
Since there are plenty of upgrade steps which don't rely on the ASP.NET framework, is there a way upgrade-assistant could restrict applied upgrade steps based on the platform rather than refuse to work entirely?

**Comment by giuseppenovielli** [comment]
+1. Need Mac Support

**Comment by ShareDev** [comment]
Why macOS is not supported???

**Comment by janusw** [comment]
@twsouthwick Is this issue fixed by #1409, or is there anything left to do?

**Comment by janusw** [comment]
With .NET SDK 7.0.306, it seems that I can at least install the upgrade assistant on Mac OS 13.4.1:

```
% dotnet tool install -g --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources upgrade-assistant
You can invoke the tool using the following command: upgrade-assistant
Tool 'upgrade-assistant' (version '0.5.30') was successfully installed.
% upgrade-assistant --version
0.5.30.21767
```

**Comment by janusw** [comment]
However, it seems that the `analyze` command is missing.

```
% upgrade-assistant --help   
USAGE:
    upgrade-assistant [OPTIONS] <COMMAND>

EXAMPLES:
    upgrade-assistant upgrade <PROJECT_PATH>
    upgrade-assistant upgrade <PROJECT_PATH> --operation Inplace --targetFramework net6.0
    upgrade-assistant upgrade <PROJECT_PATH> --operation SideBySide --targetFramework LTS --destination <NEW_PROJECT_NAME_OR_PATH>

OPTIONS:
    -h, --help       Prints help information   
    -v, --version    Prints version information

COMMANDS:
    upgrade    Upgrade project or its features. This command lets you pick upgrade options and guides through upgrade process


% upgrade-assistant analyze MyProject.sln

Error: Unknown command 'analyze'.

       analyze MyProject.sln
       ^^^^^^^ No such command
```

**Comment by jstedfast** [comment]
@janusw The latest version of the upgrade assistant had the analyze command removed (it is a 100% rewrite since 0.4.x which is what is in this GitHub repo).

The new version does support macOS but it can only upgrade dotnet core projects. It cannot upgrade .netframework projects (which unfortunately includes Xamarin projects).

This is largely because on macOS, the .netframework msbuild assemblies are not really compatible with dotnet core and so my efforts to get this to work over the past week or so since I started digging into this has been wrought with TypeLoadExceptions. 

I'm investigating a solution that will attempt to circumvent msbuild APIs with a raw XML compatibility layer in the hopes that this will at least "mostly" work, but honestly, if you need to upgrade a .netframework project, I'd recommend doing it on Windows especially if you are under any sort of time constraints.

**Comment by jstedfast** [comment]
The other option, I suppose, is to  use the last available 0.4.x version.

**Comment by janusw** [comment]
> @janusw The latest version of the upgrade assistant had the analyze command removed (it is a 100% rewrite since 0.4.x which is what is in this GitHub repo).

So why is the latest version (0.5) not in this repo? Are you not planning to open-source it?


> The new version does support macOS but it can only upgrade dotnet core projects. It cannot upgrade .netframework projects (which unfortunately includes Xamarin projects).

Wait. Xamarin is based on Mono, not the classic .NET framework, right?


> This is largely because on macOS, the .netframework msbuild assemblies are not really compatible with dotnet core and so my efforts to get this to work over the past week or so since I started digging into this has been wrought with TypeLoadExceptions.
> 
> I'm investigating a solution that will attempt to circumvent msbuild APIs with a raw XML compatibility layer in the hopes that this will at least "mostly" work, but honestly, if you need to upgrade a .netframework project, I'd recommend doing it on Windows especially if you are under any sort of time constraints.

My main concern is getting a larger Xamarin.Forms project migrated to MAUI. I'd prefer doing it in my main development environment, which is MacOS, but if there's no other way I can certainly do the migration on Windows (and then go back to development on Mac).

In fact I just tried the upgrade assistant on Mac with a .NET Standard 2.0 project (which is part of a larger Xamarin.Forms solution), and got:
```
Complete: 78 succeeded, 1 failed, 120 skipped.
```
The failure seems to be some `ArgumentException` in `MauiProjectTemplateItemTransformer`. Is it worth to open an issue about this here, or should I better try the Xamarin->MAUI migration on Windows in the first place?

**Comment by janusw** [comment]
> In fact I just tried the upgrade assistant on Mac with a .NET Standard 2.0 project (which is part of a larger Xamarin.Forms solution), and got:
> 
> ```
> Complete: 78 succeeded, 1 failed, 120 skipped.
> ```
> 
> The failure seems to be some `ArgumentException` in `MauiProjectTemplateItemTransformer`. Is it worth to open an issue about this here, or should I better try the Xamarin->MAUI migration on Windows in the first place?

Ok, tried the exact same things on Windows now (`upgrade-assistant.exe upgrade myproj.csproj --operation Inplace --targetFramework net7.0`),  which gives me (with the same version `0.5.30.21767`:

```
Complete: 79 succeeded, 0 failed, 109 skipped.
```

So the failure seems to be Mac-specific and does not occur on Windows.

Bottom line: I'll simply do both: open an issue for the failure on Mac, and continue the migration on Windows.

**Comment by janusw** [comment]
> > The failure seems to be some ArgumentException in MauiProjectTemplateItemTransformer. Is it worth to open an issue about this here, or should I better try the Xamarin->MAUI migration on Windows in the first place?
> 
> I'm not sure how to submit bug reports for the new Upgrade Assistant, but if you file a bug here in this repo and ping me, I'll look into it. I would probably suggest checking if it works on Windows if you can. If it's broken on macOS but works on WIndows, that's something I want to know because my goal is to make this work on macOS.
> 
> > So the failure seems to be Mac-specific and does not occur on Windows.
> 
> Then I want to know about the bug so I can fix it :-)

See #1505.

**Comment by jstedfast** [comment]
Good news: I've got this more-or-less working beautifully on macOS now. Just a few quirks to iron out.
