### ISSUE TITLE
As a user, project file properties/item groups are transformed from Xamarin to .NET Maui

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#552]
There may be properties and/or itemgroups that must be transformed from Xamarin to .NET Maui. First, we should identify what those are, and then teach UA to transform it.

**Comment by Sweekriti91** [comment]
everything add `<UseMaui>true</UseMaui>`

MAUI Head project == adds uses Maui and that stuff

iOS/Droid projects == add 
`<RuntimeIdentifier Condition="$(TargetFramework.Contains('-ios'))">iossimulator-x64</RuntimeIdentifier>` 
or 
`<UseInterpreter Condition="$(TargetFramework.Contains('-android'))">True</UseInterpreter>`
