### ISSUE TITLE
Incorrect documentation on dotnet.microsoft.com

### ISSUE THREAD

**Issue by glyph-se** [dotnet/upgrade-assistant#563]
I just tried the tool for the first time but had problems getting it to work. After a while I discovered that the documentation on  https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant is outdated / incorrect

The command for running the upgrade-assistant is specified as
`upgrade-assistant <MySolution.sln>`

But I never got this to work. The example command in the [README](https://github.com/dotnet/upgrade-assistant#installation-steps) in this repo says to use `upgrade-assistant upgrade <Path to csproj or sln to upgrade>` which is also what the command line help suggest. Note the added **upgrade** parameter.

I would have created a PR for the documentation myself, but I was unable to find that in this repo.

```
F:\git\modules>upgrade-assistant Modules.sln
Required command was not provided.
Unrecognized command or argument 'Modules.sln'

 -----------------------------------------------------------------------------------------
- Microsoft .NET Upgrade Assistant v0.2.227701+3e878899ae39105a278847a94a7c48f458cada83 -
-----------------------------------------------------------------------------------------

Makes a best-effort attempt to upgrade .NET Framework projects to current, preview or LTS versions of .NET.

This tool does not completely automate the upgrade process and it is expected that projects will have build errors after the tool runs. Manual changes will be required to complete the upgrade to .NET 5.

This tool's purpose is to automate some of the 'routine' upgrade tasks such as changing project file formats and updating APIs with near-equivalents in the selected target framework. Analyzers added to the project will highlight the remaining changes needed after the tool runs.

Usage:
  upgrade-assistant [options] [command]

Options:
  --version       Show version information
  -?, -h, --help  Show help and usage information

Commands:
  upgrade <project>
```

**Comment by sunandabalu** [comment]
@cathysull Is this something you can help with?

**Comment by sunandabalu** [comment]
@glyph-se The change to the usage was recently changed and is called out as breaking change in the Changelog of the recent release - https://github.com/dotnet/upgrade-assistant/blob/main/CHANGELOG.md#breaking-change. The docs.microsoft.com has not been updated in a while, thanks for bringing to our attention on that. @cathysull could you help in getting the docs site updated?

**Comment by glyph-se** [comment]
First time I tried the tool so I didn't check the release notes or changelog. Heard about it on Microsoft Build and wanted to give it a try to see how it worked on our code base.

Anyway, now you know the docs need an update :-)

Thanks!

**Comment by cathysull** [comment]
@glyph-se thanks for letting us know the instructions over there are out-dated! I just submitted PRs to get those instructions updated. Thank you!

**Comment by cathysull** [comment]
We just got the content updated on the microsoft.com tutorial pages. Thanks everyone!
