### ISSUE TITLE
Install issue from dotnet-tools NuGet feed

### ISSUE THREAD

**Issue by Jojoshua** [dotnet/upgrade-assistant#566]
I was having a problem doing the normal install because direct nuget access is blocked so I tried the alternative method referencing the dotnet-tools NuGet feed. This also wasn't successful but I noticed no reference to upgrade assistant in the json

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

Can someone confirm this method still works? Could this tool be included in vs2019?

**Comment by sunandabalu** [comment]
@Jojoshua There are instructions here on how to install from either of the feeds - https://github.com/dotnet/upgrade-assistant#installation-steps

Could you provide details on specific steps you are doing to install?

**Comment by Jojoshua** [comment]
@sunandabalu I tried `dotnet tool install -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
`  but I get NU1801: Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by sunandabalu** [comment]
@Jojoshua Unfortunately I'm unable to repro the error you are seeing installing from the dotnet-tools feed even from a non-corp-creds linked VM that I created. :( Probably you have some proxy setting in your nuget.config that is blocking the package sources, since you mentioned nuget feed being blocked?

**Comment by Jojoshua** [comment]
@sunandabalu thank you for looking into this. Yes my enterprise environment is a bit complicated. I tried pulling this into our SonataType nexus repository and pointed the installer to its json url but it didn't work most likely because Nexus repository needs authentication. Is there a way to side load this if I had the nupkg file from a NuGet source?

**Comment by sunandabalu** [comment]
yes you can do a local dotnet tool install once you have the nupkg

**Comment by mmitche** [comment]
@Jojoshua You should be able to load it from a local folder by using that path with `--add-source` too

**Comment by Jojoshua** [comment]
Thanks the local install worked great.
