### ISSUE TITLE
Get Started missing parameter

### ISSUE THREAD

**Issue by SixOThree** [dotnet/upgrade-assistant#568]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant#
Operating System: windows

upgrade-assistant <MySolution.sln>
should probably be
upgrade-assistant upgrade<MySolution.sln>

**Comment by sunandabalu** [comment]
@SixOThree Thanks for bringing this to our attention, we have #563 tracking the update to documentation in dotnet.microsoft.com. Closing this a dupe.
