### ISSUE TITLE
Running against solution not upgraded all the projects

### ISSUE THREAD

**Issue by prabuwco** [dotnet/upgrade-assistant#574]
### Describe the bug
The upgrade-assistant tool which runs against the solution file does not pick up all the projects for an upgrade. out of 70 projects only a few updated and others left intact.

### Further technical details
- Windows version -10 64-bit
- Include the output of `dotnet --list-sdks`
- 3.1.201 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
0.2.227701+3e878899ae39105a278847a94a7c48f458cada83

**Comment by sdipiazzactr** [comment]
We have a similar issue. Our solution has 200+ projects, but most of these are loaded at runtime; they are not directly referenced from the main exe. The upgrade assistant only lists the direct references to the entry point; it is not clear how to get it to upgrade the rest of the projects in the solution.

**Comment by sunandabalu** [comment]
> We have a similar issue. Our solution has 200+ projects, but most of these are loaded at runtime; they are not directly referenced from the main exe. The upgrade assistant only lists the direct references to the entry point; it is not clear how to get it to upgrade the rest of the projects in the solution.

@sdipiazzactr You can specify `--entry-point` option with a list of projects or wildcard `*` to pick all projects for upgrade-assistant to process
