### ISSUE TITLE
Target framework dropdown is disabled with empty value after upgrade

### ISSUE THREAD

**Issue by prabuwco** [dotnet/upgrade-assistant#575]
### Describe the bug
Upgrade assistant converted the project to SDK style (from .netframework 4.7.1) to netstandard2.0 but Target Framework drop down is disabled with empty in the properties window.

The project file
![image](https://user-images.githubusercontent.com/71254294/120475248-65d0bc80-c3a9-11eb-948c-a8953ec5ac4e.png)

in properties window
<img width="484" alt="empty" src="https://user-images.githubusercontent.com/71254294/120474937-112d4180-c3a9-11eb-8d86-f86f2c8225c5.png">

### Further technical details
- Windows version 10 (64-bit)
- Include the output of `dotnet --list-sdks`
  - 3.1.201 [C:\Program Files\dotnet\sdk]
  - 5.0.202 [C:\Program Files\dotnet\sdk]
  - 5.0.203 [C:\Program Files\dotnet\sdk]
  - 5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  - 6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
  - 0.2.227701+3e878899ae39105a278847a94a7c48f458cada83

**Comment by rlrcstr** [comment]
Still having this issue. Is there a known work-around?

**Comment by abpiskunov** [comment]
Please try latest Upgrade Assistant in Visual Studio or CLI, it was redesigned and now behaves differently.
