### ISSUE TITLE
Target framework is empty default after upgrade

### ISSUE THREAD

**Issue by prabuwco** [dotnet/upgrade-assistant#576]
### Describe the bug
The project is converted to SDK style but the Target Framework drop-down is by default empty and need to manually pick the framework
The project file
![image](https://user-images.githubusercontent.com/71254294/120476164-8ea58180-c3aa-11eb-922f-625b3c840d9f.png)
The properties window
<img width="441" alt="emtybutok" src="https://user-images.githubusercontent.com/71254294/120476214-9bc27080-c3aa-11eb-9246-9aa1b4e897c2.png">
 

### Further technical details
- Windows version 10 (64-bit)
- Include the output of `dotnet --list-sdks`
  - 3.1.201 [C:\Program Files\dotnet\sdk]
  - 5.0.202 [C:\Program Files\dotnet\sdk]
  - 5.0.203 [C:\Program Files\dotnet\sdk]
  - 5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  - 6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
  - 0.2.227701+3e878899ae39105a278847a94a7c48f458cada83

**Comment by abpiskunov** [comment]
Please try latest Upgrade Assistant in Visual Studio or CLI.
