### ISSUE TITLE
The target framework is not consistent in all projects of a solution

### ISSUE THREAD

**Issue by prabuwco** [dotnet/upgrade-assistant#577]
### Describe the bug
I ran upgrade-assistant on 60 projects of different types (class library and exe - netframework 4.7.1) part of the same solution but at the end, projects are converted between with the three targets - netstandard2.0, net5.0-windows and net5.0. Why it is not consistently pick the desired target net5.0? And I don't see any pattern of picking the target as some class libraries are netstandard2.0 while some are net5.0-windows 

lib1
![image](https://user-images.githubusercontent.com/71254294/120477450-1213a280-c3ac-11eb-8a96-b367cf7784cd.png)
lib 2
![image](https://user-images.githubusercontent.com/71254294/120477528-26f03600-c3ac-11eb-8f29-c0efbb89c6d4.png)

### Further technical details
- Windows version 10 (64-bit)
- Include the output of `dotnet --list-sdks`
  - 3.1.201 [C:\Program Files\dotnet\sdk]
  - 5.0.202 [C:\Program Files\dotnet\sdk]
  - 5.0.203 [C:\Program Files\dotnet\sdk]
  - 5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  - 6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
  - 0.2.227701+3e878899ae39105a278847a94a7c48f458cada83`

**Comment by prabuwco** [comment]
Thanks @jdmeer 
I can understand the logic behind choosing the framework. I have checked it in the projects I ran and you are right :)

**Comment by sunandabalu** [comment]
> In my experience it prefers NETStandard2.0 but will pick NET5 if you have a reference to system.web and will pick NET5-windows if you have a reference to system.windows.forms.
> 
> I'm sure there a many more rules like this, does anyone know if they're documented somewhere?
> 
> It'd be really helpful if you could tell the tool which framework you'd like and then tell you why that isn't possible if necessary.

@jdmeer Your explanation is spot on, Thanks! We have opened #718 for adding more intentional logging on why a specific TFM was chosen.
