### ISSUE TITLE
Project is not converted to SDK style as reported in the output

### ISSUE THREAD

**Issue by prabuwco** [dotnet/upgrade-assistant#578]
### Describe the bug
The output says the project is converted to SDK style but the project is not actually converted.
The output from log file ([ReportServer.csproj.txt](https://github.com/dotnet/upgrade-assistant/files/6584515/ReportServer.csproj.txt))

![image](https://user-images.githubusercontent.com/71254294/120479945-cf9f9500-c3ae-11eb-8963-c57cbce00cd1.png)

the actual project file

![image](https://user-images.githubusercontent.com/71254294/120480318-2efda500-c3af-11eb-9a90-0c935ed1d834.png)

and the properties window crash

![image](https://user-images.githubusercontent.com/71254294/120480425-4ccb0a00-c3af-11eb-8d4c-c60df2e27422.png)

### Further technical details
- Windows version 10 (64-bit)
- Include the output of `dotnet --list-sdks`
  - 3.1.201 [C:\Program Files\dotnet\sdk]
  - 5.0.202 [C:\Program Files\dotnet\sdk]
  - 5.0.203 [C:\Program Files\dotnet\sdk]
  - 5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  - 6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
- Include the output of `upgrade-assistant --version`
  - 0.2.227701+3e878899ae39105a278847a94a7c48f458cada83

**Comment by abpiskunov** [comment]
Please try latest Upgrade Assistant in VisualStudio or CLI.
