### ISSUE TITLE
Unsupported Xamarin targets are given an appropriate error warning when trying to run upgrade assistant

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/upgrade-assistant#585]
The only supported platforms (right now) are XF, Xamarin.Android, Xamarin.iOS. tvOS might work too (maddy/sweeky to check on this)

Unsupported platforms include UWP, macOS, watchOS, and WPF (community supported backend).

“UWP is not a supported .NET MAUI target. To target Windows desktops, you can deploy directly to WinUI3 from the .NET MAUI project itself. Any platform-specific resources and code can go into the .NET MAUI project.”

**Comment by maddyleger1** [comment]
@Redth do you think we can support tvos? what about regular macos (not catalyst?)
