### ISSUE TITLE
MAUI apps have an added startup.cs file

### ISSUE THREAD

**Issue by maddyleger1** [dotnet/upgrade-assistant#588]
```csharp
using Microsoft.Maui;
using Microsoft.Maui.Hosting;
using Microsoft.Maui.Controls.Compatibility;
using Microsoft.Maui.LifecycleEvents;

namespace HelloMaui
{
	public class Startup : IStartup
	{
		public void Configure(IAppHostBuilder appBuilder)
		{
			appBuilder
				.UseFormsCompatibility()
				.UseMauiApp<App>();
		}
	}
}
```

Open Questions: 
What needs to be moved over from App.xaml.cs to here? 
Will this override AppDelegate/MainActivity in the head projects or no?

**Comment by PureWeen** [comment]
One scenario to keep in mind here is how users will be able to use this startup file from platform heads. 

Currently in Xamarin.Forms users will have a renderer inside the platform head and the xplat control in a shared library. 

So if users want to be able to register those renderers from startup they need to be in a place that knows about both. 

For example to register an old renderer you use the following code

```C#
appBuilder
	.ConfigureMauiHandlers(handlers =>
	{
		handlers.AddCompatibilityRenderer(typeof(CustomButton),
			typeof(Microsoft.Maui.Controls.Compatibility.Platform.Android.AppCompat.ButtonRenderer));

	});
```

One approach to doing this is to create a custom startup file per platform. So you'd have a root `startup.cs` that is in your xplat code and then in your platform code you'd have something like this

```C#
public class NativeStartup : Startup
{
	public override void Configure(IAppHostBuilder appBuilder)
	{
		base.Configure(appBuilder);
		appBuilder
		.ConfigureMauiHandlers(handlers =>
		{
			handlers.AddCompatibilityRenderer(typeof(CustomButton),
				typeof(Microsoft.Maui.Controls.Compatibility.Platform.Android.AppCompat.ButtonRenderer));

		});
	}
}

[Application]
public class MainApplication : MauiApplication
{
	protected override IStartup OnCreateStartup() => new NativeStartup();

	public MainApplication(IntPtr handle, JniHandleOwnership ownership) : base(handle, ownership)
	{
	}
}
```

The upgrade assistant could try to read through the assembly for assembly attributes and then generate these native startup files itself as well
