### ISSUE TITLE
Update Xamarin.Forms namespaces

### ISSUE THREAD

**Issue by maddyleger1** [dotnet/upgrade-assistant#590]
New namespace:
Microsoft.Maui.Controls.*
Microsoft.Maui.Controls.Xaml

@Redth please confirm?!?!?!

**Comment by Sweekriti91** [comment]
** UPDATED NAMESPACE CHANGES in C# SOURCE **
Xamarin.Forms.* -> Microsoft.Maui;  && Micorosft.Maui.Controls; 

Xamarin.Essentials.* -> Microsoft.Maui.Essentials; 

Color.[NamedColor] -> Microsoft.Maui.Colors.[NamedColor] 
Color API Changes: https://gist.github.com/hartez/593fc3fb87035a3aedc91657e9c15ab3  

Shapes, Point -> add using Microsoft.Maui.Graphics;
