### ISSUE TITLE
Update XAML namespaces

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/upgrade-assistant#591]
xmlns=http://xamarin.com/schemas/2014/forms ->

xmlns=http://schemas.microsoft.com/dotnet/2021/maui

**Comment by Sweekriti91** [comment]
** UPDATED NAMESPACE CHANGES in C# SOURCE **
Xamarin.Forms.* -> Microsoft.Maui; 

&& Micorosft.Maui.Controls; 

 

Xamarin.Essentials.* -> Microsoft.Maui.Essentials; 

Xamarin 

Color.[NamedColor] -> Microsoft.Maui.Colors.[NamedColor] 
Color API Changes: https://gist.github.com/hartez/593fc3fb87035a3aedc91657e9c15ab3  

Shapes, Point -> add using Microsoft.Maui.Graphics;

**Comment by alexkblount** [comment]
absolute layout will require the following:
`xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls"`

`<cmp:AbsoluteLayout BackgroundColor="#909090"
                        HeightRequest="60">
            <Button Text="Cancel" 
                    Margin="10,10"
                    Style="{StaticResource nakedButton}" />
            <Image cmp:AbsoluteLayout.LayoutBounds="0.5, 0.5, 0.36, 0.7" 
                   cmp:AbsoluteLayout.LayoutFlags="All" 
                   BackgroundColor="Transparent" 
                   HeightRequest="36" 
                   Source="microsoft_gray.png" />
            <Button Text="Logout" 
                    Margin="10,10" 
                    cmp:AbsoluteLayout.LayoutBounds="1, 0, AutoSize, AutoSize" 
                    cmp:AbsoluteLayout.LayoutFlags="PositionProportional" 
                    Style="{StaticResource nakedButton}" />
        </cmp:AbsoluteLayout>`

**Comment by Sweekriti91** [comment]
RelativeLayout  is compat too, similar update to absolute might be needed

**Comment by mgoertz-msft** [comment]
This was done.
