### ISSUE TITLE
Upgrade VB Web API: UA0002 fails on HelpPageAreaRegistration.vb

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#613]
### Describe the bug
The `IdentifierUpgradeCodeFixer` is blocking the upgrade for VB Web apps that include route registration where the default route is mapped using an anonymous type.

```vb
        Public Overrides Sub RegisterArea(context As AreaRegistrationContext)
            context.MapRoute(
                "HelpPage_Default",
                "Help/{action}/{apiId}",
                New With {.Controller = "Help", .action = "Index", .apiId = UrlParameter.Optional})
            HelpPageConfig.Register(GlobalConfiguration.Configuration)
        End Sub
```
The `.Controller` in this code snippet from the default ASP.NET template for web apps should not trigger the analyzer.

![image](https://user-images.githubusercontent.com/23503973/121424937-8237a080-c937-11eb-9fb2-3d691604f008.png)

### To Reproduce
1. Create a "File->New" ASP.NET Framework Web app for Visual Basic
2. Run the `upgrade-assistant` tool on the web app.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/23503973/121425172-bca13d80-c937-11eb-8edb-87b516569881.png)

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.QualifiedNameSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.IdentifierNameSyntax'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj)

**Comment by KSchlobohm** [comment]
![image](https://user-images.githubusercontent.com/23503973/121432237-07bf4e80-c940-11eb-8525-72d04550d0f4.png)

As a temporary workaround the step completed successfully when I changed the code snippet from `.Controller` to `.controller`

**Comment by sunandabalu** [comment]
Closing this since there is a workaround for the issue.
