### ISSUE TITLE
Extend WCF scenario detection

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#624]
## Summary
#617 adds the ability to detect WCF server components so that we can be more proactive about the upgrade journey. Some customers will choose [CoreWCF](https://github.com/CoreWCF/CoreWCF) and some customers will choose gRPC.

## Motivation and goals
* We want to detect more WCF server scenarios e.g. (look for ServiceHost or other key types).

## In scope
* Detect ServiceHost

## Out of scope

* Making the recommended changes. This is an advisory only.

## Risks / unknowns

* This ReadyCheck does not make a technology decision. It should only provide guidance so that customers can choose the right technology when this scenario is detected.

**Comment by KSchlobohm** [comment]
We should consider doing Roslyn analysis of the code rather than string detection.

**Comment by brandonh-msft** [comment]
cc @SimonaLiao - I think your PR will go toward this user story.
