### ISSUE TITLE
upgrade-assistant project build errors

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#633]
## Summary
I think there's a race condition that is sometimes creating compile time errors during the project build process.

## Motivation and goals
I want to solve these challenges:
* When I make a change to a file in a class library (e.g. `DuplicateReferenceAnalyzer`). I see that I can no longer hit a debugger break point because the code I'm debugging isn't the code that's running. 

![image](https://user-images.githubusercontent.com/23503973/122124628-2799bb00-cdf5-11eb-865a-149e61b18f8e.png)

* In some cases this results in projects failing to build. Clean all from the sln level. Then build the solution and you will get build errors. Build it again, and you'll get fewer build errors, or even success!

## In scope

* After a 1st time checkout of the project I can start the app.
* Mysterious build errors are resolved.

## Examples

```
CSC : error CS0006: Metadata file 'D:\workspace\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CodeFixes\Release\netstandard2.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CodeFixes.dll' could not be found [D:\workspace\_work\1\s\src\steps\Microsoft.DotNet.UpgradeAssistant.Steps.Source\Microsoft.DotNet.UpgradeAssistant.Steps.Source.csproj]
```

**Comment by twsouthwick** [comment]
Hmm I'll take a look at this. For now, rebuilding the solution will work.
