### ISSUE TITLE
Add API to IExtensionLoader to identify when it matches

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#639]
Not sure if this is worth changing, but rather than trying all the loaders, `IExtensionLoader` could have an API for determining whether a path matches their expected format (*.zip, manifest.json, etc.) and you could try loading the extension with only the loaders that indicate they can handle the path.

_Originally posted by @mjrousos in https://github.com/dotnet/upgrade-assistant/pull/623#discussion_r652786310_

**Comment by mgoertz-msft** [comment]
No longer applicable.
