### ISSUE TITLE
As a user, my connection strings are automatically migrated to appsettings.json

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#64]
This already happens for app settings. The tool should also move connection strings.

**Comment by johanbenschop** [comment]
I have added a PR that adds support for the migration of connection strings to appsettings.json.

**Comment by Saibamen** [comment]
Missing link for this PR: https://github.com/dotnet/upgrade-assistant/pull/571

**Comment by mjrousos** [comment]
Closing thanks to #571
