### ISSUE TITLE
Problem installing upgrade-assistent

### ISSUE THREAD

**Issue by aspi-dwtt** [dotnet/upgrade-assistant#648]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows :
![image](https://user-images.githubusercontent.com/76160987/122764737-11ca4100-d2a0-11eb-95d1-8063306c380f.png)

I've installed VS 2019 16.10.2

Dotnet SDK's
![image](https://user-images.githubusercontent.com/76160987/122765393-bf3d5480-d2a0-11eb-958b-dc8be6120dcb.png)

I'm trying to install the upgrade-assistant and I get the error shown below.

How can I fix this problem?
I'm confused about net50 and net5.0

Kind regards,

Alberto

..> dotnet tool install -g upgrade-assistant
error NU1202: Package upgrade-assistant 0.2.231403 is not compatible with net50 (.NETFramework,Version=v5.0) / any. Package upgrade-assistant 0.2.231403 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by twsouthwick** [comment]
Can you try installing it when you're in a different directory? I've seen some issues when you try to install a CLI tool in a directory with a global.json

**Comment by aspi-dwtt** [comment]
Tried installing it in a brand new directory, same result

C:\test>dotnet tool install -g upgrade-assistant
error NU1202: Package upgrade-assistant 0.2.231403 is not compatible with net50 (.NETFramework,Version=v5.0) / any. Package upgrade-assistant 0.2.231403 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sunandabalu** [comment]
@aspi-dwtt Are you having trouble restoring other nuget packages?

**Comment by sunandabalu** [comment]
Since there is no response for the past month from OP, closing this. Feel free to re-open with more details as requested above in case this behavior is observed again.

**Comment by sasquad92** [comment]
I have same issue, trying to install with command:
`dotnet tool install -g upgrade-assistant` or `dotnet tool install -g upgrade-assistant --ignore-failed-sources`

result:
```
error NU1202: Pakiet upgrade-assistant 0.3.310801 nie jest zgodny z elementem net60 (.NETFramework,Version=v6.0) / any. Pakiet upgrade-assistant 0.3.310801 obsługuje:
C:\Users\krzysztof.sommerrey\AppData\Local\Temp\5p5pqtpa.3nq\restore.csproj : error NU1202:   - net5.0 (.NETCoreApp,Version=v5.0) / any
C:\Users\krzysztof.sommerrey\AppData\Local\Temp\5p5pqtpa.3nq\restore.csproj : error NU1202:   - net6.0 (.NETCoreApp,Version=v6.0) / any
Nie można przywrócić pakietu narzędzia.
Zainstalowanie narzędzia "upgrade-assistant" nie powiodło się. To niepowodzenie może wynikać z następujących przyczyn:

* Próbujesz zainstalować wersję zapoznawczą bez użycia opcji --version do określenia wersji.
* Znaleziono pakiet o tej nazwie, ale nie było to narzędzie platformy .NET.
* Nie można uzyskać dostępu do wymaganego źródła danych NuGet, być może ze względu na problemy z połączeniem z Internetem.
* Podana nazwa narzędzia została wpisana nieprawidłowo.

Więcej przyczyn, w tym wymuszanie nazw pakietów, można znaleźć na stronie https://aka.ms/failure-installing-tool
```

in english:
upgrade-assistant 0.3.310801 is not compatible with net60 (.NETFramework,Version=v6.0) / any.
Packet  upgrade-assistant 0.3.310801 supports:
net5.0 (.NETCoreApp,Version=v5.0) / any
net6.0 (.NETCoreApp,Version=v6.0) / any
Cannot restore tool packet.

But when I list installed SDKs I've got:
```
PS C:\Users\krzysztof.sommerrey> dotnet --list-sdks
3.1.300 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]
5.0.406 [C:\Program Files\dotnet\sdk]
6.0.201 [C:\Program Files\dotnet\sdk]
```

**Comment by sunandabalu** [comment]
@sasquad92 Do you have issues restoring other nuget packages?

**Comment by sasquad92** [comment]
No, olny with installing this tool
