### ISSUE TITLE
"Convert project file to SDK style" failed with whitespace in username

### ISSUE THREAD

**Issue by Leosamus** [dotnet/upgrade-assistant#654]
### Describe the bug
While the "Convert project file to SDK style" step, it fails saying that the specified file does not exists.

`[16:42:49 VRB] Starting process 'dotnet C:\Users\Hylian MESMOUDI\.dotnet\tools\.store\upgrade-assistant\0.2.231403\upgrade-assistant\0.2.231403\tools\net5.0\any\extensions\default\try-convert\try-convert.dll --no-backup -m "C:\\Program Files\\dotnet\\sdk\\5.0.300\\" --force-web-conversion --keep-current-tfms -p "C:\Dev\LMS\lms-api\LMS.Data\LMS.Data.csproj"'`

You can see that "C:\Users\Hylian MESMOUDI\.dotnet\tools\.store\upgrade-assistant\0.2.231403\upgrade-assistant\0.2.231403\tools\net5.0\any\extensions\default\try-convert\try-convert.dll" is called without quotes. As you can see, there is a space in my username on my professional laptop.

### To Reproduce
- Have a whitespace in your username
- Start the upgrade-assistant
- Reach the "Convert project file to SDK style" step
- Use the verbose log and retry if you want to see that log

**Comment by sunandabalu** [comment]
closes with #655
