### ISSUE TITLE
Files included with "<Content Include=..." are removed from csproj

### ISSUE THREAD

**Issue by thomas11** [dotnet/upgrade-assistant#669]
Sections such as the following are removed without replacement from our csproj files. We do need these files.

```
<ItemGroup>
    <Content Include="QueryGeneration\Facets\Facet BNF.txt" />
    <Content Include="QueryGeneration\Filters\Search OData Filter BNF.txt" />
    <Content Include="QueryGeneration\FullLuceneQueries\Full Lucene Query BNF.txt" />
</ItemGroup>
```

### Further technical details

  - Windows 10 Enterprise 21H1
  - upgrade-assistant 0.2.231403+ee9618b1fb94a6881a2e38a7b2ad50356ba54465

```
> dotnet --list-sdks
3.1.410 [C:\Program Files\dotnet\sdk]
5.0.204 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
```

**Comment by sunandabalu** [comment]
@thomas11 Could you provide the csproj you are seeing this issue with so we can debug this issue? looks like  bug in try-convert.

**Comment by sunandabalu** [comment]
Since there is no response from OP in the past month, closing this. Feel free to reopen if this issue still persists / provide more details as requested above.
