### ISSUE TITLE
Upgrade session variable access

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#679]
In ASP.NET, session variables were access with indexers (`Session["MyVariable"]`). In ASP.NET Core, they need to be accessed via methods (`Session.GetString("MyVariable")`).

Upgrade Assistant should upgrade these code patterns (including dealing with necessary serialization of non-string values).

**Comment by twsouthwick** [comment]
This is available from the Microsoft.AspNetCore.SystemWebAdapters package
