### ISSUE TITLE
Problem installing dotnet upgrade-assistant

### ISSUE THREAD

**Issue by rainer17** [dotnet/upgrade-assistant#717]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\WINDOWS\system32>dotnet tool install -g upgrade-assistant
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error : Der Dienstindex für die Quelle "http://f-nuget.binderholz.lan/api/v2" konnte nicht geladen werden. [C:\Users\raisto\AppData\Local\Temp\l2uldezx.gwh\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error :   Der Inhalt unter "http://f-nuget.binderholz.lan/api/v2" ist kein gültiges JSON-Objekt. [C:\Users\raisto\AppData\Local\Temp\l2uldezx.gwh\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error :   Unexpected character encountered while parsing value: <. Path '', line 0, position 0. [C:\Users\raisto\AppData\Local\Temp\l2uldezx.gwh\restore.csproj]
Das Toolpaket konnte nicht wiederhergestellt werden.
Fehler bei der Installation des Tools "upgrade-assistant". Dieser Fehler kann folgende Ursachen haben:

* Sie versuchen, eine Vorschauversion zu installieren und haben nicht die Option "--version" verwendet, um die Version anzugeben.
* Ein Paket mit diesem Namen wurde gefunden, aber es handelte sich nicht um ein .NET-Tool.
* Auf den erforderlichen NuGet-Feed kann nicht zugegriffen werden, möglicherweise aufgrund eines Problems mit der Internetverbindung.
* Sie haben den Namen des Tools falsch eingegeben.

Weitere Gründe sowie Informationen zum Erzwingen der Paketbenennung finden Sie unter https://aka.ms/failure-installing-tool.

#####

C:\WINDOWS\system32>dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.302
 Commit:    c005824e35

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\WINDOWS\system32>

**Comment by sunandabalu** [comment]
@rainer17 Could you try the dotnet install with ignore-failed-sources like so `dotnet tool install -g upgrade-assistant --ignore-failed-sources` ? It looks like something weird with one of the custom feeds you have in the nuget.config.

**Comment by sunandabalu** [comment]
Closing this issue, the above comment should help. Reopen if you need.
