### ISSUE TITLE
 Skipping upgrade step Convert project file to SDK style

### ISSUE THREAD

**Issue by andrewjahunter** [dotnet/upgrade-assistant#720]
[log.txt](https://github.com/dotnet/upgrade-assistant/files/6825520/log.txt)
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

When I run the assistant, it goes fine till it has to convert the project file to the new SDK style. It just skips this step. It then bombs out later in step 4 when trying to convert to .NET as the project file has not been converted above as it was skipped.

See the log file attached

Please advice
Thanks

**Comment by sunandabalu** [comment]
@andrewjahunter Could you attach the csproj you are seeing this issue with?

**Comment by sunandabalu** [comment]
@andrewjahunter Could you also attach the log.txt after running the tool in verbose mode (-v)?

**Comment by sunandabalu** [comment]
Since there is no response from OP in the past 18 days, closing this. Feel free to reopen if the issue still persists and provide more details as requested above.
