### ISSUE TITLE
Analyze report fails validation

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#729]
After running the analyze command on baby smash, it failed to validate correctly at https://sarifweb.azurewebsites.net/Validation. 

- [ ] `SARIF2005: runs[0].tool.driver: The tool 'Dependency Analysis' does not provide 'informationUri'. This property helps the developer responsible for addessing a result by providing a way to learn more about the tool.`
- [ ] `SARIF2005: runs[0].tool.driver: The tool 'Dependency Analysis' does not provide any of the version-related properties 'version', 'semanticVersion', 'dottedQuadFileVersion'. Providing version information enables the log file consumer to determine whether the file was produced by an up to date version, and to avoid accidentally comparing log files produced by different tool versions.`
- [ ] `SARIF1010: runs[0].results[0]: This result contains neither of the properties 'ruleId' or 'rule.id'. The SARIF specification ([§3.27.5](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317643)) requires at least one of these properties to be present.`

**Comment by sunandabalu** [comment]
Closed via #730
