### ISSUE TITLE
How can I upgrade to .NET 6 using "upgrade-assistant" tool?

### ISSUE THREAD

**Issue by sunilforever** [dotnet/upgrade-assistant#740]
Hi,
I used "upgrade-assistant" tool to upgrade my projects to "NET 6", but its by default upgrades to "Net 5". I have installed Visual Studio 22 Preview and Net 6, still this tool is not considering that...Is there any way to specify the "Version" to which we want to upgrade our projects?

**Comment by mjrousos** [comment]
Hi @sunilforever, the `--target-tfm-support` parameter can be used to specify which .NET release Upgrade Assistant should use when upgrading apps. For .NET 6, you'll want to run `upgrade-assistant upgrade --target-tfm-support Preview ...` where the ... is whatever other arguments you pass like your solution or project path.

Other options (besides `Preview`) that can be used are `Current` (5.0, the default) and `LTS` (.NET Core 3.1).

**Comment by sunilforever** [comment]
Thanks Mike...It worked.
    On Thursday, July 22, 2021, 07:02:13 PM GMT+5:30, Mike Rousos ***@***.***> wrote:  
 
 


Closed #740.
