### ISSUE TITLE
Question: Does this support upgrades between .NET Core versions?

### ISSUE THREAD

**Issue by Tiberriver256** [dotnet/upgrade-assistant#758]
Does this support upgrades between .NET Core versions?

For example, if I have an ASP.NET Core 2.1 project that I want to upgrade to .NET 5 can I use this tool?

**Comment by sunandabalu** [comment]
@Tiberriver256 Thanks for the question, We have not explicitly tested upgrading from an older version of .NET core but there isnt anything in code that will block you from doing it. The flow should skip the "Move to SDK-style" and "Pre-TFM Package updates" and should straight take you to the "Update TFM" step where your chosen TFM will be applied (LTS, Current or Preview). Please try it out and let us know if you see any issues.
