### ISSUE TITLE
Error while using "System.Deployment.Application.ApplicationDeployment.CurrentDeployment.ActivationUri.Query"

### ISSUE THREAD

**Issue by sunilforever** [dotnet/upgrade-assistant#760]
Hi,
After I upgraded my project from ".Net Framework 4.8" to "net6.0-windows" using the command (upgrade-assistant upgrade --target-tfm-support Preview MySol.sln), I am getting below error 

"Error	BC30456	'Deployment' is not a member of 'System'"  for below line

Dim QueryString As String = System.Deployment.Application.ApplicationDeployment.CurrentDeployment.ActivationUri.Query

Please let me know, if more details are required.

**Comment by sunandabalu** [comment]
System.Deployment is not supported in core, you should have seen a warning message calling this out while you were upgrading the project with `upgrade-assistant upgrade` . Please do let us know if the warning did not show up in your log.txt.

**Comment by sunilforever** [comment]
Thanks for prompt reply.

I didn't see any Warning in the Log.txt, it only shows the "Info" only. Also, if System.Deployment is not supported in core, would you please suggest me the alternate option?

**Comment by sunandabalu** [comment]
> Also, if System.Deployment is not supported in core, would you please suggest me the alternate option?

Unfortunately there isnt any supported way to use `system.deployment` in .net 5, there are some workarounds mentioned in the issue by members of the community, you could try the same if that suits your scenario - https://github.com/dotnet/deployment-tools/issues/53

**Comment by sunandabalu** [comment]
Closing this issue, since there is no action item for UA to provide here.

**Comment by NikolaosWakem** [comment]
Does anyone know why the developers of .NET5 and .NET6 are still refusing to put ActivationUri somewhere or even explain any other way to access it?

We all have to ship a 4.7.2 ClickOnce app with a packaged .NET 5 app included, just to do

var uri = ApplicationDeployment.CurrentDeployment.ActivationUri
process.start("theNet5App.exe", "--uri" +uri )

Which is so silly.
