### ISSUE TITLE
MAUI XAML Layout related updates

### ISSUE THREAD

**Issue by Sweekriti91** [dotnet/upgrade-assistant#774]
Adds more specifics, building on information here : https://github.com/dotnet/upgrade-assistant/issues/591

**Comment by Sweekriti91** [comment]
` xmlns:cmp="clr-namespace:Microsoft.Maui.Controls.Compatibility;assembly=Microsoft.Maui.Controls"` 

Add compat for : AbsoluteLayout, RelativeLayout

**Comment by hartez** [comment]
Forms has a default value of 6 for Grid.RowSpacing, Grid.ColumnSpacing, and StackLayout.Spacing. MAUI uses a default of zero for these values. So for folks updating from Forms to MAUI, we should add global styles for Grid and StackLayout to restore the Forms default values. Something like:

```
<ResourceDictionary>
	<Style TargetType="Grid">
		<Setter Property="RowSpacing" Value="6" />
		<Setter Property="ColumnSpacing" Value="6" />
	</Style>
	<Style TargetType="StackLayout">
		<Setter Property="Spacing" Value="6" />
	</Style>
</ResourceDictionary>
```

**Comment by aeonblaire** [comment]
Why is AbsoluteLayout being relegated to compatibility? I think it is still useful for custom layouts. Is TranslationX and TranslationY enough for absolute positioning inside the official layouts? What would be the alternative method for relative positioning?

**Comment by alexeystrakh** [comment]
In my case the markup was trying to reference FlexDirection like this:

```
<local:EnumPicker EnumType="{x:Type FlexDirection}"
SelectedItem="{Binding Direction}"
Grid.Row="1" Grid.Column="1" />
```

And I was getting the following error:

```
XamlC error XFC0000: Cannot resolve type "http://schemas.microsoft.com/dotnet/2021/maui:FlexDirection"
```

I had to explicitly define the type namespace, don't forget the assembly name as well and then use it with that namespace:

```
xmlns:layouts="clr-namespace:Microsoft.Maui.Layouts;assembly=Microsoft.Maui"
...
<local:EnumPicker EnumType="{x:Type layouts:FlexDirection}"
SelectedItem="{Binding Direction}"
Grid.Row="1" Grid.Column="1" />
```

This is a breaking change because in the original xaml markup with the original Xamarin.Forms no explicit namespace definition is required.
