### ISSUE TITLE
Failure on "dotnet tool install -g upgrade-assistant"

### ISSUE THREAD

**Issue by phr00t** [dotnet/upgrade-assistant#775]
Why the heck is it trying to get the upgrade-assistant from packages.xenko.com!?

Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

C:\Users\Phr00t>dotnet tool install -g upgrade-assistant
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error : Failed to retrieve information about 'upgrade-assistant' from remote source 'https://packages.xenko.com/nuget/FindPackagesById()?id='upgrade-assistant'&semVerLevel=2.0.0'. [C:\Users\Phr00t\AppData\Local\Temp\q01rot5h.enb\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\Phr00t\AppData\Local\Temp\q01rot5h.enb\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.302\NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [C:\Users\Phr00t\AppData\Local\Temp\q01rot5h.enb\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sunandabalu** [comment]
looks like packages.xenko.com is defined as a source in your nuget.config. If you remove that then it should not be using that as a source. The other option is to try with `--ignore-failed-sources`

**Comment by phr00t** [comment]
Removing the Xenko source worked! I did it through Visual Studio Tools -> Nuget Package Manager -> Package Manager Settings -> Package Sources.
