### ISSUE TITLE
Add support for HTML output format

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/upgrade-assistant#786]

**Comment by twsouthwick** [comment]
Would the react sarif viewer not work?

**Comment by sunandabalu** [comment]
> Would the react sarif viewer not work?

It might just work, it seems to just be doing the job - https://microsoft.github.io/sarif-web-component/ . I will need to play around this a bit to get some customer feedback on this as well.

**Comment by sunandabalu** [comment]
Hey @bleaphar I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/net-upgrade-assistant-60109bcbf6660400171726e3/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by sunandabalu** [comment]
Addressed by #966
