### ISSUE TITLE
.NET MAUI C# API Changes -> create Analyzers + Code fixes

### ISSUE THREAD

**Issue by Sweekriti91** [dotnet/upgrade-assistant#789]
Breaking up tasks from https://github.com/dotnet/upgrade-assistant/issues/590

Remaining work : 
Color.[NamedColor] -> Microsoft.Maui.Colors.[NamedColor]
Color API Changes: https://gist.github.com/hartez/593fc3fb87035a3aedc91657e9c15ab3

Shapes, Point -> add using Microsoft.Maui.Graphics;

*Colors* follow up on BlueViolet if removed or back

**Comment by mgoertz-msft** [comment]
This was done.
