### ISSUE TITLE
Analyze command should give more details in console output

### ISSUE THREAD

**Issue by mjrousos** [dotnet/upgrade-assistant#805]
I've been experimenting with the Analyze command. The Sarif output file is really cool, but it would be great if all the updates needed were also listed in the console so that I could easily get a sense of needed changes as soon as the tool executes.

Currently, necessary package updates are listed but for diagnostics, the Analyze command only says `Identified 16 diagnostics in project eShopLegacyMVC`. For upgrade scenarios this is ok because the specific diagnostics are walked through in source updater step/sub-steps but, for the Analyze command, it would be useful to have all of the diagnostics listed out (or at least summarized by diagnostic ID and count).

**Comment by sunandabalu** [comment]
Seems reasonable to me, we could just log to console when we are processing each of the diagnostics in the `ProcessDiagnostics` method - https://github.com/dotnet/upgrade-assistant/blob/main/src/extensions/default/Microsoft.DotNet.UpgradeAssistant.Steps.Source/DiagnosticAnalyzerResultProvider.cs#L60 that way this happens only for analyze and not for upgrade.

**Comment by sunandabalu** [comment]
Addressed by #877
