### ISSUE TITLE
dotnet tool install -g upgrade-assistant takes wrong source

### ISSUE THREAD

**Issue by compunited** [dotnet/upgrade-assistant#806]
dotnet tool install -g upgrade-assistant 
leads to 
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\NuGet.targets(131,5): error : Fehler beim Abrufen von Informationen zu "upgrade-assistant" aus der Remotequelle "https://pkgs.dev.azure.com/GreenerSoftware/_packaging/fd0f674f-868a-4655-8ddd-8c3f2360dad8/nuget/v3/flat2/upgrade-assistant/index.json". [C:\Users\kugle\AppData\Local\Temp\vwazqmm3.4yh\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\kugle\AppData\Local\Temp\vwazqmm3.4yh\restore.csproj]

which is the wrong nuget source

**Comment by twsouthwick** [comment]
You're trying to install it in a directory that already has a NuGet.config with sources that don't have it available. You can either go to another adirectory or do `dotnet tool install -g upgrade-assistant --ignore-failed-sources`

**Comment by twsouthwick** [comment]
Closing for now. If that doesn't work, please reopen.

**Comment by twsouthwick** [comment]
Opened https://github.com/dotnet/sdk/issues/20396 to track not looking at local nuget.config entries
