### ISSUE TITLE
Upgrade-Assistant porting to .Net Standard 2.0 instead of .Net Core  

### ISSUE THREAD

**Issue by sandeepd12** [dotnet/upgrade-assistant#827]
I tried converting class libraries from .Net framework 4.8 to .Net 5.0 using Upgrade assistant. However out of 4 class libraries only one is migrated to .Net 5.0. Whereas, remaining 3 are ported to .Net Standard 2.0 instead of .Net 5.0.
Can anyone help me out in this?

**Comment by twsouthwick** [comment]
I'll close this for now, but if you have other issues, please reopen!
