### ISSUE TITLE
Can't get --vs-path working

### ISSUE THREAD

**Issue by Roneri75** [dotnet/upgrade-assistant#844]
So i'm trying to upgrade a ASP.net project from .NET Framework 4.7 to .Net 5.
I have VS 2019.11.2 installed but i also have VS 2022 Preview 3.1 installed.
When i try to run the upgrade installer with the --vs-path set i get this:
'--vs-path' was not matched. Did you mean '--vs-path'?

This is the command I'm running:
upgrade-assistant --vs-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" analyze "D:\repos\....csproj"
It does not mater if i use upgrade or analyze, i just get the same error...
'--vs-path' was not matched. Did you mean '--vs-path'?

**Comment by sunandabalu** [comment]
@Roneri75 The upgrade / analyze command needs come before the options (--vs-path) basically `upgrade-assistant <command> <options>`.
