### ISSUE TITLE
command not found: upgrade-assistant

### ISSUE THREAD

**Issue by abadru** [dotnet/upgrade-assistant#862]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: Mac OS

I have installed the upgrade-assistant tool globally on Mac OS using the command: **dotnet tool install -g upgrade-assistant**
 and got feedback that was successfully installed, but I get the following error when I try to execute the command **upgrade-assistant upgrade** on my solution or project:

**![Screen Shot 2021-09-27 at 08 47 39](https://user-images.githubusercontent.com/15192264/134857999-2bae79e6-bdf7-4f19-819a-de2b725cea51.png)**

Even after I restarted my computer the error persist.

**Comment by sunandabalu** [comment]
@abadru Thanks for filing the issue, we do not have support for upgrade-assistant to run on MacOS yet. We are tracking this in #550 , so closing this in favor of that.
