### ISSUE TITLE
WinformsResultProvider not picking all the IUpdaters

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/upgrade-assistant#883]
WinformsResultProvider for Analzye command is only picking one the WinformsUpdater and not all of them.

**Comment by ujjwalchadha** [comment]
@brandonh-msft can you share the piece of code related to this?
The analyze command for uwp extension is not working as expected as of now. I do not think it is because of this issue though.

**Comment by sunandabalu** [comment]
The area of code where it needs to pick all the source updaters for analyze async only one of them is picked 
https://github.com/dotnet/upgrade-assistant/blob/main/src/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows/WinformsResultProvider.cs#L62

**Comment by brandonh-msft** [comment]
Thanks @sunandabalu - I'm not seeing where in that code we get a _collection_ of things, though... We do loop through the results that come back from the upgrader here, though

https://github.com/dotnet/upgrade-assistant/blob/7759eb9451dd85d20ac83e8001e549ce74ede68d/src/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows/WinformsResultProvider.cs#L74

I'll touch base w/ you offline :)
