### ISSUE TITLE
dot.net platform

### ISSUE THREAD

**Issue by Mlmolefe2** [dotnet/upgrade-assistant#900]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-sdk
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by brandonh-msft** [comment]
Closing stale issues; if you're able to provide current repro, though, let us know.
