### ISSUE TITLE
install upgrade-assistant dotnet tool issue

### ISSUE THREAD

**Issue by gmenaka** [dotnet/upgrade-assistant#913]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

* my lastest SDK : 5.0.402 [C:\Program Files\dotnet\sdk]
* I set MSBuildSDKsPath = C:\Program Files\dotnet\sdk\5.0.402\Sdks
* I have DOTNet5 apps and they are working fine. Only issue comes when I tried to install Upgrade-Assistant
* PC details:
*   OS = Windows 10 Enterprise
*   Visual Studio 2019

Error:
===
C:\Users\SAM\AppData\Local\Temp\ygkcmgp2.zml\restore.csproj(5,31): error MSB4236: Das angegebene SDK "Microsoft.NET.Sdk" wurde nicht gefunden.
Das Toolpaket konnte nicht wiederhergestellt werden.
Fehler bei der Installation des Tools "upgrade-assistant". Dieser Fehler kann folgende Ursachen haben:

* Sie versuchen, eine Vorschauversion zu installieren und haben nicht die Option "--version" verwendet, um die Version anzugeben.
* Ein Paket mit diesem Namen wurde gefunden, aber es handelte sich nicht um ein .NET-Tool.
* Auf den erforderlichen NuGet-Feed kann nicht zugegriffen werden, möglicherweise aufgrund eines Problems mit der Internetverbindung.
* Sie haben den Namen des Tools falsch eingegeben.

Weitere Gründe sowie Informationen zum Erzwingen der Paketbenennung finden Sie unter https://aka.ms/failure-installing-tool.

**Comment by sunandabalu** [comment]
@twsouthwick Could you provide some guidance here?

**Comment by sunandabalu** [comment]
@gmenaka Are you seeing an issue installing any other nuget packages?
