### ISSUE TITLE
How to reverse an incomplete upgrade

### ISSUE THREAD

**Issue by rhires** [dotnet/upgrade-assistant#929]
### Describe the bug
I skipped a step by accident and then could not go back and try again, nor could I start over. 

### Further technical details
- Windows version and bitness info (64-bit)
- Include the output of dotnet sdks
`3.0.100 [C:\Program Files\dotnet\sdk]
3.1.415 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]`
- Include the output of `upgrade-assistant --version`
0.3.252501+d008dcd65150d4d24cdeb8378cc517cc5b121b2f

**Comment by twsouthwick** [comment]
First off, you can start over by:

- Using the backup that is produced
- If you're using a version control system, you can revert that way

However, we have tried to design Upgrade Assistant to pick up where you left off. What step did you skip? What state is your project in?

**Comment by rhires** [comment]
I think I skipped the 2nd or third step, not realizing that the whole process had to be done before the single project was complete, so I chose to end the upgrade entirely.

**Comment by rhires** [comment]
Also, how do I use the backup that is produced? Are there instructions for that?

**Comment by twsouthwick** [comment]
> Also, how do I use the backup that is produced? Are there instructions for that?

You should be able to just copy it to the directory. We generally recommend using a version control system which simplifies it quite a bit

> I think I skipped the 2nd or third step, not realizing that the whole process had to be done before the single project was complete, so I chose to end the upgrade entirely.

Interesting. Do you have an example project?

**Comment by rhires** [comment]
I've abandoned this for now. My project uses webforms and SOAP, and is not going to be using either of those going forward. Thanks.
