### ISSUE TITLE
Installing upgrade assistant only returns NU1101 error

### ISSUE THREAD

**Issue by BizD3V** [dotnet/upgrade-assistant#930]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Just installed VS22 (production v17, not the preview) and running **dotnet** displays the expected help. But when I run **dotnet tool install -g upgrade-assistant**, I get **NU1101: Unable to find package upgrade-assistant**. 

I've even tried explicitly downloading and installing the SDK (although I'd think VS would do that for me), same result. I'm running WIn10 21H2 with all patches (including Nov's patch Tuesday). And I've created and run some simple VS projects without an issue. Where/how do I install this package as the referenced source implies it should just work ;-)

**Comment by sunandabalu** [comment]
@BizD3V Are you able to install any other nuget packages?

**Comment by BizD3V** [comment]
Thanks Sunanda! That simple question pointed me in the right direction. Somehow (like right out of the box) my system had no online package sources. Once I added it, everything is working. But that does leave me trying to find the "definitive" location for Nuget.org packages. Do you happen to know if it's still https://api.nuget.org/v3/index.json?

**Comment by sunandabalu** [comment]
> Thanks Sunanda! That simple question pointed me in the right direction. Somehow (like right out of the box) my system had no online package sources. Once I added it, everything is working. But that does leave me trying to find the "definitive" location for Nuget.org packages. Do you happen to know if it's still https://api.nuget.org/v3/index.json?

Yes that would be the right package source for nuget.org 
`<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />`

**Comment by BizD3V** [comment]
TY Appreciate the quick resolution.
