### ISSUE TITLE
I have dotnet upgrade assistant installed for .NET 5. How can I update it to .NET 6?

### ISSUE THREAD

**Issue by inabeel** [dotnet/upgrade-assistant#934]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

I have dotnet upgrade assistant installed for .NET 5. How can I update it to .NET 6

**Comment by sunandabalu** [comment]
@inabeel Are you trying to upgrade your projects to .NET 6?

**Comment by inabeel** [comment]
> @inabeel Are you trying to upgrade your projects to .NET 6?

Yes., I want to convert my solution to .NET 6. For this purpose I want to run upgrade-assistant.
Problem is I have already installed upgrade-assistant, which was for .NET 5. And it still uses same .NET 5, and i am unable to update it to .NET 6

**Comment by sunandabalu** [comment]
> > @inabeel Are you trying to upgrade your projects to .NET 6?
> 
> Yes., I want to convert my solution to .NET 6. For this purpose I want to run upgrade-assistant. Problem is I have already installed upgrade-assistant, which was for .NET 5. And it still uses same .NET 5, and i am unable to update it to .NET 6

If you just get the latest [upgrade-assistant package](https://www.nuget.org/packages/upgrade-assistant/0.3.255803) from nuget feed will get you the version that works with .NET 6

**Comment by inabeel** [comment]
I tried that command, but it just didn't work. Best solution for me was to uninstall upgrade assistant via command and then install a new copy, which installed latest one.
