### ISSUE TITLE
Prebuild + Postbuild Events are not correctly converted into SDK-Format

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/upgrade-assistant#936]
- [ ] Include the log file `upgrade-assistant.clef` that is produced in the working directory

### Describe the bug
In the Old Project format you could define pre/post buildevents using the names, like this:
<PreBuildEvent>echo "TargetPath is $(TargetPath)"</PreBuildEvent>
in the SDK Format it must be in a Different Format, like this:
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo &quot;TargetPath is $(TargetPath)&quot;" />
  </Target>
Same issue in a different project:
https://github.com/dotnet/try-convert/issues/269

### To Reproduce
Add
<PreBuildEvent>echo "TargetPath is $(TargetPath)"</PreBuildEvent>
do any project, and convert it.
build the old and the converted project and look at the output.

### Further technical details
- Windows 10.0.19041.1288 and (64-bit)

- Include the output of `dotnet --list-sdks`
2.1.526 [C:\Program Files\dotnet\sdk]
2.1.818 [C:\Program Files\dotnet\sdk]
2.2.402 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
3.0.101-servicing-014317 [C:\Program Files\dotnet\sdk]
3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
3.1.120 [C:\Program Files\dotnet\sdk]
3.1.415 [C:\Program Files\dotnet\sdk]
5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]

- Include the output of `upgrade-assistant --version`
0.3.255803+d72527aefab54bfbadc3227b4f1ffd326c1e9a8a

**Comment by sunandabalu** [comment]
Upgrade-Assistant uses try-convert internally so we are hitting the same issue.

**Comment by sunandabalu** [comment]
Closing the issue here in UA, it can be tracked with the issue in try-convert

**Comment by IgbyLargeman** [comment]
This should be re-opened as it has not been fixed. The fact it also exists in another project doesn't justify closing it here.
