### ISSUE TITLE
Log the output in a format, that can be read by the sarif-vscode-extension

### ISSUE THREAD

**Issue by klacol** [dotnet/upgrade-assistant#940]
# Summary
Hi, I am in the process of upgrading a project to .NET 6.0. I use the dotnet upgrade-assistant .
This assistant produces logs in the sarif-format. But they cannot be opened with this [VSC-extension](https://github.com/microsoft/sarif-vscode-extension).

> 'c:...\AnalysisReport.sarif' was not loaded. Version '2.1.0' and schema 'http://json.schemastore.org/sarif-2.1.0' is not supported.

Is there a plan to support any sarif viewer?

## Motivation and goals

I have to read the outcome of the analysis and talk with other developers about the results.

**Comment by sunandabalu** [comment]
This is addressed in the PR https://github.com/dotnet/upgrade-assistant/pull/927 , we were using an older schema that did not work with VS Code extension. If you pick the version - 0.3.256001 - from the AzDO public feed - `dotnet tool update -g upgrade-assistant --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` then you should get an updated SARIF schema version.

**Comment by sunandabalu** [comment]
You can get a Web view using https://microsoft.github.io/sarif-web-component/, we are making changes to the SARIF log to increase readability in the Web view soon.

**Comment by klacol** [comment]
Thank you!
