### ISSUE TITLE
cant install upgrade-assistant

### ISSUE THREAD

**Issue by stokara** [dotnet/upgrade-assistant#947]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

C:\Users\avistokar\Documents\OA>dotnet tool install -g upgrade-assistant
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\avistokar\AppData\Local\Temp\gthvyyew.e44\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\avistokar\AppData\Local\Temp\gthvyyew.e44\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/hc-ms/_packaging/HCMS/nuget/v3/index.json. [C:\Users\avistokar\AppData\Local\Temp\gthvyyew.e44\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\avistokar\AppData\Local\Temp\gthvyyew.e44\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

I tried this :
C:\Users\avistokar\Documents\OA>dotnet tool install -g --interactive  upgrade-assistant

after a long pause I got this:
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error :     [CredentialProvider]Device flow authentication failed. User was presented with device flow, but didn't react within 90 seconds. [C:\Users\avistokar\AppData\Local\Temp\f3aem1rv.vsb\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/hc-ms/_packaging/HCMS/nuget/v3/index.json. [C:\Users\avistokar\AppData\Local\Temp\f3aem1rv.vsb\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(130,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\avistokar\AppData\Local\Temp\f3aem1rv.vsb\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sunandabalu** [comment]
@stokara Please try with `ignore-failed-sources`, this error should go away.

**Comment by sunandabalu** [comment]
https://github.com/dotnet/sdk/issues/18402 to track executing by default with `ignore-failed-sources`
