### ISSUE TITLE
Add ability to choose which Visual Studio installation is used

### ISSUE THREAD

**Issue by adegeo** [dotnet/upgrade-assistant#949]
## Summary

I have multiple editions of Visual Studio installed, including previews. I want the ability to select which edition is being used by the upgrade tool.

## Motivation and goals

It's quite possible that a preview release of Visual Studio will break something, if so, the upgrade tool would be useless until that VS edition is either uninstalled or updated with a fix.

**Comment by sunandabalu** [comment]
@adegeo you can try giving the path to the VS installation by using `--vs-path`.
