### ISSUE TITLE
As a user, I can specify what the end TFM should be

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#95]
We can definitely guide them down the path of choosing this. Initially, though, we need a way to set the value that is used internally.

2/12 Update: follow up on the customer scenarios here.

**Comment by twsouthwick** [comment]
Closing this in favor of #41

**Comment by sunilforever** [comment]
Can someone please show how can I mention the version (.NET 6) while running "upgrade-assistant". I have installed Visual Studio 22 Preview and .NET 6, still its upgrading my projects to .NET 5.

**Comment by mjrousos** [comment]
Hi @sunilforever, the `--target-tfm-support` parameter can be used to specify which .NET release Upgrade Assistant should use when upgrading apps. For .NET 6, you'll want to run `upgrade-assistant upgrade --target-tfm-support Preview ...` where the ... is whatever other arguments you pass like your solution or project path.

**Comment by robinne** [comment]
I have .net 3 and 5 installed but the upgrade assistant seems to ignores "Current" (at time of writing Current = 5.0.9) and tries to use 6.0 Preview:

`PS ...> **upgrade-assistant upgrade --target-tfm-support Current .\ASRTemplateProject.sln**
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-preview.7.21377.19' was not found.
  - The following frameworks were found:
      2.1.28 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      6.0.0-preview.6.21352.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0-preview.7.21377.19&arch=x64&rid=win10-x64`
