### ISSUE TITLE
Got error while installing .NET upgrae assistant

### ISSUE THREAD

**Issue by sankhyac** [dotnet/upgrade-assistant#951]
Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Got the following error while running the below command:

C:\Users\sachak>dotnet tool install -g upgrade-assistant
C:\Program Files\dotnet\sdk\5.0.403\NuGet.targets(131,5): error : Failed to retrieve information about 'upgrade-assistant' from remote source 'https://pkgs.dev.azure.com/msasg/_packaging/57772f9f-5568-4158-b08d-3a6b1de8773d/nuget/v3/flat2/upgrade-assistant/index.json'. [C:\Users\sachak\AppData\Local\Temp\4tdo3cqp.uvv\restore.csproj]
C:\Program Files\dotnet\sdk\5.0.403\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\sachak\AppData\Local\Temp\4tdo3cqp.uvv\restore.csproj]
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sunandabalu** [comment]
@sankhyac Could you try with `ignore-failed-sources`? It should resolve the install problems you are seeing.

**Comment by sunandabalu** [comment]
dotnet/sdk#18402 to track executing by default with ignore-failed-sources
