### ISSUE TITLE
Upgrading the tool fails if I have multiple NuGet package sources

### ISSUE THREAD

**Issue by OliaG** [dotnet/upgrade-assistant#958]
I have multiple NuGet Package Sources on my machine and when I was running

"dotnet tool update -g upgrade-assistant"

seems that the tool only looked at one of my sources (Telerik) even though all of them were turned on, and gave me an error that it couldn't find Upgrade Assistant info 
![image](https://user-images.githubusercontent.com/31997351/143981676-51e5ee18-a0a7-46dd-b74b-f47958f59d60.png)

When I went to VS and turned off all Package Sources except nuget.org:
![image](https://user-images.githubusercontent.com/31997351/143981588-63bc2d73-f501-4eef-8d06-eaaa1435274d.png) 
and reran the command, the upgrade worked: 
![image](https://user-images.githubusercontent.com/31997351/143981737-413fb2ae-a019-43fb-822f-ff195ada6920.png)

**Comment by twsouthwick** [comment]
This is a problem with the way the CLI handles stuff. I think this issue covers a request to ignore that by default: https://github.com/dotnet/sdk/issues/18402
