### ISSUE TITLE
After upgrading an app, large unneeded NuGet package references are added to WinForms projects

### ISSUE THREAD

**Issue by OliaG** [dotnet/upgrade-assistant#960]
After upgrading basic hello world WinForms app created for .NET Framework 4.8, Upgrade Assistant adds references to NuGet packages that are not needed:

![image](https://user-images.githubusercontent.com/31997351/144033693-2317f9af-0dbf-424d-a225-8c8f549af8dd.png)

Microsoft.Windows.Compatibility is extremely large NuGet containing over 20K APIs, we should not be adding it. Plus almost all WinForms APIs are included in net6-windows, so I hardly see a need to add Compatibility package ever.

Possibly same issues with WPF.

**Comment by twsouthwick** [comment]
When should the windows compat pack be added? Or is it now included in .NET 6 if you have a `-windows` TFM?

**Comment by twsouthwick** [comment]
There's a new Roslyn feature to detect unused references. I wonder if we could use that to trim down if we aren't using any types in there
