### ISSUE TITLE
'upgrade-assistant' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by shreeakshaya11** [dotnet/upgrade-assistant#971]
When I try to run the below command I am facing the below issue. Can you let me know what is the correct command I need to provide in order to get the analysis report.

**upgrade-assistant analyze C:\Users\Akshayashree.p\Documents\Workspace\ui\DLZADM_UI\DLZADM_UI.csproj
'upgrade-assistant' is not recognized as an internal or external command,
operable program or batch file.Problem encountered on https://dotnet.microsoft.com/platform/upgrade-assistant/tutorial/install-upgrade-assistant**

Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by twsouthwick** [comment]
Have you installed it? Once you run `dotnet tool install -g upgrade-assistant` that command should work.

**Comment by shreeakshaya11** [comment]
I have installed the upgrade assistant but not able run analyze command.

**Comment by jlugogarcia** [comment]
If you had installed this tool previously try doing first:

`dotnet tool update -g upgrade-assistant`

**Comment by nandostyle** [comment]
I am was having this very same issue.  I fix it by re-installing the tool with a command prompt in Admin mode.

**Comment by vishnuramero** [comment]
same issue when using upgrade tool to upgrade xamarin forms to maui using Mac (MacOS Monterey)

`zsh: command not found: upgrade-assistant`

**Comment by brandonh-msft** [comment]
> same issue when using upgrade tool to upgrade xamarin forms to maui using Mac (MacOS Monterey)
> 
> `zsh: command not found: upgrade-assistant`

UA does not support Mac at this time

**Comment by lukedukeus** [comment]
Any clue what I'm missing? I'm on Win 11 21H2.
![error](https://user-images.githubusercontent.com/23089287/196477419-93e7a408-70ae-46b9-b3ff-400d47f25b5d.jpg)

**Comment by 1saeedsalehi** [comment]
I got the same problem on Mac (Apple Silicon chip),

- dotnet-sdk installed,
- upgrade-assistant could be found under the `~/.dotnet/tools` directory

![Image](https://github.com/user-attachments/assets/fc30126c-40d6-45eb-bbe0-d6c90aa2bcbb)
