### ISSUE TITLE
couldn;t able to install upgrade assistant

### ISSUE THREAD

**Issue by Sacwith** [dotnet/upgrade-assistant#975]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by sunandabalu** [comment]
@Sacwith Are you able to install / restore any other nuget packages?

**Comment by brandonh-msft** [comment]
Closing stale issues; if you're able to provide current repro, though, let us know.
