### ISSUE TITLE
Could not load project. Please ensure the selected VS instance has the correct workloads installed for your projects.

### ISSUE THREAD

**Issue by fiddyschmitt** [dotnet/upgrade-assistant#994]
### Describe the bug
While trying to upgrade the WebDAVSharp.Server project from .NET 4.5 to .NET 6, upgrade-assistant says that it cannot load the project, even though Visual Studio 2019 and 2022 load and compile it with issue.

### To Reproduce

1. Download the WebDAVSharp.Server from [here](https://github.com/WebDAVSharp/WebDAVSharp.Server)
2. Run `upgrade-assistant upgrade "WebDAVSharp.Server.csproj"`

### Exceptions (if any)
`[16:42:25 ERR] Project C:\Temp\WebDAVSharp.Server.csproj cannot be loaded: Could not load project. Please ensure the selected VS instance has the correct workloads installed for your projects. If Upgrade Assistant selected the incorrect VS version, please pass the argument --vs-path with the appropriate path. You can see the Visual Studio instances searched by running with the --verbose flag.`

### Further technical details
- Windows 64-bit
- Output of `dotnet --list-sdks`
```
2.1.617 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.818 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.210 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
```

- Output of `upgrade-assistant --version`
`0.3.261602+efb3cc30a24e699e6e4337f263a2b9478f04f618`

upgrade-assistant.clef.txt has been attached

[upgrade-assistant.clef.txt](https://github.com/dotnet/upgrade-assistant/files/7797427/upgrade-assistant.clef.txt)

**Comment by sunandabalu** [comment]
@fiddyschmitt Have you tried this `If Upgrade Assistant selected the incorrect VS version, please pass the argument --vs-path with the appropriate path. ` like mentioned in the error message? Sometimes when there are multiple VS installation upgrade-assistant might choose the wrong one and give the error missing workloads.

**Comment by fiddyschmitt** [comment]
> @fiddyschmitt Have you tried this `If Upgrade Assistant selected the incorrect VS version, please pass the argument --vs-path with the appropriate path. ` like mentioned in the error message? Sometimes when there are multiple VS installation upgrade-assistant might choose the wrong one and give the error missing workloads.

Thanks @sunandabalu; yes I tried pointing it toe VS2019 and had the same result.

`upgrade-assistant upgrade "WebDAVSharp.Server.csproj" --vs-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"`

Thanks!
Fidel

**Comment by Whatever-6** [comment]
I have the exact same problem with my solution. 
You can run your command with the following parameter at the end
`--verbose`
This will get you more information on why it is failing or what sort of "workloads" are missing. Look especially on the [Failure] Log entries.

For me he had problems with some of my paths in the .csproj like for example
`<Import Project="$(SolutionDir)..\Dependencies\`
which I had to replace with the absolute path to get it working e.g: 
`C:\Repos\Whatever\Dependencies\`

It is still not running for me tho. I still get the same error:
"Could not load project. Please ensure the selected VS instance has the correct workloads installed for your projects."

When I run it with the --verbose parameter I get the following Failure log entry:
`[Failure] Problem loading file in MSBuild workspace Msbuild failed when processing the file 'C:\Repos\Whatever\BaseInterfaces\Sources\DialogsInterfaces\DialogsInterfaces.csproj' with message: C:\Program Files\dotnet\sdk\5.0.404\Microsoft.CSharp.CurrentVersion.targets: (130, 9): Could not find rule set file "ManagedMinimumRules.ruleset".`

I get this error for every referenced project and I don't know why.
The file "Microsoft.CSharp.CurrentVersion.targets" is at the correct location, but I do not know why he search for ManagedMinimumRules.ruleset and why he does not find it.

I might open a new issue for my problem, unless your --verbose gives out a similar error.

**Comment by fiddyschmitt** [comment]
> I have the exact same problem with my solution. 
> You can run your command with the following parameter at the end
> `--verbose`
> This will get you more information on why it is failing or what sort of "workloads" are missing. Look especially on the [Failure] Log entries.
> 
> For me he had problems with some of my paths in the .csproj like for example
> `<Import Project="$(SolutionDir)..\Dependencies\`
> which I had to replace with the absolute path to get it working e.g: 
> `C:\Repos\Whatever\Dependencies\`
> 
> It is still not running for me tho. I still get the same error:
> "Could not load project. Please ensure the selected VS instance has the correct workloads installed for your projects."
> 
> When I run it with the --verbose parameter I get the following Failure log entry:
> `[Failure] Problem loading file in MSBuild workspace Msbuild failed when processing the file 'C:\Repos\Whatever\BaseInterfaces\Sources\DialogsInterfaces\DialogsInterfaces.csproj' with message: C:\Program Files\dotnet\sdk\5.0.404\Microsoft.CSharp.CurrentVersion.targets: (130, 9): Could not find rule set file "ManagedMinimumRules.ruleset".`
> 
> I get this error for every referenced project and I don't know why.
> The file "Microsoft.CSharp.CurrentVersion.targets" is at the correct location, but I do not know why he search for ManagedMinimumRules.ruleset and why he does not find it.
> 
> I might open a new issue for my problem, unless your --verbose gives out a similar error.

Thanks, I'll check tonight

**Comment by fiddyschmitt** [comment]
Hi @Whatever-6,

I see a different error:
`[Failure] Problem loading file in MSBuild workspace Msbuild failed when processing the file 'C:\Users\fiddy\Desktop\dev\cs\WebDAVSharp.Server-master\WebDAVSharp.Server.csproj' with message: The imported project "C:\Users\fiddy\Desktop\dev\cs\.nuget\nuget.targets" was not found.`

Full log [Here](https://github.com/dotnet/upgrade-assistant/files/7832899/verbose-2022.txt)

But thanks for the `--verbose` recommendation! I was able to upgrade successfully by first commenting out the NuGet line in the csproj file:
`<!--<Import Project="$(SolutionDir)\.nuget\nuget.targets" />-->`

Cheers,
Fidel

**Comment by exaiwitmx** [comment]
> When I run it with the --verbose parameter I get the following Failure log entry: `[Failure] Problem loading file in MSBuild workspace Msbuild failed when processing the file 'C:\Repos\Whatever\BaseInterfaces\Sources\DialogsInterfaces\DialogsInterfaces.csproj' with message: C:\Program Files\dotnet\sdk\5.0.404\Microsoft.CSharp.CurrentVersion.targets: (130, 9): Could not find rule set file "ManagedMinimumRules.ruleset".`
> 

I also had this error and could resolve it by giving correct full paths in <CodeAnalysisRuleSetDirectories> and <CodeAnalysisRuleDirectories> - either in each and every project file or globally in Directory.build.targets:

`<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<CodeAnalysisRuleSetDirectories>;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Static Analysis Tools\Rule Sets</CodeAnalysisRuleSetDirectories>
		<CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
		<CodeAnalysisRuleDirectories>;C:\Program Files\Microsoft Visual Studio\2022\Professional\Team Tools\Static Analysis Tools\FxCop\Rules</CodeAnalysisRuleDirectories>
		<CodeAnalysisIgnoreBuiltInRules>true</CodeAnalysisIgnoreBuiltInRules>`

See:
https://stackoverflow.com/a/33020602/13039722

However, I still get the following error:

`[18:26:49 DBG] Unable to resolve assembly Microsoft.Build.resources, Version=15.1.0.0, Culture=de-DE, PublicKeyToken=b03f5f7f11d50a3a
[18:26:49 DBG] Unable to resolve assembly Microsoft.DotNet.UpgradeAssistant.MSBuild.resources, Version=0.4.0.0, Culture=de-DE, PublicKeyToken=31bf3856ad364e35
[18:26:49 DBG] Unable to resolve assembly Microsoft.DotNet.UpgradeAssistant.MSBuild.resources, Version=0.4.0.0, Culture=de, PublicKeyToken=31bf3856ad364e35
[18:26:50 ERR] Could not load project. Please ensure the selected VS instance has the correct workloads installed for your projects. If Upgrade Assistant selected the incorrect VS version, please pass the argument --vs-path with the appropriate path. You can see the Visual Studio instances searched by running with the --verbose flag. If you are migrating UWP to Windows App SDK project, make sure you are using the latest version of VS 2022 (>17.2)
[18:26:50 DBG] Hosting started
[18:26:50 DBG] Hosting stopping
[18:26:50 DBG] Hosting stopped
[18:26:50 DBG] UA_NuGet0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_BinaryAnalysis0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_Default0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_try-convert0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_VB0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_Web0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_windows0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_MAUI0ebd45413b4949ea8c0b639b207ae8ee extension is unloading
[18:26:50 DBG] UA_WCFUpdater0ebd45413b4949ea8c0b639b207ae8ee extension is unloading`

I cannot find any indication which project causes this error and what the exact problem might be as I cannot find any error message. I assume that the unresolved resource assemblys don't pose any problem?!

**Comment by LegacyOfKain** [comment]
I had the same issue with upgrade assistant for a project. I downgraded the version and it worked
dotnet tool uninstall --global upgrade-assistant
dotnet tool install --global upgrade-assistant --version 0.4.355802
